### ISSUE TITLE
My tests seemed to hang, but I was waiting on a Downloader.download

### ISSUE THREAD

**Issue by q42jaap** [flapdoodle-oss/de.flapdoodle.embed.mongo#103]
I'm using play2 with specs2 as the test framework. Using jstack I got this stacktrace:

"pool-4-thread-2" prio=6 tid=0x000000002826f000 nid=0x1bc4 runnable [0x0000000029d7c000]
   java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    - locked <0x00000007c55f7c70> (a java.io.BufferedInputStream)
    at sun.net.www.MeteredStream.read(MeteredStream.java:134)
    - locked <0x00000007c55facd8> (a sun.net.www.http.KeepAliveStream)
    at java.io.FilterInputStream.read(FilterInputStream.java:133)
    at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3053)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
    - locked <0x00000007c56113f0> (a java.io.BufferedInputStream)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:89)
    at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
    at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribution(CachingArtifactStore.java:56)
    at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)

The console however didn't mention anything, it seemed the tests we just stuck.
The download is very slow, so I tought everything was broken. Is it normal that the logs don't mention this? Or is our logging setup during tests the reason nothing is logged?

**Comment by Loki-Afro** [comment]
There is now some kind of _progressbar_ since this ticket didn't receive any further input I will close it for now.
