### ISSUE TITLE
Use of locally installed mongod

### ISSUE THREAD

**Issue by dazraf** [flapdoodle-oss/de.flapdoodle.embed.mongo#123]
Hi,

I commented about this on a separate issue. Thought it best to raise as a proper one.
Is it possible to point embed.mongo to directly use a locally installed instance of mongod - i.e. parameterised using a full path to the executable? 
(There are just too many headaches with our local repositories and firewall to use the standard approach).

Many thanks
Fuzz.

**Comment by michaelmosmann** [comment]
Ah.. understand. 

Quickfix: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/89#issuecomment-66312790

**Comment by michaelmosmann** [comment]
...or you can configure an alternative download location (behind your firewall) where you put all needed mongo-dist archives. 

everything else will take much longer to implement..

**Comment by dazraf** [comment]
Made it work like this :-)

```
 private final static IRuntimeConfig config = new RuntimeConfigBuilder()
            .defaults(Command.MongoD)
            .artifactStore(new ArtifactStoreBuilder()
                    .executableNaming((s, s1) -> s + s1)
                    .tempDir(new PlatformTempDir())
                    .downloader(new Downloader())
                    .download(new DownloadConfigBuilder()
                                    .downloadPrefix("")
                                    .artifactStorePath(new PlatformTempDir())
                                    .downloadPath(new File(mongodBinDirectory).toURI().toString())
                                    .fileNaming((s, s1) -> s + s1)
                                    .progressListener(new Slf4jProgressListener(logger))
                                    .userAgent("")
                                    .packageResolver(
                                            new IPackageResolver() {
                                                @Override
                                                public FileSet getFileSet(Distribution distribution) {
                                                    return FileSet.builder().addEntry(FileType.Executable, getPath(distribution)).build();
                                                }

                                                @Override
                                                public ArchiveType getArchiveType(Distribution distribution) {
                                                    return ArchiveType.EXE;
                                                }

                                                @Override
                                                public String getPath(Distribution distribution) {
                                                    return mongodExecutableFileName; 
                                                }
                                            })
                                    .build()
                    ).build())
            .build();
```

**Comment by michaelmosmann** [comment]
if it works once, it will work most of the time.. :) and the worst thing is a red test..

**Comment by dazraf** [comment]
:-) in fact, if I terminate a test, restarting i get 

```
com.rbs.datafabric.server.testing.MongodProcessException: de.flapdoodle.embed.process.exceptions.DistributionException: de.flapdoodle.embed.process.extract.ExecutableFileAlreadyExistsException: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: Could not create Tempfile: c:\temp\extractmongod.exe
	at com.rbs.datafabric.server.testing.MongodProcess.start(MongodProcess.java:97)
	at com.rbs.datafabric.server.command.store.mongo.AbstractMongoDBTest.startMongod(AbstractMongoDBTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: de.flapdoodle.embed.process.extract.ExecutableFileAlreadyExistsException: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: Could not create Tempfile: c:\temp\extractmongod.exe
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:68)
	at com.rbs.datafabric.server.testing.MongodProcess.start(MongodProcess.java:94)
	... 23 more
Caused by: de.flapdoodle.embed.process.extract.ExecutableFileAlreadyExistsException: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: Could not create Tempfile: c:\temp\extractmongod.exe
	at de.flapdoodle.embed.process.extract.FilesToExtract$Match.write(FilesToExtract.java:107)
	at de.flapdoodle.embed.process.extract.ArchiveIsFileExtractor.extract(ArchiveIsFileExtractor.java:50)
	at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:74)
	at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.use(CachingArtifactStore.java:132)
	at de.flapdoodle.embed.process.store.CachingArtifactStore.extractFileSet(CachingArtifactStore.java:78)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
	... 24 more
Caused by: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: Could not create Tempfile: c:\temp\extractmongod.exe
	at de.flapdoodle.embed.process.io.file.Files.createTempFile(Files.java:68)
	at de.flapdoodle.embed.process.extract.FilesToExtract$Match.write(FilesToExtract.java:105)
	... 29 more

```

**Comment by julien-may** [comment]
I just created a PR (https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/30) that includes a new ArtifactStore to define the location of an extracted Artifact. So it is actually possible to refer to an already installed version of mongodb.

**Comment by sylvain-charton** [comment]
+1 to the PR. please review it.

**Comment by michaelmosmann** [comment]
Did a merge ..
need some time to make releases..

**Comment by michaelmosmann** [comment]
Did some refactoring.. Have a look at: https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/store/StaticArtifactStoreBuilder.java

**Comment by dazraf** [comment]
This looks very good. Will give it a go this week. The solution we use right now works well for setting up MDB for our local integration tests. It's been fairly solid. Issues are: a fair bit of custom code that only i understand; and a bug where the temporary artifices and logs remain after the test is run. Anyhow, will feed back here any results. Thanks again.

**Comment by torsten-liermann** [comment]
I would like to embed mongodb in a product. When the application starts, the mongo daemon should also be started, when the application is finished, the mongo daemon should also be terminated. It looks like I can easily do that with mongo embed. The only way to avoid downloading and unpacking the artifact is to implement IArtifactStore. Am I correct?

Thanks for a tip.

**Comment by ogerardin** [comment]
@torsten-liermann I have a similar requirement, here's how I have done it:

-the mongodb distributable (zip) is bundled as a Java resource, for example in directory /bundled/mongodb/win32 (for the Windows version). You can also bundle the versions for several platforms by placing them in the appropriate folders.

-I use a customized IDownloadConfig as follows:

    protected IDownloadConfig getDownloadConfig() {
        return new DownloadConfigBuilder()
                .defaultsForCommand(Command.MongoD)
                .downloadPath("classpath:/bundled/mongodb/")
                .build();
    }

The trick is to use a URL with the "classpath" protocol. Spring has the machinery to extract resources from such URLs, so essentially you just trick de.flapdoodle.embed.mongo into downloading from the classpath instead of a network URL. The full URL will be constructed just as it would be with a "http" URL, so you should take care to use the distributable file that matches exactly the combination of platform / version / features that you will be using.

The executable will be extracted and cached as it would have been if the zip had been downloaded from the web, and the next time the download/extract phase will be skipped.
