### ISSUE TITLE
OutOfMemoryError in LogWatchStreamProcessor when running many commands

### ISSUE THREAD

**Issue by danielFesenmeyer** [flapdoodle-oss/de.flapdoodle.embed.mongo#124]
When running many commands (e.g. 100.000 inserts with the async Mongo Java driver), an OutOfMemoryError occurs:

Exception in thread "Thread-4" java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Unknown Source)
at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
at java.lang.AbstractStringBuilder.append(Unknown Source)
at java.lang.StringBuilder.append(Unknown Source)
at java.lang.StringBuilder.append(Unknown Source)
at java.lang.AbstractStringBuilder.append(Unknown Source)
at java.lang.StringBuilder.append(Unknown Source)
at de.flapdoodle.embed.process.io.LogWatchStreamProcessor.process(LogWatchStreamProcessor.java:52)
at de.flapdoodle.embed.process.io.ReaderProcessor.run(ReaderProcessor.java:52)

**Comment by michaelmosmann** [comment]
ah.. yes.. i think i know the cause..

**Comment by Loki-Afro** [comment]
@michaelmosmann is it fixed? :)

**Comment by michaelmosmann** [comment]
Hmm..Not sure.

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 4. März 2017 1:26:16 nachm. schrieb Phillip <notifications@github.com>:

**Comment by Loki-Afro** [comment]
Seems to be fixed ...

I tested it with the following code:
```
    @Test
    public void blub() throws IOException {
        MongodForTestsFactory factory = null;
        try {
            factory = MongodForTestsFactory.with(Version.Main.PRODUCTION);
            MongoClient mongo = factory.newMongo();
            DB db = mongo.getDB("test-" + UUID.randomUUID());
            DBCollection col = db.createCollection("testCol", new BasicDBObject());
            col.save(new BasicDBObject("testDoc", new Date()));
            for (int i = 0; i < Integer.MAX_VALUE; i++) {
                col.save(new BasicDBObject("testDoc" + 1, new Date()));
            }
        } finally {
            if (factory != null) {
                factory.shutdown();
            }
        }
    }
```

with `-Xmx1024m -Xms1024m`.

![screen shot 2017-03-11 at 14 10 01](https://cloud.githubusercontent.com/assets/4738445/23823533/b768d660-0664-11e7-95fc-bfb0f1284c08.png)
