### ISSUE TITLE
Update to the latest version of  mongo-java-driver.

### ISSUE THREAD

**Issue by vkozubal** [flapdoodle-oss/de.flapdoodle.embed.mongo#128]
In order to use the latest version of mongo-java-driver on client side, update the version of mongo-java-driver to 3.x.

I am getting the following error when using 3.0.2

`java.lang.NoSuchMethodError: com.mongodb.DBRef.<init>(Lcom/mongodb/DB;Ljava/lang/String;Ljava/lang/Object;)V
	at org.springframework.data.mongodb.core.convert.DefaultDbRefResolver.createDbRef(DefaultDbRefResolver.java:104)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.createDBRef(MappingMongoConverter.java:818)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.createCollection(MappingMongoConverter.java:557)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writePropertyInternal(MappingMongoConverter.java:457)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$4.doWithAssociation(MappingMongoConverter.java:438)
	at org.springframework.data.mapping.model.BasicPersistentEntity.doWithAssociations(BasicPersistentEntity.java:324)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:432)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writeInternal(MappingMongoConverter.java:386)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:350)
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.write(MappingMongoConverter.java:77)
	at org.springframework.data.mongodb.core.MongoTemplate.toDbObject(MongoTemplate.java:732)
	at org.springframework.data.mongodb.core.MongoTemplate.doSave(MongoTemplate.java:882)
	at org.springframework.data.mongodb.core.MongoTemplate.save(MongoTemplate.java:833)
	at org.springframework.data.mongodb.repository.support.SimpleMongoRepository.save(SimpleMongoRepository.java:73)`

**Comment by matlockx** [comment]
done with #131 
You can use the new version 1.48.0 from maven central. Should be available in the next hours...
