### ISSUE TITLE
Cannot run on NixOS

### ISSUE THREAD

**Issue by a1russell** [flapdoodle-oss/de.flapdoodle.embed.mongo#142]
I'm on NixOS 15.09 stable, and trying to use this in one of my apps, I get this stacktrace:

```
Extract /home/user/.embedmongo/linux/mongodb-linux-x86_64-3.0.2.tgz START
Extract /home/user/.embedmongo/linux/mongodb-linux-x86_64-3.0.2.tgz DONE
java.io.IOException: Cannot run program "/tmp/extract-5b9a453a-ee43-4572-9348-068c4706dcd0mongod": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:98)
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
    at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
    at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
    ...
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at cucumber.runtime.Utils$1.call(Utils.java:34)
    at cucumber.runtime.Timeout.timeout(Timeout.java:13)
    at cucumber.runtime.Utils.invoke(Utils.java:30)
    at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:59)
    at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:222)
    at cucumber.runtime.Runtime.runHooks(Runtime.java:210)
    at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:200)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
    at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:163)
    at cucumber.runtime.Runtime.run(Runtime.java:120)
    at cucumber.api.cli.Main.run(Main.java:36)
    at cucumber.api.cli.Main.main(Main.java:18)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 28 more
```

The file does exist:

```
$ ls -l /tmp/extract-5b9a453a-ee43-4572-9348-068c4706dcd0mongod 
-rwxr--r-- 1 user group 22335592 Dec 16 11:15 /tmp/extract-5b9a453a-ee43-4572-9348-068c4706dcd0mongod
$ file /tmp/extract-5b9a453a-ee43-4572-9348-068c4706dcd0mongod 
/tmp/extract-5b9a453a-ee43-4572-9348-068c4706dcd0mongod: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.9, stripped
$ uname -a
Linux hostname 3.18.24 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
```

This is the source of the MongoDB package on NixOS: https://github.com/NixOS/nixpkgs/blob/release-15.09/pkgs/servers/nosql/mongodb/default.nix

So it seems like on my OS things need to be built from source.

Is there any way to get this library to work with a system that isn't compatible with the pre-built, downloaded binary?

**Comment by michaelmosmann** [comment]
Hmm.. not sure.. 
can you execute the file?

is there any selinux enabled?

**Comment by a1russell** [comment]
No to both questions, unfortunately. I imagine it's just because NixOS is weird and doesn't put anything where it might be on other distros, causing a dynamically linked executable to probably not be able to find what it needs.

I mean, I do have mongo installed on my own machine, and it works fine, but it's via the Nix package manager.

This library works fine and is helpful on other machines, but I just can't get the acceptance tests to pass on my machine because it's this OS. One option that might work would be to tell this library somehow to just use my system's Mongo. Would that be outside the scope of this project?

**Comment by michaelmosmann** [comment]
IMHO you can do that.. i should have a look..
.. strange exception by the way.. 

maybe i should have a look into nixos to solve this..

**Comment by a1russell** [comment]
@michaelmosmann That would be great! I'd be glad to try and answer any questions that you end up with, as well.

**Comment by michaelmosmann** [comment]
it will take a little... today is star wars.. :)

**Comment by a1russell** [comment]
@michaelmosmann I hear you. No spoilers, please! I won't see it until Christmas. ;-)

**Comment by michaelmosmann** [comment]
@a1russell  .. not from me:) ..

**Comment by a1russell** [comment]
Any luck on this? I'm working on another project that's using this lib, and I can't run it.

**Comment by michaelmosmann** [comment]
Not so far... I will try again in the next days... :)

**Comment by a1russell** [comment]
Thanks! Again I'll be glad to answer any questions.

**Comment by eikek** [comment]
Hi, 
I'm running into the same problem. The problem with prebuild binaries on nixos is indeed that the dynamic linked libs cannot be found. Nixos does not have a /lib or /lib64, for example.

For me also, it would be just great if I could define the executable from my system to be used. I could not figure out how to do this.

**Comment by slanglois** [comment]
(In case you stumbed upon this issue because you get this error message, but are not on NixOS, chances are the download of MongoDB failed for some reason. Just delete your ```~/.embedmongo```. HTH! :-)

**Comment by eikek** [comment]
I'm on NixOS, but thanks anyways! I now symlinked my systems mongod executable into the `~/.embedmongo/extracted/Linux-*/` directory. This is not nice but works and is sufficient for me :-)

**Comment by Loki-Afro** [comment]
> NixOS is a Linux distribution with a unique approach to package and configuration management. 

@eikek @a1russell what did you expect? 

Just making fun :D

**Comment by Loki-Afro** [comment]
Since there is a NixOs workaround ... I will close this issue. If you have a solution which works for everyone , let me know.
