### ISSUE TITLE
Embedded MongoDB fails to shutdown gracefully in Spring Boot webapp

### ISSUE THREAD

**Issue by vpavic** [flapdoodle-oss/de.flapdoodle.embed.mongo#152]
Originally reported as spring-projects/spring-boot#5487.

The problem can be reproduced using Spring Boot's [`spring-boot-sample-data-mongodb`](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-data-mongodb) app, changing it to a web application using the following patch:

``` diff
diff --git spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml
index 1ff97bb..ff92880 100644
--- spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml
+++ spring-boot-samples/spring-boot-sample-data-mongodb/pom.xml
@@ -21,7 +21,7 @@
        <dependencies>
                <dependency>
                        <groupId>org.springframework.boot</groupId>
-                       <artifactId>spring-boot-starter</artifactId>
+                       <artifactId>spring-boot-starter-web</artifactId>
                </dependency>
                <dependency>
                        <groupId>org.springframework.boot</groupId>
```

Shutting down the app generates the following output:

```
2016-03-24 20:17:32.379  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] got signal 2 (Interrupt), will terminate after current cmd ends
2016-03-24 20:17:32.379  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] now exiting
2016-03-24 20:17:32.379  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] dbexit: 
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: going to close listening sockets...
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] closing listening socket: 5
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] closing listening socket: 7
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] removing socket file: /tmp/mongodb-41282.sock
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: going to flush diaglog...
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: going to close sockets...
2016-03-24 20:17:32.380  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: waiting for fs preallocator...
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.378+0100 [signalProcessingThread] shutdown: closing all files...
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.379+0100 [signalProcessingThread] closeAllFiles() finished
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.379+0100 [signalProcessingThread] shutdown: removing fs lock...
2016-03-24 20:17:32.381  INFO 8202 --- [       Thread-3] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2016-03-24T20:17:32.379+0100 [signalProcessingThread] dbexit: really exiting now
2016-03-24 20:17:32.383  INFO 8202 --- [       Thread-7] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@446cdf90: startup date [Thu Mar 24 20:17:25 CET 2016]; root of context hierarchy
2016-03-24 20:17:32.385  INFO 8202 --- [       Thread-7] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2016-03-24 20:17:32.393  WARN 8202 --- [       Thread-1] d.flapdoodle.embed.mongo.runtime.Mongod  : sendShutdown /127.0.0.1:41282

java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_74]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_74]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_74]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_74]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_74]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_74]
    at de.flapdoodle.embed.mongo.runtime.Mongod.sendShutdown(Mongod.java:86) ~[de.flapdoodle.embed.mongo-1.50.2.jar!/:na]
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.sendStopToMongoInstance(AbstractMongoProcess.java:133) [de.flapdoodle.embed.mongo-1.50.2.jar!/:na]
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:107) [de.flapdoodle.embed.mongo-1.50.2.jar!/:na]
    at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170) [de.flapdoodle.embed.process-1.50.1.jar!/:na]
    at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:73) [de.flapdoodle.embed.process-1.50.1.jar!/:na]
    at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:90) [de.flapdoodle.embed.process-1.50.1.jar!/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]

2016-03-24 20:17:32.494  WARN 8202 --- [       Thread-1] d.f.embed.mongo.AbstractMongoProcess     : could not stop mongod with db command, try next
2016-03-24 20:17:32.506  INFO 8202 --- [       Thread-1] d.f.e.process.runtime.ProcessControl     : execSuccess: false [kill, -2, 8226]
2016-03-24 20:17:32.506  WARN 8202 --- [       Thread-1] d.f.embed.mongo.AbstractMongoProcess     : could not stop mongod, try next
2016-03-24 20:17:32.507  WARN 8202 --- [       Thread-1] d.f.embed.mongo.AbstractMongoProcess     : could not stop mongod the second time, try one last thing
```

This happens regardless of the way the app is run - I've tried Intellij IDEA, `mvn spring-boot:run` and `java -jar`. However using `SIGINT` manages to shut it down correctly, as explained in the original issue.

**Comment by albertmatyi** [comment]
I noticed a similar issue but in my case the problem was that by a failure I've defined an alternative `Mongo` bean via an implementation of `AbstractMongoConfiguration` so there were two Beans managing the same in memory instance. 
In my case that is what caused the problem. As soon as I removed the second bean (configuration class) the problem disappeared. Just an idea

Cheers,
m

**Comment by michaelmosmann** [comment]
Is this still an issue?

**Comment by albertmatyi** [comment]
No, my issue was that my integration tests were not reusing the Spring context, and the contexts was cached thus the Embedded MongoDB was never shut down, and a new one for a new context could not be started.

**Comment by vpavic** [comment]
@michaelmosmann Yes, the problem is still present. It was originally reported against ```1.50.2``` however I've just checked against ```1.50.5``` and situation is the same.

Steps to reproduce:

```bash
git clone git@github.com:spring-projects/spring-session.git
cd spring-session
./gradlew :samples:mongo:bootRun
```

After the app has been started, SIGINT (Ctrl+C) to stop it generates the stacktrace from the original comment.

**Comment by Loki-Afro** [comment]
@vpavic what is the current gradle command that will produce the error?

**Comment by vpavic** [comment]
Hi @Loki-Afro, we did some refactoring of the samples in the meanwhile, the current command to run sample app that uses embedded Mongo is `./gradlew :spring-session-samples-boot-mongo:bootRun`.

That being said, I cannot reproduce the original problem with either of our active branches (`master` and `1.4.x`) so I'll close this issue. Thanks.
