### ISSUE TITLE
java.io.IOException: Could not start process: <EOF>

### ISSUE THREAD

**Issue by kajsa** [flapdoodle-oss/de.flapdoodle.embed.mongo#167]
I'm only seeing this error on our CI machine, a SLES 10.2 box (kernel version 2.6.16.60-0.21-smp). I get the error both running through Jenkins and from a workspace I cloned on that machine to try to debug. The same code runs fine on my Mac, my co-workers Mac, and elsewhere on a OLE 6.3.1 box (kernel version 2.6.32-279.11.1.el6.x86_64). Here's the exception:

```
java.io.IOException: Could not start process: <EOF>
at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) ~[de.flapdoodle.embed.mongo-1.50.5.jar:na]
at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114) ~[de.flapdoodle.embed.process-1.50.2.jar:na]
at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) ~[de.flapdoodle.embed.mongo-1.50.5.jar:na]
at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) ~[de.flapdoodle.embed.mongo-1.50.5.jar:na]
at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) ~[de.flapdoodle.embed.mongo-1.50.5.jar:na]
at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) ~[de.flapdoodle.embed.mongo-1.50.5.jar:na]
at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101) ~[de.flapdoodle.embed.process-1.50.2.jar:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1645) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
... 
```

This is a Spring Boot application, that makes heavy use of auto-configuration, but I'm specifying the IRuntimeConfig like so, because I need to provide the proxy info:

```
@Primary
@Bean
IRuntimeConfig runtimeConfig()
{
    final Command command = Command.MongoD;
    return new RuntimeConfigBuilder()
        .defaults(command)
        .artifactStore(new ExtractedArtifactStoreBuilder()
                           .defaults(command)
                           .download(new DownloadConfigBuilder()
                                         .defaultsForCommand(command)
                                         .proxyFactory(new HttpProxyFactory("proxy.employer.com", 80))
                                         .build()))
        .build();
}
```

I've tried the workaround mentioned on another ticket of setting LC_ALL=C, to no avail. Let me know if there's any additional information I should gather.

**Comment by firatkucuk** [comment]
Same here,
I use default spring boot configuration on my server. But it throws IoException.
Strange but it works on desktop.

**Comment by magiccrafter** [comment]
This problem happens only if your environment is configured to run on 32bit java. 
Try running with 64bit java and the issue should disappear.
Short explanations is that during mongod initialization, based on the java platform, the embedded-mongo will decide which mongod build to use. For the 32bit monogod build, the default "wiredTiger" storage engine is not available and the process could not start.

**Comment by firatkucuk** [comment]
Setting locale fixed my problem.

http://stackoverflow.com/questions/26337557/badvalue-invalid-or-no-user-locale-set-please-ensure-lang-and-or-lc-environme

**Comment by chuspb** [comment]
Hi, same issue here. I've also try setting locales... but no way. If I run the same command (directly in the shell) that Jenkins executes, then it works fine. I don't know what more to do.

/etc/default/locale:
LANG="en_US.UTF-8"
LANGUAGE="en_US"
LC_ALL="en_US.UTF-8"

/etc/environment:
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

Also:
locale-gen en_US.UTF-8
dpkg-reconfigure locales

Any help? Thanks!

**Comment by donabrams** [comment]
I've gotten this multiple times when mongo gets corrupted (through various means). The easiest way to find the root cause is to start up mongo again in whatever directory it was started before. You'll see real error messages come out. It would be helpful if, upon finding EOF, the entire mongo log was printed to the console.

**Comment by francisdb** [comment]
version `2.0.0` seems to at least got rid of this specific error for us, and my guess is that one of the reasons we have seen this is out of memory errors while starting mongo

**Comment by keklabs** [comment]
We have the same problem. 

After investigating source code, the problem is in realization of [de/flapdoodle/embed/process/distribution/BitSize.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/586ff5c964edfc4fdd35d1444a5a20d6be44f5b0/src/main/java/de/flapdoodle/embed/process/distribution/BitSize.java)

according to [javas-osarch-system-property-is-the-bitness-of-the-jre-not-the-operating-system](http://mark.koli.ch/javas-osarch-system-property-is-the-bitness-of-the-jre-not-the-operating-system)  and [how-can-i-check-the-bitness-of-my-os](https://stackoverflow.com/questions/4748673/how-can-i-check-the-bitness-of-my-os-using-java-j2se-not-os-arch/5940770#5940770)

the implementation resolves the bitness of JRE/JDK  not bitness of OS. 

I´m searching for way, how to configure/change this behavior by some system environment settings or by other way.

**Comment by Loki-Afro** [comment]
@keklabs so you are running an 32 bit JDK on a 64 Bit machine? I had cases where java won't even start, why would you do that?

**Comment by Alexaas** [comment]
Similar issue here during maven build. Running on Win10 64 bit. JAVA_HOME is set to 64bit JDK. Any idea??
`Caused by: java.io.IOException: Could not start process: <EOF>
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)`

**Comment by mainedufresne** [comment]
I am also getting this or a very similar issue. I'm attempting to build with gradle inside a Docker container. My Docker image is based on frolvlad/alpine-oraclejdk8 due to reading that this problem could be caused by not having glibc. The build works on my local machine (OS X) but fails inside the container. I've tried versions 1.50.3, 1.50.5, and 2.0.0 all fail the same way.

**Comment by mainedufresne** [comment]
I figured it out. The following worked for me in my Dockerfile:

`FROM frolvlad/alpine-oraclejdk8 AS build
WORKDIR /build-env
ADD . /build-env
RUN apk update &&  apk add bash && apk add libstdc++
ENV LC_ALL=C
RUN ./gradlew build`

**Comment by Florian-Maurer** [comment]
@Alexaas I have a very similar problem to yours in my project, did you find any solution for this error?

**Comment by Loki-Afro** [comment]
@Florian-Maurer make sure JDK and OS architecture match

**Comment by bertramn** [comment]
The problem on Windows seems to be related to MongoDB 3.6.0, running the extracted mongod executable in `%USERPROFILE%\.embedmongo\extracted\Windows-B64--3.6.0` abruptly ends cause the mongod process fails to locate `libeay32.dll` and `ssleay32.dll`. Throwing the ddls into the extract folder does not seem to work either. Running the same with MongoDB 3.4.1 works fine.

Having said that, MongoDB 3.6.0 does not run on RHEL either out of the box or with any of the locale hacks from above.

```
[INFO] Running io.github.bertramn.mongodb.test.MongoRuleIntegrationTest
23:06:46.873 [main] ERROR d.f.e.p.runtime.AbstractProcess - failed to call onAfterProcessStart()
java.io.IOException: Could not start process: <EOF>
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
        at io.github.bertramn.mongodb.test.MongoTestBase.startMongo(MongoTestBase.java:54)
        at io.github.bertramn.mongodb.test.MongoRule$3.evaluate(MongoRule.java:79)
        at io.github.bertramn.mongodb.test.MongoRuleIntegrationTest.testRuleStart(MongoRuleIntegrationTest.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
23:06:46.880 [main] INFO  d.f.e.p.runtime.AbstractProcess - construct de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@4b86805d
23:06:47.886 [main] WARN  d.f.embed.mongo.runtime.Mongod - sendShutdown localhost/127.0.0.1:27099
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at de.flapdoodle.embed.mongo.runtime.Mongod.sendShutdown(Mongod.java:87)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.sendStopToMongoInstance(AbstractMongoProcess.java:133)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:107)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:119)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
        at io.github.bertramn.mongodb.test.MongoTestBase.startMongo(MongoTestBase.java:54)
        at io.github.bertramn.mongodb.test.MongoRule$3.evaluate(MongoRule.java:79)
        at io.github.bertramn.mongodb.test.MongoRuleIntegrationTest.testRuleStart(MongoRuleIntegrationTest.java:27)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
23:06:47.988 [main] WARN  d.f.embed.mongo.AbstractMongoProcess - could not stop mongod with db command, try next
23:06:47.988 [main] WARN  d.f.embed.mongo.AbstractMongoProcess - could not stop mongod, try next
23:06:47.988 [main] WARN  d.f.embed.mongo.AbstractMongoProcess - could not stop mongod the second time, try one last thing
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.67 s <<< FAILURE! - in io.github.bertramn.mongodb.test.MongoRuleIntegrationTest
[ERROR] testRuleStart(io.github.bertramn.mongodb.test.MongoRuleIntegrationTest)  Time elapsed: 5.621 s  <<< ERROR!
java.io.IOException: Could not start process: <EOF>
        at io.github.bertramn.mongodb.test.MongoRuleIntegrationTest.testRuleStart(MongoRuleIntegrationTest.java:27)
```

**Comment by Loki-Afro** [comment]
@bertramn what RHEL version?

**Comment by bertramn** [comment]
@Loki-Afro its a stock RHEL 7.4 with 3.10.0-693.11.1.el7.x86_64 kernel

**Comment by bertramn** [comment]
I also found that the libssl dlls need to be on the path. Flapdoodle copies the extracted mongod binary to users temp folder. So dropping them in there will fix the issue on Windows (although this is not portable).

On RHEL I did not have a detailed look but installing openssl-devel seems to get over one hump but then it fails with some errors about a missing data directory in /tmp ...

**Comment by Loki-Afro** [comment]
@bertramn could you make a PR regarding the Windows issue? I'll take a look at that rhel one

**Comment by Loki-Afro** [comment]
@bertramn extracting and executing works fine on the current fedora container which is more or less RHEL 7.4+ centos 7 works also pretty fine.

**Comment by garydgregory** [comment]
Watching this issue after creating https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232 (closed a duplicate)...

**Comment by Loki-Afro** [comment]
@garydgregory could you test if the branch `windows_include_dlls` works for you?

**Comment by garydgregory** [comment]
@Loki-Afro : I posted my results and comments on https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232

**Comment by Loki-Afro** [comment]
please follow #232

**Comment by yoyoktw** [comment]
Seems there is libraries are missing.
https://indy.fulgan.com/SSL/
In my case using Win 10 64 : https://indy.fulgan.com/SSL/openssl-1.0.2s-x64_86-win64.zip
Or you may unzip and copy DLL files to System32 folder and run mongo again.

**Comment by thridevmanikanta** [comment]
This issue may also occur (as in my case) if you had an older version of MongoDB (probably the higher one) and you downgraded it to lower version. Just clear all the contents in C:/data/db (which contains configuration files of the higher version which may not be compatible with lower version) and rerun the MongoDB.

**Comment by bryancan** [comment]
I know this is an old thread, but for me it was my McAfee. I had to turn it off and delete the mongo dir in my appdata/temp
