### ISSUE TITLE
Cannot stop mongod process gracefully.

### ISSUE THREAD

**Issue by anyway1021** [flapdoodle-oss/de.flapdoodle.embed.mongo#168]
Error Message

Couldn't kill mongod process!  ---------------------------------------------------- Something bad happend. We couldn't kill mongod process, and tried a lot. If you want this problem solved you can help us if you open a new issue.  Follow this link: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues  Thank you:) ----------------------------------------------------  
Stacktrace

java.lang.IllegalStateException: Couldn't kill mongod process!
    at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:192)
    at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:76)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:189)
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:117)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170)
    at org.apache.eagle.service.alert.resource.impl.MongoImplTest.teardown(MongoImplTest.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
    at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
    at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)

Standard Output
2016-08-25 05:22:34,319 DEBUG [main] mongo.AbstractMongoProcess[106]: try to stop mongod
2016-08-25T05:22:34.320+0000 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:60603 #4 (4 connections now open)
[mongod output] 2016-08-25T05:22:34.320+0000 I COMMAND  [conn4] terminating, shutdown command received
[mongod output] 2016-08-25T05:22:34.320+0000 I FTDC     [conn4] Shutting down full-time diagnostic data capture
[mongod output] 2016-08-25T05:22:34.322+0000 I CONTROL  [conn4] now exiting
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn4] shutdown: going to close listening sockets...
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn4] closing listening socket: 5
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn4] closing listening socket: 6
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn4] removing socket file: /tmp/mongodb-27017.sock
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn4] shutdown: going to flush diaglog...
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn4] shutdown: going to close sockets...
[mongod output] 2016-08-25T05:22:34.322+0000 I STORAGE  [conn4] WiredTigerKVEngine shutting down
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn2] end connection 127.0.0.1:56142 (3 connections now open)
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn3] end connection 127.0.0.1:56455 (3 connections now open)
[mongod output] 2016-08-25T05:22:34.322+0000 I NETWORK  [conn1] end connection 127.0.0.1:56141 (3 connections now open)
[mongod output] 2016-08-25 05:22:34,422 INFO [main] runtime.ProcessControl[101]: stopOrDestroyProcess: process hasn't exited

**Comment by anyway1021** [comment]
Made a simple debug, and found in de.flapdoodle.embed.process.runtime.ProcessControl.stopOrDestroyProcess(), line 119~142, while the returnCode remains null all the way, the process should be destroyed anyway by calling implementation of Process.destroy() method. 

However, in such situation, the stopOrDestroyProcess() neither renders the destroy() state, nor does it return a value that could indicate the destroy() result, but just returns null which makes de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled() throw IllegalStateException("Couldn't kill "+runtime.getName()+" process!..............").

This may cause usage of the API tricky to handle such exception itself.

**Comment by bjornharvold** [comment]
+1

**Comment by DanielPrawdzik** [comment]
+1 
Would be a nice one to have, since it breakes our unit tests, time by time. Using 0 as port (aka random port) doesn't help aswell.

**Comment by Loki-Afro** [comment]
@DanielPrawdzik wouldn't it be nice to have a Junit Rule to make integration easier and error handling?

**Comment by Selectorrr** [comment]
+1

**Comment by FilippoGuenzi** [comment]
+1

**Comment by a8m8** [comment]
+1

**Comment by shilpauran** [comment]
its because the process takes a few seconds to shutdown. so do an await for a few seconds and then let the process stop. below is the java code for the same. keep in mind that process and executable are already created. this is just to stop the mongoDb
import static org.awaitility.Awaitility.await;
public void stopMongoDb() throws IOException {
if (process != null) {
try {
process.stop();
} catch (IllegalStateException e) {
if (process != null) {
await().atMost(1, TimeUnit.MINUTES).until(() -> !process.isProcessRunning());
} else {
throw new IllegalStateException(e);
}
}
}
if (mongodExecutable != null) {
mongodExecutable.stop();
}
}

in the above code, if the process is still running then the method isProcessRunning() returns true. we wait until it is false, or we wait until 1 min is over.

**Comment by michaelmosmann** [comment]
.. if this is still an issue, please reopen.
