### ISSUE TITLE
Release version 2.0.0 for mongodb 3.4

### ISSUE THREAD

**Issue by Loki-Afro** [flapdoodle-oss/de.flapdoodle.embed.mongo#190]
Could you please release version 2.0.0 for mongodb 3.4
after gh-185 has been merged?

Thsi is crucial because under current macOs Sierra mongodb 3.2 does not function that well - 

mongotools (like mongorestore) are build with go 1.4.2 and macOs Sierra had some breaking changes see here https://github.com/golang/go/issues/17492

The current mongotools are build with go 1.7

**Comment by Jock924491** [comment]
This is also needed to support Decimal128

**Comment by Loki-Afro** [comment]
It is released the ticket is just not closed... https://search.maven.org/#artifactdetails%7Cde.flapdoodle.embed%7Cde.flapdoodle.embed.mongo%7C2.0.0%7Cbundle

**Comment by Jock924491** [comment]
Then I need to create a defect, if you set a serializable property & set the value to Decimal128 (which became supported in 3.4) you get an error. It seems the connections are still using 3.2

`Caused by: com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.connection.SocketStream.read(SocketStream.java:88)
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:494)
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:224)
	at com.mongodb.connection.UsageTrackingInternalConnection.receiveMessage(UsageTrackingInternalConnection.java:96)
	at com.mongodb.connection.DefaultConnectionPool$PooledConnection.receiveMessage(DefaultConnectionPool.java:440)
	at com.mongodb.connection.WriteCommandProtocol.receiveMessage(WriteCommandProtocol.java:262)
	at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:104)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:67)
	at com.mongodb.connection.InsertCommandProtocol.execute(InsertCommandProtocol.java:37)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.insertCommand(DefaultServerConnection.java:118)
	at com.mongodb.operation.InsertOperation.executeCommandProtocol(InsertOperation.java:76)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:139)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:133)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60)
	at com.mongodb.Mongo.execute(Mongo.java:845)
	at com.mongodb.Mongo$2.execute(Mongo.java:828)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:342)
	at com.mongodb.DBCollection.insert(DBCollection.java:337)
	at com.mongodb.DBCollection.insert(DBCollection.java:328)
	at com.mongodb.DBCollection.insert(DBCollection.java:298)
	at com.mongodb.DBCollection.insert(DBCollection.java:264)
	at com.mongodb.DBCollection.insert(DBCollection.java:248)
	at org.springframework.data.mongodb.core.MongoTemplate$10.doInCollection(MongoTemplate.java:1074)
	at org.springframework.data.mongodb.core.MongoTemplate$10.doInCollection(MongoTemplate.java:1069)
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:478)
	... 56 more`

**Comment by Jock924491** [comment]
```
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.2.0</version>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
```

**Comment by Loki-Afro** [comment]
Create an example project and I will look into it, looks weird. Are you sure you are using the correct mongodb version?

**Comment by Jock924491** [comment]
Sure I'll throw a project together. In the mean time here are my dependencies

```
	compile('org.springframework.boot:spring-boot-starter-web')
	compile("org.springframework.boot:spring-boot-starter-data-mongodb")
	compile('org.springframework.boot:spring-boot-starter-log4j2')
	compile('com.fasterxml.jackson.dataformat:jackson-dataformat-yaml')
	compile group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.8'
	compile group: 'com.querydsl', name: 'querydsl-mongodb'
	compile group: 'com.querydsl', name: 'querydsl-sql', version: '4.1.4'
	compile group: 'org.springframework.hateoas', name: 'spring-hateoas', version: '0.23.0.RELEASE'
	compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.4'
	compile group: 'commons-io', name: 'commons-io', version: '2.5'
	compile group: 'com.jayway.jsonpath', name: 'json-path', version: '2.0.0'
	compile group: 'com.google.guava', name: 'guava', version: '21.0'
	testCompile('org.springframework.boot:spring-boot-starter-test')
	testCompile('junit:junit')
	testCompile('org.mockito:mockito-core')
	testCompile group: 'org.springframework', name: 'spring-test'
	testCompile group: "de.flapdoodle.embed", name: "de.flapdoodle.embed.mongo", version: "2.0.0"
```

**Comment by Jock924491** [comment]
Here is the project i set up to show this off: https://github.com/Jock924491/Decimal128.Testing.flapdoodle

**Comment by Loki-Afro** [comment]
you forgot to add the gradle-wrapper.jar ...

**Comment by Jock924491** [comment]
ha it's in now

**Comment by Loki-Afro** [comment]
First of all you are using Mongodb 3.2.x - lookinto your home directory and then .embedmongo - you should see some binaries and a directory with the version. This is just one way to find that out ...

Second you are using spring, espically spring boot where all things happen amgically automatically. But spring boot relies on a old mongodb version (at least for tests)

Third therefore you should debug `EmbeddedMongoAutoConfiguration`.

In `EmbeddedMongoProperties` is a version specified: 3.2.x - thats the evil part.

How to cahnge that?

Well you are lucky, I know spring :dancing_men:

Just add the following lines to your `application.yml`

```
spring:
    data:
        mongodb:
          repositories:
            enabled: true
    mongodb:
        embedded:
          version: 3.4.1
```

**Comment by Jock924491** [comment]
That absolutely did the job thanks so much!

**Comment by Loki-Afro** [comment]
'glad that i could help you ;)
