### ISSUE TITLE
Spring MongoDb Reactive with Embedded MongoDb - #block terminated with an error

### ISSUE THREAD

**Issue by Marek00Malik** [flapdoodle-oss/de.flapdoodle.embed.mongo#221]
Hi, 
Not sure if this is the correct place, but this only happens when connecting to the embedded db.

My setup 
de.flapdoodle.embed:de.flapdoodle.embed.mongo:2.0.0
cz.jirutka.spring:embedmongo-spring:1.3.1

org.springframework.boot:spring-boot-starter-data-mongodb-reactive
'org.springframework.boot' in version @2.0.0.M5

The problem is after connection, when trying to block. 
When connecting to a local MongoDb ran from docker all works well.

I have created a test branch of my little app so the example can be seen
https://github.com/Marek00Malik/recruit/tree/embbedded-mongodb-failing-test

Running the only test will result in the following error:

	org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]

	at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:87)
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.potentiallyConvertRuntimeException(ReactiveMongoTemplate.java:2197)
	at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$translateException$54(ReactiveMongoTemplate.java:2180)
	at reactor.core.publisher.Mono.lambda$onErrorMap$20(Mono.java:2368)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.MonoSingle$SingleSubscriber.onError(MonoSingle.java:140)
	at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:120)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onError(FluxFilter.java:133)
	at com.mongodb.reactivestreams.client.internal.ObservableToPublisher$1.onError(ObservableToPublisher.java:73)
	at com.mongodb.async.client.AbstractSubscription.onError(AbstractSubscription.java:123)
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:52)
	at com.mongodb.async.client.MongoIterableSubscription$1.onResult(MongoIterableSubscription.java:48)
	at com.mongodb.async.client.MappingIterable$6.onResult(MappingIterable.java:112)
	at com.mongodb.async.client.MappingIterable$6.onResult(MappingIterable.java:108)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.async.client.MongoClientImpl$2$1.onResult(MongoClientImpl.java:127)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.operation.ListCollectionsOperation$2.call(ListCollectionsOperation.java:201)
	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:499)
	at com.mongodb.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:489)
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:79)
	at com.mongodb.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:75)
	at com.mongodb.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:407)
	at com.mongodb.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:292)
	at com.mongodb.connection.BaseCluster.access$800(BaseCluster.java:55)
	at com.mongodb.connection.BaseCluster$WaitQueueHandler.run(BaseCluster.java:456)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:89)
		at reactor.core.publisher.Mono.block(Mono.java:1161)
		at com.code.house.recruit.common.nosql.repos.UserRepoTest.test1(UserRepoTest.java:37)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
		at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
		at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
		at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
		at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
		at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
		at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
		at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
		at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375)
	... 4 more

**Comment by asarkar** [comment]
The embedded Mongo support for Spring Boot doesn't work for webflux. In fact, a lot of their test framework doesn't work for webflux. You'll have to configure it yourself, like so:

In your test:
```
@SpringBootConfiguration
@ComponentScan
@EnableAutoConfiguration(exclude = {
          MongoAutoConfiguration.class,
          MongoDataAutoConfiguration.class})
public class EventRepositoryTestConfiguration {
}
```

In main:

```
@Configuration
@EnableReactiveMongoRepositories
@EnableConfigurationProperties(MongoProperties.class)
@RequiredArgsConstructor
@Slf4j
public class MongoConfiguration extends AbstractReactiveMongoConfiguration {
    private final MongoProperties mongoProperties;
    private final ConfigurableEnvironment env;

    @Override
    protected String getDatabaseName() {
        return mongoProperties.getMongoClientDatabase();
    }

    @Override
    @Bean(destroyMethod = "close")
    public MongoClient reactiveMongoClient() {
        Integer localPort = env.getProperty("local.mongo.port", Integer.class);

        if (nonNull(localPort)) {
            log.debug("Found embedded Mongo running on port: {}.", localPort);
            return MongoClients.create(String.format("mongodb://localhost:%d/%s", localPort, getDatabaseName()));
        }

        return MongoClients.create(mongoProperties.determineUri());
    }

    @Profile("embedded")
    @Configuration
    @Import({EmbeddedMongoAutoConfiguration.class})
    public static class EmbeddedMongoConfiguration {
    }
}
```

Notice that the `EmbeddedMongoConfiguration` is only activated when profile `embedded` is active; this way, you can switch between embedded and external Mongo without changing code.

**Comment by Marek00Malik** [comment]
This didn't helped, the EmbeddedMongConfig throws ' No qualifying bean of type 'org.springframework.data.mongodb.core.convert.MongoConverter''. 

Any idea why ?

**Comment by asarkar** [comment]
Please open a SO thread, GH issues is not really a place for "help me fix my code", unless you believe there is an actual issue to report.

**Comment by Loki-Afro** [comment]
@asarkar in fact even spring boot github would be a better place :)

https://github.com/spring-projects/spring-boot

**Comment by hitendrapratap** [comment]
@Marek00Malik are you able to resolve the issue? I am facing similar issue

**Comment by leccyril** [comment]
any update ? with reactive?

**Comment by michaelmosmann** [comment]
@leccyril do you have any specific question? please just open an new issue?

**Comment by leccyril** [comment]
> @leccyril do you have any specific question? please just open an new issue?

i am trying to make working this lib with Spring boot  3.0 , webflux and reactive mongo and cluster, unfortunatley i read on some thread that is not working

**Comment by michaelmosmann** [comment]
here is an canary project for all spring versions: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary .. this could be a template .. and there is an integration for reactive mongo too... so feel free to test this.

If you have any trouble, please open an issue .. any error message or stacktrace would help.
