### ISSUE TITLE
Cannot execute a gradlew task that eventually starts an embedded Mongo twice on Windows

### ISSUE THREAD

**Issue by doctorpangloss** [flapdoodle-oss/de.flapdoodle.embed.mongo#225]
Reproduction steps:

  1. Install Java 8
  2. Clone the repository at https://github.com/hiddenswitch/Spellsource-Server
  3. In Windows Powershell, run `& ".\gradlew.bat net:local`.
  4. Observe `de.flapdoodle.embed.mongo` correctly downloads and executes a `mongod`.
  5. `SIGINT` the process with `Shift+Ctrl+C`
  6. In Windows Powershell, run `& ".\gradlew.bat net:local`.
  7. Observe the following exception:

```
10:15:37.426 [main] ERROR d.f.e.p.runtime.AbstractProcess - failed to call onAfterProcessStart()
java.io.IOException: Could not start process: <EOF>
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) [de.flapdoodle.embed.mongo-e5232204c2.jar:na]
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114) ~[de.flapdoodle.embed.process-2.0.1.jar:na]
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) [de.flapdoodle.embed.mongo-e5232204c2.jar:na]
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) [de.flapdoodle.embed.mongo-e5232204c2.jar:na]
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) [de.flapdoodle.embed.mongo-e5232204c2.jar:na]
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) [de.flapdoodle.embed.mongo-e5232204c2.jar:na]
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101) [de.flapdoodle.embed.process-2.0.1.jar:na]
        at com.hiddenswitch.spellsource.util.LocalMongo.start(LocalMongo.java:66) [main/:na]
        at com.hiddenswitch.spellsource.util.Mongo.startEmbedded(Mongo.java:47) [main/:na]
        at com.hiddenswitch.spellsource.util.Mongo.connectWithEnvironment(Mongo.java:102) [main/:na]
        at com.hiddenswitch.spellsource.applications.Embedded.main(Embedded.java:22) [main/:na]
Mongo failed to start.
java.io.IOException: Could not start process: <EOF>
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79)
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114)
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
        at com.hiddenswitch.spellsource.util.LocalMongo.start(LocalMongo.java:66)
        at com.hiddenswitch.spellsource.util.Mongo.startEmbedded(Mongo.java:47)
        at com.hiddenswitch.spellsource.util.Mongo.connectWithEnvironment(Mongo.java:102)
        at com.hiddenswitch.spellsource.applications.Embedded.main(Embedded.java:22)
```

   8. Delete the `net\.mongo` directory.
   9. Observe running `& ".\gradlew.bat" net:local` despite even deleting the directory does not resolve the issue.
  10. Observe restarting the computer does not resolve the issue.
  11. Observe that an equivalent sequence of steps produces no issues on Mac or Linux.

Thoughts?

**Comment by doctorpangloss** [comment]
I also have no issues starting a Mongo 3.6 server and connecting to it, and I experience the same issue on current `master`.

**Comment by Loki-Afro** [comment]
@doctorpangloss thanks for giving so much details however I can't reproduce it an my mac machine :( I guess its running on Linux too?

**Comment by doctorpangloss** [comment]
@Loki-Afro yes, this is only an issue on Windows.

Others have reported issues with embedded Mongo on Windows and suspect it's because shutdown hooks aren't being called when the user `Ctrl+C`'s the `cmd` window running `gradle`. But other applications do not have that problem.

**Comment by doctorpangloss** [comment]
Anyone develop on Windows who'd be interested in tackling this issue?

**Comment by Loki-Afro** [comment]
maybe it is reproducible here https://www.appveyor.com/ seems like travis for windows

**Comment by bertramn** [comment]
I am able to reproduce the issue on Windows 7 with flapdoodle mongo version 2.0.1 which defaults to mongo version 3.6.0. From what I can tell is that MongoDB 3.6.x needs `libeay32.dll` and `ssleay32.dll`. Unless both are available on the PATH the error above matches what I can see. 

The flapdoodle process extracts the mongod.exe from the zip and copies it to `%TEMP%`. From mongo 3.6.0, it will also have to copy the 2 dlls to that location or probably less prone to interference, create a sub directory in `%TEMP%` and extract all 3 files to it.

So to fix it temporarily just download the win zip distro from mongo website and extract the above dlls to `%TEMP%` folder which is something like `C:\Users\fred\AppData\Local\Temp`.

**Comment by doctorpangloss** [comment]
@bertramn so you're saying this is all that's needed for a patch too?

**Comment by Loki-Afro** [comment]
@doctorpangloss @bertramn is purly mongodb 3.6 under windows related and the issue for that is here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232 don't let us start the 3. or 4. discussion here. 

meanwhile https://www.appveyor.com/ does not work in our scenario due to some restrctions...

**Comment by michaelmosmann** [comment]
.. if this is still an issue, please reopen.
