### ISSUE TITLE
MongoDB 3.6: Address already in use

### ISSUE THREAD

**Issue by livthomas** [flapdoodle-oss/de.flapdoodle.embed.mongo#230]
When I use MongoDB 3.6 in my tests, they fail because the server is not started. Here is the output:
```
[mongod output]note: noprealloc may hurt performance in many applications
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten] MongoDB starting : pid=5391 port=27017 dbpath=/tmp/embedmongo-db-2e6f6c1b-cf13-45f0-a402-41955ca76258 64-bit host=tom-PC
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten] db version v3.6.0
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten] allocator: tcmalloc
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten] modules: none
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten] build environment:
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten]     distarch: x86_64
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten]     target_arch: x86_64
[mongod output] 2018-01-19T10:41:36.989+0100 I CONTROL  [initandlisten] options: { net: { bindIp: "localhost", port: 27017 }, security: { authorization: "disabled" }, storage: { dbPath: "/tmp/embedmongo-db-2e6f6c1b-cf13-45f0-a402-41955ca76258", journal: { enabled: false }, mmapv1: { preallocDataFiles: false, smallFiles: true }, syncPeriodSecs: 0.0 } }
[mongod output] 2018-01-19T10:41:36.989+0100 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7353M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),,log=(enabled=false),
[mongod output] 2018-01-19T10:41:37.001+0100 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
[mongod output] 2018-01-19T10:41:37.001+0100 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 202ab372-5863-4009-bed3-88b79a171230
[mongod output] 2018-01-19T10:41:37.003+0100 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
[mongod output] 2018-01-19T10:41:37.005+0100 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: fd0f8431-f5b4-41bb-aeb8-df7d8a25feb6
[mongod output] 2018-01-19T10:41:37.007+0100 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/tmp/embedmongo-db-2e6f6c1b-cf13-45f0-a402-41955ca76258/diagnostic.data'
[mongod output] 2018-01-19T10:41:37.008+0100 I STORAGE  [initandlisten] exception in initAndListen std::exception: listen: Address already in use, terminating
[mongod output] 2018-01-19T10:41:37.008+0100 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
[mongod output] 2018-01-19T10:41:37.011+0100 I FTDC     [initandlisten] Shutting down full-time diagnostic data capture
[mongod output] 2018-01-19T10:41:37.011+0100 I STORAGE  [initandlisten] WiredTigerKVEngine shutting down
[mongod output] 2018-01-19T10:41:37.012+0100 I STORAGE  [initandlisten] shutdown: removing fs lock...
[mongod output] 2018-01-19T10:41:37.012+0100 I CONTROL  [initandlisten] now exiting
[mongod output] 2018-01-19T10:41:37.012+0100 I CONTROL  [initandlisten] shutting down with code:100
2018-01-19 10:41:37,022 ERROR [main] {de.flapdoodle.embed.process.runtime.AbstractProcess} failed to call onAfterProcessStart()
java.io.IOException: Could not start process: <EOF>
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) ~[de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:114) [de.flapdoodle.embed.process-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101) [de.flapdoodle.embed.process-2.0.1.jar:?]
2018-01-19 10:41:37,026 INFO  [main] {de.flapdoodle.embed.process.runtime.AbstractProcess} construct de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@2f54a33d
2018-01-19 10:41:37,027 WARN  [main] {de.flapdoodle.embed.mongo.runtime.Mongod} sendShutdown localhost/127.0.0.1:27017
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_151]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_151]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_151]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_151]
	at de.flapdoodle.embed.mongo.runtime.Mongod.sendShutdown(Mongod.java:87) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.sendStopToMongoInstance(AbstractMongoProcess.java:133) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:107) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:170) [de.flapdoodle.embed.process-2.0.1.jar:?]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:119) [de.flapdoodle.embed.process-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) [de.flapdoodle.embed.mongo-2.0.1.jar:?]
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101) [de.flapdoodle.embed.process-2.0.1.jar:?]
2018-01-19 10:41:37,128 WARN  [main] {de.flapdoodle.embed.mongo.AbstractMongoProcess} could not stop mongod with db command, try next
2018-01-19 10:41:37,128 WARN  [main] {de.flapdoodle.embed.mongo.AbstractMongoProcess} could not stop mongod, try next
2018-01-19 10:41:37,128 WARN  [main] {de.flapdoodle.embed.mongo.AbstractMongoProcess} could not stop mongod the second time, try one last thing
```
It seems like MongoDB is already running but there is no other instance running unless this library starts the server twice. When I change MongoDB version back to 3.4, everything works. Is there some problem with starting new MongoDB in this library?

I use `de.flapdoodle.embed.mongo` version **2.0.1** on Fedora 27.

**Comment by Loki-Afro** [comment]
Can you share a bit of code? I can't reproduce this on my lovely fedora machine

**Comment by livthomas** [comment]
Steps to reproduce this problem in our project:

1. Checkout [Lumeer/engine](https://github.com/Lumeer/engine) repository.
2. Run `mvn clean test -Dtest=MongoViewDaoTest -DfailIfNoTests=false` in the root folder. See that all tests pass with MongoDB 3.4.
3. Modify [EmbeddedMongoDb](https://github.com/Lumeer/engine/blob/devel/lumeer-storage/lumeer-storage-mongodb/src/test/java/io/lumeer/storage/mongodb/EmbeddedMongoDb.java#L59) to use MongoDB 3.6.
4. Run the tests again and see the failures.

Make sure no other MongoDB instance is running.

**Comment by Loki-Afro** [comment]
This relates to https://jira.mongodb.org/browse/SERVER-32631 :/ 

A Workaround since `localhost` is not working:

```
            return new MongodConfigBuilder()
                    .version(Version.Main.V3_6)
                    .net(new Net(Network.getLocalHost().getHostAddress(),
                            27017,
                            Network.localhostIsIPv6()))
                    .build();
```

`Network.getLocalHost().getHostAddress()` resolves to `127.0.0.1` and everything seems to work fine, this also fixes some weird mac OS X firewall warnings by the way.

I'll build in the next days a fix directly in this lib but I hope this helps ;)

And thanks for submitting this issue!

**Comment by Loki-Afro** [comment]
@livthomas the fix is out, also now with mongodb 3.6.2 if you can relay on SNAPSHOT versions...

**Comment by livthomas** [comment]
@Loki-Afro, thanks a lot! I have set the host address directly to `127.0.0.1`.

**Comment by maksym-shamanovskyi-axon** [comment]
@Loki-Afro your solution works local but not in remote jenkins with slowly machine

**Comment by Loki-Afro** [comment]
@maksym-shamanovskyi-axon check your `/etc/hosts` file , compare it on a machine where it works. I Once had weird mappings there for localhost, maybe this is your case too. Otherwise this sounds like a different bug?
