### ISSUE TITLE
Unable to download Mongo v3.6.6

### ISSUE THREAD

**Issue by thefridge111** [flapdoodle-oss/de.flapdoodle.embed.mongo#252]
I'm unable to get version 3.6.6 to download. Based on the stacktrace it appears that the url being used is missing characters from its url: 
```
Download de.flapdoodle.embed.mongo.distribution.Versions$GenericFeatureAwareVersion@66933e02:OS_X:B64 START
11:41:31 ERROR->runtime.Starter:main prepare executable
java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.6.6.tgz
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
	at de.flapdoodle.embed.process.runtime.Starter$prepare.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at marketplace.mongo.MongoDBServerWrapper.start(MongoDBServerWrapper.groovy:39)
```

The config/code at MongoDBServerWrapper: 

```groovy
def runtimeConfig = new RuntimeConfigBuilder().defaults(Command.MongoD).processOutput(output).build()
        def runtime = MongodStarter.getInstance(runtimeConfig)
        println "Preparing MongoDB v${version}"
        executable = runtime.prepare(mongoConfig)
```

We specify the version in Config.groovy as a string: "3.6.6". The download works up to version 3.4.15 (I didnt try 3.5). But when looking at the stacktrace it appears the url `https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.6.6.tgz` should be `https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.6.6.tgz` based on looking at the downloads [here](https://www.mongodb.org/dl/osx?_ga=2.120687880.1069094547.1526998971-844003580.1521544964&_gac=1.250655220.1523279310.Cj0KCQjwnqzWBRC_ARIsABSMVTOg8cBFPTaleAXiv042nfIr--GSjvjFI539SnqeKQsTDSuZM-ZqkegaAqsyEALw_wcB)

**Comment by Loki-Afro** [comment]
@thefridge111 nice finding and thanks for analysing this, will look into it tomorrow ;)

as a workaround .. https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-download-url

**Comment by Loki-Afro** [comment]
@thefridge111 

3.5.5 works as well, but this was just an development release
3.6.5 works too
3.6.6 is not yet released and not listed [here](https://www.mongodb.org/dl/osx?_ga=2.120687880.1069094547.1526998971-844003580.1521544964&_gac=1.250655220.1523279310.Cj0KCQjwnqzWBRC_ARIsABSMVTOg8cBFPTaleAXiv042nfIr--GSjvjFI539SnqeKQsTDSuZM-ZqkegaAqsyEALw_wcB) either

**Comment by Loki-Afro** [comment]
closing because of no response and this was not a bug either :D
