### ISSUE TITLE
port setting doesn't work

### ISSUE THREAD

**Issue by razorree** [flapdoodle-oss/de.flapdoodle.embed.mongo#259]
I set port for embeded mongo
		EmbeddedMongoFactoryBean mongo = new EmbeddedMongoFactoryBean();
		mongo.setBindIp("localhost");
		mongo.setPort(27018);

however later in the logs i can see:
Caused by: java.io.IOException: Could not start process: failed errno:10048 Only one usage of each socket address (protocol/network address/port) is normally permitted. for socket: 127.0.0.1:27017
2018-08-02T16:37:21.495+0100 E STORAGE  [initandlisten] Failed to set up sockets during startup.
2018-08-02T16:37:21.495+0100 I CONTROL  [initandlisten] dbexit:  rc: 48

	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) ~[de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116) ~[de.flapdoodle.embed.process-2.0.5.jar:na]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) ~[de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) ~[de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) ~[de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) ~[de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108) ~[de.flapdoodle.embed.process-2.0.5.jar:na]

and real MongoDB service at the end is stopped too (another issue?)

newest 2.1.1 version

**Comment by Loki-Afro** [comment]
@razorree `EmbeddedMongoFactoryBean` sounds like spring, therefore not part of this project, sorry :)

**Comment by razorree** [comment]
ok, thanks,
after looking more careful (and trying to understand everything) it looks like Spring was running another flapdoodle mongo for tests (so i had two instances, on 27018 and standard 27017)
