### ISSUE TITLE
MongoDB not shutting down with Spring Boot application

### ISSUE THREAD

**Issue by dillius** [flapdoodle-oss/de.flapdoodle.embed.mongo#262]
I found some previous references to this issue I believe, and it also seems to match a number of other errors, I'm just not sure this is the same. If it is I apologize.

After starting up my Spring Boot application once successfully, then stopping it and attempting to restart it again, I get the following:

```
java.io.IOException: Could not start process: <EOF>
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116) ~[de.flapdoodle.embed.process-2.0.5.jar:na]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108) [de.flapdoodle.embed.process-2.0.5.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1824) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1767) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) [spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:396) ~[spring-context-5.0.9.RELEASE.jar:5.0.9.RELEASE]

```

I am able to resolve this by killing any active `java.exe` processes still live on my computer.

I expect there may be a way for me to hook into the shutdown and ensure the process is being killed, but it doesn't seem like that is a normal problem. I wonder if instead this is a symptom of the issues that have been ongoing with the MongoDB failure on Windows machines due to certain DLLs?

However, mine will run fine once I have killed the outstanding process.

**Comment by Loki-Afro** [comment]
Any working complete code example? Otherwise its really difficult to find any circumstances but this is properly spring related :)

**Comment by dillius** [comment]
I don't have the full thing available as its a giant mess right now. And yes, I'm using the spring auto configuration so probably it's doing something wrong.

My configuration is:

```kotlin
@Configuration
@EnableReactiveMongoRepositories
@AutoConfigureAfter(EmbeddedMongoAutoConfiguration::class)
internal class Configuration(private val environment: Environment) : AbstractReactiveMongoConfiguration() {

    @Bean
    @DependsOn("embeddedMongoServer")
    override fun reactiveMongoClient(): MongoClient {
        val host = environment.getProperty("news.mongo.host", String::class.java)
        val port = environment.getProperty("news.mongo.port", Int::class.java) ?: 27017

        return if(host != null)
            MongoClients.create("mongodb://$host:$port")
        else MongoClients.create("mongodb://localhost:$port")
    }

    @ConditionalOnProperty("news.mongo.datadir")
    @Bean
    fun mongoConfig(): IMongodConfig {
        val port = environment.getProperty("news.mongo.port", Int::class.java) ?: 27017
        val storage = environment.getProperty("com.dillius.news.mongo.datadir", String::class.java) ?: "~/."

        val replication = Storage(storage, null, 0)

        return MongodConfigBuilder()
                //.version(Version.Main.DEVELOPMENT)
                .version(Version.Main.V3_4) //https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/232
                .net(Net(port, Network.localhostIsIPv6()))
                .replication(replication)
                .cmdOptions(MongoCmdOptionsBuilder()
                        .defaultSyncDelay()
                        .build())
                .build()
    }

    override fun getDatabaseName(): String {
        return environment.getProperty("news.mongo.db", String::class.java) ?: "news"
    }
}

```

**Comment by Loki-Afro** [comment]
@dillius I guess its somewhere in that giant mess, but at the first look it looks okay.

Maybe you could play around a bit with `storage`.
Normally 
```
java.io.IOException: Could not start process: <EOF>
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
```
comes with some clue why the server could not start up, so probably it is not killed correctly or at all ... 

But with these information: could be anything ;) - please provide a complete code example where this is reproducible

**Comment by dillius** [comment]
I'm going to close this out. I think the problem was actually in how the application was being shut down.

If anyone else runs into this issue; If you are running with Gradle from Jetbrains Intellij; do NOT run the gradle tasks to run your application. Simply run the class with the main method in it itself or use the Intellij Run Configuration for a Spring Boot application.

Running through Gradle results in an improper shut down; resources don't get closed/destroyed properly.

**Comment by Loki-Afro** [comment]
@dillius thanks for pointing this out, this could be related to some maven/gradle signal handling issues
