### ISSUE TITLE
403 on download

### ISSUE THREAD

**Issue by damianopezzotti** [flapdoodle-oss/de.flapdoodle.embed.mongo#269]
When Embed Mongo starts on MacOSX I obtain the following error:

```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-4.0.4.tgz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)
	... 58 common frames omitted

```
If I try to download from MongoDB site URL is 
https://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-4.0.4.tgz
instead of 
https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-4.0.4.tgz

**Comment by Loki-Afro** [comment]
How got your Version constrcuted?
Did you try https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/261 ?

**Comment by damianopezzotti** [comment]
> How got your Version constrcuted?
> Did you try #261 ?

spring.mongodb.embedded.version=4.0.4

**Comment by Loki-Afro** [comment]
@damianopezzotti find out how to define the version properly. Search for `GenericVersion`

**Comment by rcardin** [comment]
@damianopezzotti, have you resolved?

**Comment by alook** [comment]
When setting `spring.mongodb.embedded.version` to `4.4.4` on MacOS, the download fails:

> Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-4.4.4.tgz

It looks like a part of the URL pattern has changed from `osx`  to `macos`.

This URL works for me https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.4.4.tgz

I guess this line needs to be updated: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/c317350ad7e96205fce0135400d32c21dc6415d9/src/main/java/de/flapdoodle/embed/mongo/Paths.java#L139

**Comment by brianmarting** [comment]
Any update on this? also having the issue, but on windows and 4.2.0
```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-4.2.0.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at de.flapdoodle.embed.process.store.UrlConnectionDownloader.downloadInputStream(UrlConnectionDownloader.java:130)
	... 143 more
```

**Comment by brianmarting** [comment]
Could also be fixed by doing 
``
    @Bean
    public DownloadConfigBuilderCustomizer downloadConfigBuilderCustomizer() {
        return (downloadConfigBuilder) -> downloadConfigBuilder
                .downloadPath(distribution -> "https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-4.4.0.zip")
                .build();
    }
```

**Comment by oliverlockwood** [comment]
@codependent @alook I guess #359 (active open ticket, unlike this one) tracks the issue you are describing.

**Comment by duanjiqing** [comment]
Because the version of de.flapdoodle.embed.mongo is too low, you need to upgrade its version instead of following the Springboot version.
