### ISSUE TITLE
SocketException: Connection reset upon download distribution; How to manually setup the distribution archive location ?

### ISSUE THREAD

**Issue by OhadR** [flapdoodle-oss/de.flapdoodle.embed.mongo#278]
We use flapdoodle in our integration tests. Locally (on dev machines, Windows), it works fine; bur on Jenkins (linux) it fails from time to time, randomly. The exception is below.

```
...Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: java.net.SocketException: Connection reset
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:69)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
	at cz.jirutka.spring.embedmongo.EmbeddedMongoBuilder.build(EmbeddedMongoBuilder.java:99)
	at cz.jirutka.spring.embedmongo.EmbeddedMongoFactoryBean.getObject(EmbeddedMongoFactoryBean.java:52)
	at cz.jirutka.spring.embedmongo.EmbeddedMongoFactoryBean.getObject(EmbeddedMongoFactoryBean.java:1)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:161)
	... 213 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3444)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:87)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribution(CachingArtifactStore.java:62)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
	... 218 common frames omitted

```

How can I tell what exactly it tries to download and where from? I guess it tries to download mongo... is there a way to overcome the download, and use it from a local repo (like nexus/maven-repo)

seems like this issue is similar to [this one](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/89)...

Anyone care to relieve my of my ignorance? :)

**Comment by asgarov1** [comment]
having the same issue
