### ISSUE TITLE
mongodExecutable.start() fails on windows machine. It throws exception java.io.IOException: Cannot run program "C:\Users\XXX\AppData\Local\Temp\extract1231-345-456-2324extractmongod.exe". CreateProcess error=1260

### ISSUE THREAD

**Issue by deepakThedeveloper** [flapdoodle-oss/de.flapdoodle.embed.mongo#280]
embeded mongoD jar is trying to execute extracted mongoD.exe file in \Local\Temp of AppData. As there is some group policy applied on that folder, It won't be possible to use this directory for execution purpose.

I am looking into how to change this \Local\Temp path to other directory. Any help will be appreciated. Thanks in advance.
[ERROR] 15:03:22.245 (AbstractProcess.java:119): failed to call start()
java.io.IOException: Cannot run program "C:\Users\******\AppData\Local\Temp\extract-64d8927e-d029-4f2c-92ec-33ab0ec6e9cdextractmongod.exe": CreateProcess error=1260, This program is blocked by group policy. For more information, contact your system administrator
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_45]
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:213) ~[de.flapdoodle.embed.process-2.0.5.jar:na]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99) ~[de.flapdoodle.embed.process-2.0.5.jar:na]
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108) [de

Below version I am using.
IMongodConfig config = new MongodConfigBuilder().version(Version.V2_4_10)

**Comment by Loki-Afro** [comment]
Hi there take a look here 
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#usage---custom-mongod-filename

This isn't exactly what you want, but it gives you the hint that you should take a look into `ExtractedArtifactStoreBuilder`;)

**Comment by david0** [comment]
Would it be an option to check the group policiy on windows before extracting using java native access and fall back to another path if the group policy denies it?
If so, I could implement that and open a PR.

Some colleges have corperate PCs with this silly policies in place. I think the whole point of this is to have some mongo running without configuration related to a respective operating system.
