### ISSUE TITLE
FileNotFound in docker environment

### ISSUE THREAD

**Issue by Tobisaninfo** [flapdoodle-oss/de.flapdoodle.embed.mongo#281]
Hi,

I've some trouble with the de.flapdoodle.embed.mongo library in my Unit Tests.
My Unit Tests are written in Java 8 using the Spring-Boot Framework in version 2.0.9.RELEASE. The embbeded mongodb is the suggested version from spring (2.0.3).

The unit tests runs on a jenkins using docker. The exception I have got is 

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.io.IOException: Cannot run program "/tmp/extract-1aabfc01-694e-475b-b260-79d3c107a6d3extractmongod": error=2, No such file or directory
Caused by: java.io.IOException: Cannot run program "/tmp/extract-1aabfc01-694e-475b-b260-79d3c107a6d3extractmongod": error=2, No such file or directory
Caused by: java.io.IOException: error=2, No such file or directory
```
To use the mebedded mongodb, I have annotated my class this `@DataMongoTest`.

I already can say, that this file in the tmp directory is existing and it seams to be not empty. 
On other systems works the embedded db fine, such as on a macOS system or a debian linux server without docker. This error I've got seams to me as a problem using the embedded mongodb inside a docker container. I'll run my unit tests using maven.

Do anyone have some suggestions where the error is?
Thanks for help

**Comment by Loki-Afro** [comment]
There are several very similar closed-issues around, maybe one of them is usefull for you ;)
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/226#issuecomment-355179867
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/174 

and finally https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/220

226 is the more likely case, I GUESS this can happen if your container is based on alpine.

Anyway - unless you provide a Dockerfile where this issue is reproduce-able I can't help you very much. 

I'm running multiple docker builds and this setup works fine, at least with a openjdk:11 image ;)

**Comment by Tobisaninfo** [comment]
Thanks so fare for your help. I will check this issues you mentioned later today.

But I would like to give you some details on my docker container already. I'm using the `jenkinsci/blueocean` image, which should depend on the alpine linux. I use this image more or less in the default way without any customization.

**Comment by Loki-Afro** [comment]
I can confirm, it derives from alpine linux

```
zarathustra@hel ~ % docker run -it jenkinsci/blueocean cat /etc/issue
Welcome to Alpine Linux 3.9
Kernel \r on an \m (\l)
```

**Comment by Tobisaninfo** [comment]
I think that the issue #226 matches my problem very well. I could also see the dynamically linked libraries of the binary. But further on, I have no idea what to do.

Console output of ldd:
`bash-4.4# ldd extract-906afbda-f455-4961-9927-610c04657a4aextractmongod 
	/lib64/ld-linux-x86-64.so.2 (0x7f42891d1000)
	librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f42891d1000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f42891d1000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f428907c000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f42891d1000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f4289068000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f42891d1000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f42891d1000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f4289062000)
Error relocating extract-906afbda-f455-4961-9927-610c04657a4aextractmongod: gnu_get_libc_version: symbol not found
Error relocating extract-906afbda-f455-4961-9927-610c04657a4aextractmongod: __wcstol_internal: symbol not found
Error relocating extract-906afbda-f455-4961-9927-610c04657a4aextractmongod: __sbrk: symbol not found
Error relocating extract-906afbda-f455-4961-9927-610c04657a4aextractmongod: strtoq: symbol not found
Error relocating extract-906afbda-f455-4961-9927-610c04657a4aextractmongod: __register_atfork: symbol not found
Error relocating extract-906afbda-f455-4961-9927-610c04657a4aextractmongod: strtouq: symbol not found
Error relocating extract-906afbda-f455-4961-9927-610c04657a4aextractmongod: backtrace: symbol not found
Segmentation fault` 

To fix this issue, I already tried to install mongodb itself, gcc, ld-linux-x86-64 and gcompat. But unfortunately none of them help to to fix this issue.

Do you have any idea what to do?

**Comment by Loki-Afro** [comment]
Not sure what to do, not a huge fan of alpine linux in such cases ...

However the main difference is that alpine linux does not use glibc

search for uclibc vs glibc

**Comment by Tobisaninfo** [comment]
I'm new to alpine linux, so I haven't so much experience with it.

Unfortunately the installation of mongodb using apk did not help me. This thing with uclibc only frustrated me. Nevertheless thank for your time and help.

**Comment by Loki-Afro** [comment]
btw here for a table of differences http://www.etalabs.net/compare_libcs.html

But I'll try it out today, can't promise anything though

**Comment by Loki-Afro** [comment]
Got it to work

**This is not production ready!**
Add to your Dockerfile something like this.
It basically installs glibc, more info here https://github.com/sgerrand/alpine-pkg-glibc
```
RUN apk --no-cache add ca-certificates
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub

RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-bin-2.29-r0.apk

RUN apk add glibc-2.29-r0.apk glibc-bin-2.29-r0.apk
```
If you run into any other issues, see the link above, you may need to generate the locales as well.

As a proof:

```
% docker run -it --rm alpine:latest sh
/ # cd root/
~ # wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.0.9.tgz
Connecting to fastdl.mongodb.org (143.204.214.92:443)
mongodb-linux-x86_64 100% |*******************************************************************************************************************************************************************| 81.0M  0:00:00 ETA
~ # apk --no-cache add ca-certificates
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20190108-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 6 MiB in 15 packages
~ # wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
~ # wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk
Connecting to github.com (140.82.118.4:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.171.67:443)
glibc-2.29-r0.apk    100% |*******************************************************************************************************************************************************************| 2006k  0:00:00 ETA
~ # wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-bin-2.29-r0.apk
Connecting to github.com (140.82.118.4:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.144.51:443)
glibc-bin-2.29-r0.ap 100% |*******************************************************************************************************************************************************************|  963k  0:00:00 ETA
~ # apk add glibc-2.29-r0.apk glibc-bin-2.29-r0.apk
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/3) Installing glibc (2.29-r0)
(2/3) Installing libgcc (8.3.0-r0)
(3/3) Installing glibc-bin (2.29-r0)
Executing glibc-bin-2.29-r0.trigger
OK: 13 MiB in 18 packages
~ # tar -xzf mongodb-linux-x86_64-4.0.9.tgz
~ # mkdir -p /data/db
~ # ./mongodb-linux-x86_64-4.0.9/bin/mongod
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten] MongoDB starting : pid=31 port=27017 dbpath=/data/db 64-bit host=bb060c5afa6f
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten] db version v4.0.9
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten] git version: fc525e2d9b0e4bceff5c2201457e564362909765
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten] modules: none
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten] build environment:
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten]     distarch: x86_64
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2019-04-20T09:39:32.938+0000 I CONTROL  [initandlisten] options: {}
2019-04-20T09:39:32.939+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=15544M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2019-04-20T09:39:33.455+0000 I STORAGE  [initandlisten] WiredTiger message [1555753173:455540][31:0x7f9e1c7bfa40], txn-recover: Set global recovery timestamp: 0
2019-04-20T09:39:33.464+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten]
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten]
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server.
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2019-04-20T09:39:33.479+0000 I CONTROL  [initandlisten]
2019-04-20T09:39:33.480+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: aff5b4da-045b-4a07-919c-14e52c1e67e4
2019-04-20T09:39:33.494+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.0
2019-04-20T09:39:33.514+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: ae23ed7b-06fd-4e00-9c35-bbc4a70fb0e4
2019-04-20T09:39:33.529+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2019-04-20T09:39:33.529+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
2019-04-20T09:39:33.529+0000 I STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with generated UUID: fc2afe72-3871-47e2-bba4-cce64b165e67
2019-04-20T09:39:33.559+0000 I INDEX    [LogicalSessionCacheRefresh] build index on: config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 }
2019-04-20T09:39:33.559+0000 I INDEX    [LogicalSessionCacheRefresh]     building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2019-04-20T09:39:33.562+0000 I INDEX    [LogicalSessionCacheRefresh] build index done.  scanned 0 total records. 0 secs
^C2019-04-20T09:39:36.429+0000 I CONTROL  [signalProcessingThread] got signal 2 (Interrupt), will terminate after current cmd ends
2019-04-20T09:39:36.429+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2019-04-20T09:39:36.429+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2019-04-20T09:39:36.430+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2019-04-20T09:39:36.434+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2019-04-20T09:39:36.438+0000 I STORAGE  [signalProcessingThread] Shutting down session sweeper thread
2019-04-20T09:39:36.438+0000 I STORAGE  [signalProcessingThread] Finished shutting down session sweeper thread
2019-04-20T09:39:36.686+0000 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2019-04-20T09:39:36.686+0000 I CONTROL  [signalProcessingThread] now exiting
2019-04-20T09:39:36.686+0000 I CONTROL  [signalProcessingThread] shutting down with code:0
~ # cat /etc/issue 
Welcome to Alpine Linux 3.9
Kernel \r on an \m (\l)

```

**Comment by Tobisaninfo** [comment]
I installed everything as you described above without any installation errors. But my unit tests still failed with some the same error. In addition I found some maybe helpful prints from the maven run.

```
2019-04-20 10:10:03.622  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : starting...
2019-04-20 10:10:04.439  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : DownloadSize: 56475924
2019-04-20 10:10:04.530  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 0 %
2019-04-20 10:10:05.460  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 10 %
2019-04-20 10:10:06.048  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 20 %
2019-04-20 10:10:06.679  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 30 %
2019-04-20 10:10:07.243  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 40 %
2019-04-20 10:10:07.858  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 50 %
2019-04-20 10:10:08.404  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 60 %
2019-04-20 10:10:08.965  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 70 %
2019-04-20 10:10:09.560  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 80 %
2019-04-20 10:10:10.126  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 90 %
2019-04-20 10:10:10.716  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 100 %
2019-04-20 10:10:10.768  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : downloaded with 9192kb/s
2019-04-20 10:10:10.895  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : finished
2019-04-20 10:10:11.080  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : starting...
2019-04-20 10:10:12.125  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : extract mongodb-linux-x86_64-3.2.2/bin/mongod
2019-04-20 10:10:12.209  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : nothing left
2019-04-20 10:10:12.295  INFO 2494 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : finished
2019-04-20 10:10:12.911 ERROR 2494 --- [      Thread-18] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-2e9ddebe-d9fb-4392-a19e-ad962270669eextractmongod: /usr/lib/libstdc++.so.6: no version information available (required by /tmp/extract-2e9ddebe-d9fb-4392-a19e-ad962270669eextractmongod)
2019-04-20 10:10:13.036 ERROR 2494 --- [      Thread-18] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-2e9ddebe-d9fb-4392-a19e-ad962270669eextractmongod: /usr/lib/libstdc++.so.6: no version information available (required by /tmp/extract-2e9ddebe-d9fb-4392-a19e-ad962270669eextractmongod)
2019-04-20 10:10:13.169 ERROR 2494 --- [      Thread-18] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-2e9ddebe-d9fb-4392-a19e-ad962270669eextractmongod: /usr/lib/libstdc++.so.6: no version information available (required by /tmp/extract-2e9ddebe-d9fb-4392-a19e-ad962270669eextractmongod)
2019-04-20 10:10:12.912  INFO 2494 --- [      Thread-17] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-04-20T10:10:12.858+0000 F CONTROL  [main] Failed global initialization: BadValue: Invalid or no user locale set. Please ensure LANG and/or LC_* environment variables are set correctly.
2019-04-20 10:10:13.576 ERROR 2494 --- [           main] d.f.e.process.runtime.AbstractProcess    : failed to call onAfterProcessStart()
```

**Comment by Loki-Afro** [comment]
```
2019-04-20 10:10:12.912  INFO 2494 --- [      Thread-17] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-04-20T10:10:12.858+0000 F CONTROL  [main] Failed global initialization: BadValue: Invalid or no user locale set. Please ensure LANG and/or LC_* environment variables are set correctly.
```

basically says it wants the locale to be set

I did my test on the most recent mongodb version (4.0.9), 3.2.x is very old ... - but I can look into that if you need this version to work, shouldn't be much of a difference I think

**Comment by Tobisaninfo** [comment]
I didn't select this version myself. Spring Boot uses your library in version 2.0.3. But if you want, I could try to override this to your current library version. The downloaded database version I think, I can't change myself.

Is this locale thing the Java Locale one or any other ?

**Comment by Loki-Afro** [comment]
You can change the locale like this https://github.com/sgerrand/alpine-pkg-glibc#locales

Regarding the mongodb version
I don't know whats currently the embedded mongo lib in spring boot but 2.2.0 is desired. - in any way since you are using spring boot - you have to overwrite something and change some bean definitions - there is also an optional configuration property as far as I know ...

**Comment by Tobisaninfo** [comment]
I set the locale using the following command (TO make things easy, I used US instead of DE for the locale settings)

``` bash
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-i18n-2.29-r0.apk
apk add glibc-bin-2.29-r0.apk glibc-i18n-2.29-r0.apk
/usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
```

I also update the library from 2.0.3 up to 2.2.0. But it still not works in my docker container :( The exception seams to be the same as before

```
2019-04-20 13:52:24.816  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : starting...
2019-04-20 13:52:25.510  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : DownloadSize: 56475924
2019-04-20 13:52:25.598  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 0 %
2019-04-20 13:52:26.302  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 10 %
2019-04-20 13:52:26.917  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 20 %
2019-04-20 13:52:27.715  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 30 %
2019-04-20 13:52:28.356  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 40 %
2019-04-20 13:52:28.954  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 50 %
2019-04-20 13:52:29.815  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 60 %
2019-04-20 13:52:30.556  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 70 %
2019-04-20 13:52:31.325  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 80 %
2019-04-20 13:52:32.025  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 90 %
2019-04-20 13:52:32.740  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : 100 %
2019-04-20 13:52:32.788  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : downloaded with 7878kb/s
2019-04-20 13:52:32.902  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download 3.2.2:Linux:B64 : finished
2019-04-20 13:52:33.089  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : starting...
2019-04-20 13:52:34.152  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : extract mongodb-linux-x86_64-3.2.2/bin/mongod
2019-04-20 13:52:34.307  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : nothing left
2019-04-20 13:52:34.385  INFO 9680 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-3.2.2.tgz : finished
2019-04-20 13:52:34.846 ERROR 9680 --- [      Thread-18] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-0d469724-2c27-4fe8-9fba-0456270c6359extractmongod: /usr/lib/libstdc++.so.6: no version information available (required by /tmp/extract-0d469724-2c27-4fe8-9fba-0456270c6359extractmongod)
2019-04-20 13:52:34.856  INFO 9680 --- [      Thread-17] o.s.b.a.mongo.embedded.EmbeddedMongo     : 2019-04-20T13:52:34.855+0000 F CONTROL  [main] Failed global initialization: BadValue: Invalid or no user locale set. Please ensure LANG and/or LC_* environment variables are set correctly.
2019-04-20 13:52:34.991 ERROR 9680 --- [      Thread-18] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-0d469724-2c27-4fe8-9fba-0456270c6359extractmongod: /usr/lib/libstdc++.so.6: no version information available (required by /tmp/extract-0d469724-2c27-4fe8-9fba-0456270c6359extractmongod)
2019-04-20 13:52:35.353 ERROR 9680 --- [           main] d.f.e.process.runtime.AbstractProcess    : failed to call onAfterProcessStart()

java.io.IOException: Could not start process: <EOF>
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) [de.flapdoodle.embed.mongo-2.2.0.jar:na]
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116) ~[de.flapdoodle.embed.process-2.1.2.jar:na]
```

**Comment by Loki-Afro** [comment]
you can define the actual mongodb version via `spring.mongodb.embedded.version` but please use the version `2.2.0` to avoid any other havoc - and I guess you have to reconfigure that default spring boot magic then.

But in any way - I can verify the process described in my previous comment also works for **3.2.22**

But it does not work for **3.2.2**, great :D

**Comment by Tobisaninfo** [comment]
I can finally report that my unit tests running fine 😀 

For documentation reasons, here are my steps I have done to achieve that.

1. First I defined some env variables in the docker compose file:
```
    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
```

2. Second in the alpine docker container I run these following commands:

```
apk --no-cache add ca-certificates
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub

wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-bin-2.29-r0.apk

apk add glibc-2.29-r0.apk glibc-bin-2.29-r0.apk

wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-i18n-2.29-r0.apk
apk add glibc-bin-2.29-r0.apk glibc-i18n-2.29-r0.apk
/usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
```

3. Update the versions in my project, setting these to the following:

```
de.flapdoodle.embed.mongo=2.2.0 (maven)
spring.mongodb.embedded.version=3.2.22 (application.properties)
```

Thank you for the great help over easter.

**Comment by Loki-Afro** [comment]
thanks for documenting, enjoy your holidays too  🍺
