### ISSUE TITLE
Windows, Artifact Caching improper

### ISSUE THREAD

**Issue by EmteeW** [flapdoodle-oss/de.flapdoodle.embed.mongo#285]
On a Windows 10 machine, with the 2.2.0 release, we are trying to use V3_4 (Main) which successfully downloads:

"mongodb-win32-x86_64-3.4.15.zip"

It also successfully extracts, and invokes Mongod.exe.  But subsequent calls to "prepare(...)"--even on separate runs--will fail a cache hit, and then the downloader will attempt to invoke a bogus URL:
```
Caused by: java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-V3_4.zip
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribution(CachingArtifactStore.java:62)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	... 79 common frames omitted
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-V3_4.zip
```

I have spent hours combing over the source code of both embed-mongo and embed-process, to try to see where **.toString()** or **.name()** is invoked either explicitly or implicitly, on the Version (the enum instance) that would produce this behavior, but I cannot find it for the life of me.  Mostly I see **asInDownload()** which is as it should be.

I'm sorry I couldn't be more helpful.  I don't have a lot of insight into this codebase which does have its fair share of indirection.

**Comment by EmteeW** [comment]
Actually, I was viewing Master.  I was unable to build master, because it said repositories are offline...

I really suspect this has been fixed in Master, as a lot of the relevant file have been modified since then.  Both the embed-mongo and embed-process have had a long time since a release!

**Comment by EmteeW** [comment]
Sry, it in fact the issue is with https://github.com/jirutka/embedmongo-spring

I didn't notice that our developers, in addition to using flapdoodle mongo directly, had also tried to use the bean, and left both in.
