### ISSUE TITLE
java.io.IOException: Could not open inputStream

### ISSUE THREAD

**Issue by derekzhan** [flapdoodle-oss/de.flapdoodle.embed.mongo#305]
```java
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: prepare executable
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:64)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:45)
	at example.springdata.mongodb.util.MongosSystemForTestFactory.initializeReplicaSet(MongosSystemForTestFactory.java:111)
	at example.springdata.mongodb.util.MongosSystemForTestFactory.start(MongosSystemForTestFactory.java:82)
	at example.springdata.mongodb.util.EmbeddedMongo$ReplSet.doStart(EmbeddedMongo.java:321)
	... 11 more
Caused by: java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	... 15 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://downloads.mongodb.org/win32/mongodb-win32-x86_64-ssl-3.7.9.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)
	... 19 more

**Comment by derekzhan** [comment]
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/261
