### ISSUE TITLE
Cannot run on remote build server when tmp directory is non-executable

### ISSUE THREAD

**Issue by apiwoni** [flapdoodle-oss/de.flapdoodle.embed.mongo#308]
Provide ability to inherit parent process environment

Looking at de.flapdoodle.embed.process.runtime.AbstractProcess#getEnvironment the environment ends up being null so there is no way to set java.io.tempdir for execution in more controlled environments. Ideally, process environment should be inherited from parent process.

where -Djava.io.tmpdir=/data1/tmp
```
java.io.IOException: Cannot run program "/tmp/extract-3fd4c0fb-75ed-4be0-a5f2-81c5a30db637extractmongod": error=13, Permission denied
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
  at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:213)
  at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
  at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
  at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
  at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
  at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
  at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
  at com.github.simplyscala.MongoEmbedDatabase$class.mongoStart(MongoEmbedDatabase.scala:26)
  at com.marketo.mongo.MultitenantMongoDaoSpec.mongoStart(MultitenantMongoDaoSpec.scala:19)
  ...
  Cause: java.io.IOException: error=13, Permission denied
  at java.lang.UNIXProcess.forkAndExec(Native Method)
  at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
  at java.lang.ProcessImpl.start(ProcessImpl.java:134)
  at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
  at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:213)
  at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
  at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
  at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
  at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
  at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
```

**Comment by apiwoni** [comment]
Basically, it does not seem to be possible to run test cases on remote build system where tmp directory is not executable for security reasons.

**Comment by apiwoni** [comment]
Closing this issue. It seems this can be handled by passing command line args which are propagated to forked Maven test as -DargLine="-Djava.io.tmpdir=/my/tmp"
