### ISSUE TITLE
problem with download distribution with ubuntu-12.04

### ISSUE THREAD

**Issue by sidarth164** [flapdoodle-oss/de.flapdoodle.embed.mongo#319]
Hi, I got the following embedded mongo download distribution error while trying to build my spring project on Circle CI
The build is happening on a linux ubuntu-12.04, and I'm trying to run mongodb 4.2.5 version for my tests
These are the error logs:
`Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/linux/mongodb-macos-x86_64-4.2.5.tgz
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)
	... 146 more
`
As you can see the tar download link is non-sensical: `https://fastdl.mongodb.org/linux/mongodb-macos-x86_64-4.2.5.tgz`

Thank you in advance for the help :)

**Comment by sidarth164** [comment]
Sorry it was an error on my part
I was hardcoding mongodb-macos into my Paths class object.
Closing this issue.
