### ISSUE TITLE
Emebeded Mongo on macOS Big Sur

### ISSUE THREAD

**Issue by lfdp** [flapdoodle-oss/de.flapdoodle.embed.mongo#329]
I am trying to run EmbeddedMongo on macOS Big Sur / AppleSilicon. Unfortunately the following issue pop up
failure message="java.lang.IllegalArgumentException: this version does not support 32Bit: PRODUCTION:OS_X:B32" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: this version does not support 32Bit: PRODUCTION:OS_X:B32
        at de.flapdoodle.embed.mongo.Paths.getBitSize(Paths.java:157)
        at de.flapdoodle.embed.mongo.Paths.getPath(Paths.java:97)
        at de.flapdoodle.embed.process.store.LocalArtifactStore.getArtifact(LocalArtifactStore.java:71)
        at de.flapdoodle.embed.process.store.LocalArtifactStore.checkArtifact(LocalArtifactStore.java:38)
        at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:65)
        at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
        at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:45)
        at eu.toyota.connected.ecare.sink.EmbeddedMongoDb.start(EmbeddedMongoDb.kt:41)

**Comment by antongalaev** [comment]
Having the same problem on m1 Mac using Azul zulu64-11.0.9.1 JDK, which is aarch64. Other x64 intel JDK works fine.
```
Caused by: java.lang.IllegalArgumentException: this version does not support 32Bit: Version{3.5.5}:OS_X:B32
	at de.flapdoodle.embed.mongo.Paths.getBitSize(Paths.java:157)
	at de.flapdoodle.embed.mongo.Paths.getPath(Paths.java:97)
	at de.flapdoodle.embed.process.store.LocalArtifactStore.getArtifact(LocalArtifactStore.java:71)
	at de.flapdoodle.embed.process.store.LocalArtifactStore.checkArtifact(LocalArtifactStore.java:38)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:65)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:45)
```

**Comment by kurly09** [comment]
Same here. 
```
Caused by: java.lang.IllegalArgumentException: this version does not support 32Bit: Version{3.5.5}:OS_X:B32
	at de.flapdoodle.embed.mongo.Paths.getBitSize(Paths.java:157)
	at de.flapdoodle.embed.mongo.Paths.getPath(Paths.java:97)
	at de.flapdoodle.embed.process.store.LocalArtifactStore.getArtifact(LocalArtifactStore.java:71)
	at de.flapdoodle.embed.process.store.LocalArtifactStore.checkArtifact(LocalArtifactStore.java:38)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:65)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:45)
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoServer(EmbeddedMongoAutoConfiguration.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 194 more
```

**Comment by antongalaev** [comment]
upd: actually it works with the latest 3.0.0 version
