### ISSUE TITLE
Embedded MongoDB does not start on macOS since v3.1.3

### ISSUE THREAD

**Issue by jmesny** [flapdoodle-oss/de.flapdoodle.embed.mongo#352]
Hi.

Since version 3.1.3, our application fails to start using Embedded MongoDB on macOS.

The problem is easily reproducible with the first example available in the [README.md](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/README.md#usage) file.

Here is the stacktrace:
```
java.lang.IllegalArgumentException: no match out of [X86_64, X86_32, ARM_64, ARM_32]

	at de.flapdoodle.os.common.PeculiarityInspector.match(PeculiarityInspector.java:51)
	at de.flapdoodle.os.Platform.detectArchitecture(Platform.java:71)
	at de.flapdoodle.os.Platform.detect(Platform.java:46)
	at de.flapdoodle.os.Platform.detect(Platform.java:40)
	at de.flapdoodle.embed.process.distribution.Distribution.detectFor(Distribution.java:48)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
```
Is there anything else I can provide to help you?

Thanks a lot for this great tool 🙏

**Comment by michaelmosmann** [comment]
Did a new release .. can you try if this works now?

**Comment by jmesny** [comment]
It works! Thanks a lot 🙏

**Comment by jonatan-ivanov** [comment]
@pierrcou I think it was failing before fixing this `X86_64` is not supported either; now `x86_64` is supported but it is not the same (capital `X`).

@michaelmosmann What do you think about doing `[xX]` in the regexp?
