### ISSUE TITLE
`MongoSocketWriteException` when executing multiple consecutive tests

### ISSUE THREAD

**Issue by gscaparrotti** [flapdoodle-oss/de.flapdoodle.embed.mongo#354]
I'm experiencing an issue with Embedded MongoDB: I have a test class containing many test methods, each one starting a new instance of Embedded MongoDB, stopping the already running one if present. 

When I run each test individually everything works fine, but when I launch all the methods in the test class in batch only the first one works, while the others fail with the following exception:

```
com.mongodb.MongoSocketWriteException: Exception sending message
	at com.mongodb.internal.connection.InternalStreamConnection.translateWriteException(InternalStreamConnection.java:618) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.access$1200(InternalStreamConnection.java:78) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection$3.failed(InternalStreamConnection.java:541) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.AsynchronousChannelStream$1.failed(AsynchronousChannelStream.java:100) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.AsynchronousChannelStream$2.failed(AsynchronousChannelStream.java:203) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.AsynchronousChannelStream$AsyncWritableByteChannelAdapter$WriteCompletionHandler.failed(AsynchronousChannelStream.java:228) ~[mongodb-driver-core-4.2.3.jar:?]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
	at sun.nio.ch.Invoker$2.run(Invoker.java:219) ~[?:?]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.io.IOException: Connessione in corso interrotta forzatamente dall'host remoto
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.write0(Native Method) ~[?:?]
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$WriteTask.run(WindowsAsynchronousSocketChannelImpl.java:776) ~[?:?]
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl.implWrite(WindowsAsynchronousSocketChannelImpl.java:912) ~[?:?]
	at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:383) ~[?:?]
	at sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:400) ~[?:?]
	at java.nio.channels.AsynchronousSocketChannel.write(AsynchronousSocketChannel.java:582) ~[?:?]
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$AsynchronousSocketChannelAdapter.write(AsynchronousSocketChannelStream.java:177) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.AsynchronousChannelStream$AsyncWritableByteChannelAdapter.write(AsynchronousChannelStream.java:210) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.AsynchronousChannelStream.pipeOneBuffer(AsynchronousChannelStream.java:191) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.AsynchronousChannelStream.writeAsync(AsynchronousChannelStream.java:88) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.writeAsync(InternalStreamConnection.java:532) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendMessageAsync(InternalStreamConnection.java:528) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendCommandMessageAsync(InternalStreamConnection.java:428) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceiveAsync(InternalStreamConnection.java:397) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceiveAsync(UsageTrackingInternalConnection.java:145) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceiveAsync(DefaultConnectionPool.java:527) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.executeAsync(CommandProtocolImpl.java:77) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.executeAsync(DefaultServer.java:271) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocolAsync(DefaultServerConnection.java:218) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.commandAsync(DefaultServerConnection.java:135) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.commandAsync(DefaultServerConnection.java:126) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommandAsyncWithConnection(CommandOperationHelper.java:453) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.FindOperation$2.call(FindOperation.java:701) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.OperationHelper$9.onResult(OperationHelper.java:734) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.OperationHelper$9.onResult(OperationHelper.java:731) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:120) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:109) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool.openAsync(DefaultConnectionPool.java:204) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool.getAsync(DefaultConnectionPool.java:154) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.DefaultServer.getConnectionAsync(DefaultServer.java:109) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding$AsyncClusterBindingConnectionSource.getConnection(AsyncClusterBinding.java:134) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withAsyncConnectionSource(OperationHelper.java:731) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.OperationHelper.access$200(OperationHelper.java:69) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:751) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.OperationHelper$AsyncCallableWithConnectionAndSourceCallback.onResult(OperationHelper.java:739) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:48) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:106) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding$1.onResult(AsyncClusterBinding.java:100) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:438) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:302) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.BaseCluster.selectServerAsync(BaseCluster.java:155) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.SingleServerCluster.selectServerAsync(SingleServerCluster.java:41) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding.getAsyncClusterBindingConnectionSource(AsyncClusterBinding.java:100) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.binding.AsyncClusterBinding.getReadConnectionSource(AsyncClusterBinding.java:85) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withAsyncReadConnection(OperationHelper.java:678) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.operation.FindOperation.executeAsync(FindOperation.java:691) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$3(OperationExecutorImpl.java:69) ~[mongodb-driver-reactivestreams-4.2.3.jar:?]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1643) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3873) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:75) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:129) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at com.mongodb.reactivestreams.client.internal.ClientSessionHelper.lambda$createClientSessionMono$2(ClientSessionHelper.java:67) ~[mongodb-driver-reactivestreams-4.2.3.jar:?]
	at com.mongodb.internal.connection.BaseCluster$ServerSelectionRequest.onResult(BaseCluster.java:438) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.BaseCluster.handleServerSelectionRequest(BaseCluster.java:302) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.BaseCluster.selectServerAsync(BaseCluster.java:155) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.internal.connection.SingleServerCluster.selectServerAsync(SingleServerCluster.java:41) ~[mongodb-driver-core-4.2.3.jar:?]
	at com.mongodb.reactivestreams.client.internal.ClientSessionHelper.lambda$createClientSessionMono$3(ClientSessionHelper.java:62) ~[mongodb-driver-reactivestreams-4.2.3.jar:?]
	at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3873) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:3979) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3867) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3834) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3806) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$1(BatchCursorFlux.java:48) ~[mongodb-driver-reactivestreams-4.2.3.jar:?]
	at reactor.core.publisher.FluxCreate$BaseSink.onRequest(FluxCreate.java:535) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.onRequest(FluxCreate.java:263) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$2(BatchCursorFlux.java:44) ~[mongodb-driver-reactivestreams-4.2.3.jar:?]
	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:7967) ~[reactor-core-3.2.22.RELEASE.jar:3.2.22.RELEASE]
	at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.subscribe(BatchCursorFlux.java:68) ~[mongodb-driver-reactivestreams-4.2.3.jar:?]
	at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.subscribe(BatchCursorPublisher.java:115) ~[mongodb-driver-reactivestreams-4.2.3.jar:?]
	at com.engynya.framework.mongo.subscribers.ObservableSubscriber.<init>(ObservableSubscriber.java:70) ~[mongodb-1.0.0.jar:?]
	at com.engynya.framework.mongo.subscribers.ObservableSubscriber.get(ObservableSubscriber.java:47) ~[mongodb-1.0.0.jar:?]
	at com.engynya.trion.businesslogic.MongoMapManager.getMaps(MongoMapManager.java:48) ~[classes/:?]
	at com.engynya.trion.core.shared.TrionEnvironment.createEnvironment(TrionEnvironment.java:102) ~[classes/:?]
	at test.engynya.autoId.AutoIDTest.palletSearchTest(AutoIDTest.java:52) ~[test-classes/:?]
	[JUnit frames...]
```

I wonder if there is some issue with the stop of any previous instance of Embedded MongoDB (I already call `waitFor()` after calling `stop()` and I set the `stopTimeout` to 0). 

The issue disappears if I insert a long enough `Thread.sleep()` after calling `stop()`, but this is clearly an ugly workaround rather than a solution.

**Comment by michaelmosmann** [comment]
.. ah. hmm.. maybe there is an issue without timeout. I expect that the port is not free when mongod stops so the new instance may fail.. or something like this.. maybe i can add an test to see if i can reproduce this problem.. and then fix it.

**Comment by michaelmosmann** [comment]
@gscaparrotti is this still an issue? please reopen if needed.
