### ISSUE TITLE
Oracle Linux

### ISSUE THREAD

**Issue by eladeyal-intel** [flapdoodle-oss/de.flapdoodle.embed.mongo#364]
Here is /etc/os-release

```
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5
```

which is supposedly "like fedora"

with spring boot 2.6.2 + embedmongo 3.2.6 I get 

```
because there is no package for Version{5.0.2}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{5.0.2}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
22-01-09 Sun 15:09:59.343 ERROR 165 --- [     Thread-260] EmbeddedMongo @ log : /tmp/extract-5cd7b12b-0fb9-4ecf-9dee-dfea6e4ed9f9extractmongod: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/extract-5cd7b12b-0fb9-4ecf-9dee-dfea6e4ed9f9extractmongod)
22-01-09 Sun 15:09:59.343 ERROR 165 --- [     Thread-260] EmbeddedMongo @ log : /tmp/extract-5cd7b12b-0fb9-4ecf-9dee-dfea6e4ed9f9extractmongod: /lib64/libcurl.so.4: no version information available (required by /tmp/extract-5cd7b12b-0fb9-4ecf-9dee-dfea6e4ed9f9extractmongod)
```

**Comment by michaelmosmann** [comment]
@eladeyal-intel which mongodb package works for you? as there is no fedora or oracle dist package, only redhat/centos.

**Comment by eladeyal-intel** [comment]
https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel80-5.0.4.tgz seems to work @michaelmosmann

**Comment by michaelmosmann** [comment]
@eladeyal-intel  .. ok.. then i try to use the redhat version for oracle linux ..

**Comment by eladeyal-intel** [comment]
@michaelmosmann thanks so much for addressing this 


I still get `linux distribution not supported` with 3.2.8 after adding `<version>3.2.8</version> to pom.xml - :

```
LinuxPackageFinder @ lambda$rules$0 : because there is no package for GenericFeatureAwareVersion{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Oracle, version=Oracle_8} we fall back to GenericFeatureAwareVersion{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Oracle, version=Ubuntu_20_04}

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterManagementController' defined in class path resource [spring-context.xml]: Cannot resolve reference to bean 'clusterManagementService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterManagementService' defined in class path resource [spring-context.xml]: Cannot resolve reference to bean 'clusterRepository' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusterRepository' defined in com.lightbits.remote.repository.ClusterRepository defined in @EnableMongoRepositories declared on SpringBootApplication: Cannot resolve reference to bean 'mongoTemplate' while setting bean property 'mongoOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is java.lang.IllegalArgumentException: linux distribution not supported: GenericFeatureAwareVersion{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Oracle, version=Oracle_8}(with fallback to GenericFeatureAwareVersion{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Oracle, version=Ubuntu_20_04})
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.14.jar:5.3.14]
	... 129 common frames omitted
Caused by: java.lang.IllegalArgumentException: linux distribution not supported: GenericFeatureAwareVersion{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Oracle, version=Oracle_8}(with fallback to GenericFeatureAwareVersion{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Oracle, version=Ubuntu_20_04})
	at de.flapdoodle.embed.mongo.packageresolver.linux.LinuxPackageFinder.lambda$rules$0(LinuxPackageFinder.java:184) ~[de.flapdoodle.embed.mongo-3.2.8.jar:na]
	at de.flapdoodle.embed.mongo.packageresolver.PlatformMatchRules.packageFor(PlatformMatchRules.java:43) ~[de.flapdoodle.embed.mongo-3.2.8.jar:na]
	at de.flapdoodle.embed.mongo.packageresolver.linux.LinuxPackageFinder.packageFor(LinuxPackageFinder.java:54) ~[de.flapdoodle.embed.mongo-3.2.8.jar:na]
	at de.flapdoodle.embed.mongo.packageresolver.PlatformMatchRules.packageFor(PlatformMatchRules.java:43) ~[de.flapdoodle.embed.mongo-3.2.8.jar:na]
	at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.packageFor(PlatformPackageResolver.java:62) ~[de.flapdoodle.embed.mongo-3.2.8.jar:na]
```

**Comment by michaelmosmann** [comment]
@eladeyal-intel .. ah, found the bug.. will fix it.

**Comment by michaelmosmann** [comment]
.. hmm.. mongodb 5.0.2 is the last supported with embedmongo 3.2.8 .. so 5.0.2 should work, support for 5.0.4 (5.0.5) has to be implemented.. (in progress)

**Comment by eladeyal-intel** [comment]
@michaelmosmann I can confirm 5.0.2 works for me now. thanks a lot!

**Comment by michaelmosmann** [comment]
@eladeyal-intel did a new release (3.3.0) and 5.0.5. support is enabled..
