### ISSUE TITLE
Cannot run several JUnit4 style tests

### ISSUE THREAD

**Issue by ghost** [flapdoodle-oss/de.flapdoodle.embed.mongo#37]
Using v1.27 along with JUnit 4.0 style with annotations.

Code for Before and After methods:

```
private MongodProcess _mongod;
private Mongo _mongo;
private DB db;
```

@Before

```
public void setUp() throws Exception {
    int port = 12345;
    _mongod = null;
    MongodConfig mongodConfig = new MongodConfig(Version.Main.V2_3, port,Network.localhostIsIPv6());
    RuntimeConfig runtimeConfig=new RuntimeConfig();
    runtimeConfig.setExecutableNaming(new UserTempNaming());
    MongodStarter runtime = MongodStarter.getInstance(runtimeConfig);
    MongodExecutable mongodExecutable = runtime.prepare(mongodConfig);
    _mongod = mongodExecutable.start();
    _mongo = new Mongo("localhost", port);
    db = _mongo.getDB("mydb");
}

@After
public void tearDown() throws Exception {
    if (_mongod != null) {
        _mongod.stop();
    }
}
```

My JUnit test class contains 4 different test cases. Each of the tests succeeds when I run them one by one. When I try to run all 4 tests, the first will always succeed and the others will always fail, with the following exception:

de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not create Tempfile: C:\Users\Peter\AppData\Local\Temp\extract-Peter-mongod.exe
    at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:78)
    at wecloud.TestMongoDataStore.setUp(TestMongoDataStore.java:71)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.io.IOException: Could not create Tempfile: C:\Users\Peter\AppData\Local\Temp\extract-Peter-mongod.exe
    at de.flapdoodle.embed.process.io.file.Files.createTempFile(Files.java:60)
    at de.flapdoodle.embed.process.runtime.Starter.extractExe(Starter.java:89)
    at de.flapdoodle.embed.mongo.MongodStarter.extractExe(MongodStarter.java:61)
    at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:70)
    ... 25 more

Operating system is Windows 7, JDK 1.7, Eclipse Juno SR1. I have tried to place each test in a separate class but that did not seem to make any difference. If I run that as a suite, the first test succeeds but the remaining ones fail. 

Any input, hints or ideas are most appreciated.

**Comment by lokeshtank** [comment]
Hi I am new to embed.mongodb. while try to setup junit test cases environment, I am getting following error . 
I am using spring-data-mongodb: 1.6.1.RELEASE
de.flapdoodle.embed.mongo 1.47.3
org.springframework: 4.0.3.RELEASE

de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for http://downloads.mongodb.org/win32/mongodb-win32-i386-3.0.2.zip

Caused by: java.net.UnknownHostException: downloads.mongodb.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)

and also its pointing to  mongodb-win32-i386-3.0.2.zip but I am using windows 64 bit.
here is my code
package com.bosch.test;

import junit.framework.TestCase;

import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.support.AnnotationConfigContextLoader;

import com.bosch.in.model.Device;
import com.bosch.in.service.imp.DeviceServiceImp;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import com.mongodb.MongoClient;

import de.flapdoodle.embed.mongo.MongodExecutable;
import de.flapdoodle.embed.mongo.MongodProcess;
import de.flapdoodle.embed.mongo.MongodStarter;
import de.flapdoodle.embed.mongo.config.MongodConfigBuilder;
import de.flapdoodle.embed.mongo.config.Net;
import de.flapdoodle.embed.mongo.distribution.Version;
import de.flapdoodle.embed.process.runtime.Network;

@ContextConfiguration(classes=ApplicationConfig.class,loader=AnnotationConfigContextLoader.class)
@RunWith(SpringJUnit4ClassRunner.class)
public class DeviceServiceTest2 {
	    
	    private static final MongodStarter starter = MongodStarter
				.getDefaultInstance();

		private static MongodExecutable mongodExe;
		private static MongodProcess mongod;

		private static MongoClient mongo;

		
		private DeviceServiceImp deviceServiceImp;
		
		private MongoTemplate template;

		@BeforeClass
		public static void setUp() throws Exception {
			//System.out.println("1");
			mongodExe = starter.prepare(new MongodConfigBuilder()
					.version(Version.Main.V3_0)
					.net(new Net(12345, Network.localhostIsIPv6())).build());
			System.out.println("2");
			mongod = mongodExe.start();
			System.out.println("3");
			
			System.out.println("4");
			mongo = new MongoClient("12345", 12345);
			System.out.println("5");
			
		}

		@AfterClass
		public static void tearDown() throws Exception {
			mongod.stop();
			mongodExe.stop();
		}

		public Mongo getMongo() {
			return mongo;
		}
    
	@Test
	public void save(){
		
       System.out.println("1");
		
	}
		
	}



Could you please help me to resolve this please.

**Comment by michaelmosmann** [comment]
same issue as this one:  https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/126

**Comment by ashishk-jain** [comment]
I am getting similar issue but there are no exceptions.
Even thought I have used mongexe.stop in teardown method.
Individual test passes but when I run all tests together 2nd test onwards fails.
Even If I have debugger in 2nd test, then those tests passes too.

Junit 4, 
embed mongo version : 1.47.3/1.35/1.36
I have this code in teardown
    @After
    public void teardown() throws Exception {
        _mongodExe.stop();
        _mongod.stop();
    }

**Comment by ashishk-jain** [comment]
To be very specific first db query fails and all other db query passes.

**Comment by philnate** [comment]
It's probably not solving the issue seen here, but it's at least going into the right direction of making your tests fast and properly cleaning up side effects. But why would you do something resource intense like start/stop of mongo do per test? Even per test class, this seems overkill to me. Can provide you with code to have this started only once for a suite/class/test depending on your scope. To me this looks like the proper solution.

**Comment by ashishk-jain** [comment]
Thanks for your reply.

Yeah.. I need to do rationalize start/stop.

Share some the code you have something.
