### ISSUE TITLE
Exception on start up - java.lang.NoSuchFieldException: handle

### ISSUE THREAD

**Issue by kitkars** [flapdoodle-oss/de.flapdoodle.embed.mongo#376]
Hi Guys,

Do you know what is causing this? I am on MacOS (m1) + Java 17

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:113)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$3.getPid(Processes.java:215)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:82)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:65)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:165)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:96)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1930)
```

My maven dependency

```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.kitkars</groupId>
	<artifactId>my-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>my-service</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>11</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>de.flapdoodle.embed</groupId>
			<artifactId>de.flapdoodle.embed.mongo</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>testcontainers</artifactId>
			<version>1.16.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.testcontainers</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>1.16.3</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

**Comment by michaelmosmann** [comment]
Hi, can you try to run this code:
```java
System.out.println(javax.lang.model.SourceVersion.latest());
```

**Comment by michaelmosmann** [comment]
Maybe you should use:

<dependency>
			<groupId>de.flapdoodle.embed</groupId>
			<artifactId>de.flapdoodle.embed.mongo</artifactId>
			<scope>test</scope>
			<version>3.3.3</version>
		</dependency>

**Comment by kitkars** [comment]
Ok Thanks, will test and confirm

**Comment by codengy** [comment]
Hi,

I have same issue with version 3.4.6

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2642)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:112)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:48)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$3.getPid(Processes.java:218)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:81)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:65)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:165)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:96)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:109)
	at com.lindar.mrq.risk.cucumber.config.EmbeddedMongoConfiguration.startMongo(EmbeddedMongoConfiguration.kt:38)
...
```

and exception is thrown in method: _mongodExecutable.start()_

**Comment by codengy** [comment]
MacOS (M1), JDK 17, but app is Java version 8

**Comment by michaelmosmann** [comment]
@codengy there is a new release.. the problem is not the app code version but the running jdk ..

**Comment by Moez1010** [comment]
Yes It's works for me with 3.4.9

**Comment by michaelmosmann** [comment]
.. if this is still an issue, please reopen.

**Comment by monu-k2io** [comment]
Facing this issue with 3.5.4 , JDK 21
