### ISSUE TITLE
IOException: Could not open inputStream SSL peer shutdown incorrectly

### ISSUE THREAD

**Issue by AshuRane09** [flapdoodle-oss/de.flapdoodle.embed.mongo#381]
i am getting this error

de.flapdoodle.embed.proces process.exceptions.Distribution Exception: prepare executable.

Caused by: java.io.IOException Create breakpoint: Could not open inputstream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-4.0.2.zip.

Caused by: javax.net.ssl.SSLHandshakeException Create breakpoint: Remote host closed connection during handshake.

Spring boot version - 2.1.4
embed.mongo version - 2.1.2

i tried changing version to 3.4.3 and 3.3.2 but it broke my code.

**Comment by michaelmosmann** [comment]
@AshuRane09  .. can you give me the error message/stack trace/compile error?

**Comment by AshuRane09** [comment]
Caused by: java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ss1-4.0.2. at de. flapdoodle.embed.process.store.Downloader.download InputStream(Downloader.java:131)

at de.flapdoodle.embed.process.store.Downloader.download (Downloader.java:69) at de.flapdoodle.embed.process.store. ArtifactStore.checkDistribution (ArtifactStore.java:66)

at de. flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution (ExtractedArtifactStore.java:60)

at de. flapdoodle.embed.process.runtime.Starter.prepare (Starter.java:52)

... 21 more

Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake at sun.security.ssl.SSLSocket Impl.readRecord (SSL SocketImpl.java:994)

ava:60)

at sun.security.ssl.SSLSocketImpl.performInitialHandshake (SSLSocket Impl. java:1367) at sun.security.ssl.SSL SocketImpl.startHandshake (SSLSocket Impl.java:1395)

at sun.security.ssl.SSLSocket Impl.startHandshake (SSLSocketImp1.java:1379)

at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURL Connection.java:185). at sun.net.www.protocol.http.HttpURLConnection.getInputStreame(HttpURL Connection.java:1564)

at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) at sun.net.www.protocol.https.HttpsURLConnectionImpl. getInputStream(HttpsURL ConnectionImpl.java:263)

at de flapdoodle.embed.process.store.Downloader.downloadInputStream (Downloader.java:127)

...25 more Caused by: java.io.EOFException: SSL peer shut down incorrectly.

at sun.security.ssl.InputRecord.read(InputRecord.java:505) at sun.security.ssl.SSLSocket Impl. readRecord (SSL SocketImp1.java:975)

**Comment by AshuRane09** [comment]
Caused by: java.io.IOException: Could not open inputStream for https://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ss1-4.0.2. at de. flapdoodle.embed.process.store.Downloader.download InputStream(Downloader.java:131)

at de.flapdoodle.embed.process.store.Downloader.download (Downloader.java:69) at de.flapdoodle.embed.process.store. ArtifactStore.checkDistribution (ArtifactStore.java:66)
at de. flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution (ExtractedArtifactStore.java:60)
at de. flapdoodle.embed.process.runtime.Starter.prepare (Starter.java:52)


Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake at sun.security.ssl.SSLSocket Impl.readRecord (SSL SocketImpl.java:994)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake (SSLSocket Impl. java:1367) at sun.security.ssl.SSL SocketImpl.startHandshake (SSLSocket Impl.java:1395)
at sun.security.ssl.SSLSocket Impl.startHandshake (SSLSocketImp1.java:1379)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURL Connection.java:185). at sun.net.www.protocol.http.HttpURLConnection.getInputStreame(HttpURL Connection.java:1564)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) at sun.net.www.protocol.https.HttpsURLConnectionImpl. getInputStream(HttpsURL ConnectionImpl.java:263)
at de flapdoodle.embed.process.store.Downloader.downloadInputStream (Downloader.java:127)

Caused by: java.io.EOFException: SSL peer shut down incorrectly.
at sun.security.ssl.InputRecord.read(InputRecord.java:505) at sun.security.ssl.SSLSocket Impl. readRecord (SSL SocketImp1.java:975)

**Comment by michaelmosmann** [comment]
@AshuRane09 can you show me the error message if you change embed mongo to 3.3.2? the exception above is just bc the download fails.

**Comment by michaelmosmann** [comment]
@AshuRane09 is this still an issue? please reopen if needed.
