### ISSUE TITLE
test with embedded MongoDB (3.4.3) fails on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by FrVaBe** [flapdoodle-oss/de.flapdoodle.embed.mongo#383]
I generated a **Java 11** **Spring Boot 2.6.4** project on start.spring.io and just added _Spring Data MongoDB_ and _EmbeddedMongoDB Database_ (this is the [Share...](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.6.4&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=embedded-mongodb-test-demo&name=embedded-mongodb-test-demo&description=Demo%20project%20for%20Spring%20Boot%20with%20an%20embedded%20MongoDB%20test&packageName=com.example.embedded-mongodb-test-demo&dependencies=data-mongodb,flapdoodle-mongo) link)

I changed the generated test class to a very simple `@DataMongoTest`

```java
@DataMongoTest
class EmbeddedMongodbTestDemoApplicationTests {
	
        @Autowired
	private MongoTemplate mongoTemplate;
	
        @Test
	void contextLoads() {
		assertNotNull(mongoTemplate);
	}
}
```

and added the `spring.mongodb.embedded.version=4.4.1` to the _application.properties_.

As MongoDB changed the downlaod locations of the community server packages, the download of MongoDB fails with the manged version `de.flapdoodle.embed.mongo:3.0.0`. I guess this is already addressed somewhere else and updated the version to  `de.flapdoodle.embed.mongo:3.4.3`

The test works fine now on Windows but fails on Ubuntu 20.04 (which is the OS we use for CI/CD builds).

Besides our build system I reproduced the failure in an Ubuntu image running on the _Windows-Subsystems for Linux (WSL)_ (which I created some times ago, please do not ask me how).

The error in short is

```
Caused by: java.lang.RuntimeException: Could not start process: <EOF>
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) ~[de.flapdoodle.embed.mongo-3.4.3.jar:na]
        at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:113) ~[de.flapdoodle.embed.process-3.1.7.jar:na]
        at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) ~[de.flapdoodle.embed.mongo-3.4.3.jar:na]
        at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) ~[de.flapdoodle.embed.mongo-3.4.3.jar:na]
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44) ~[de.flapdoodle.embed.mongo-3.4.3.jar:na]
        at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34) ~[de.flapdoodle.embed.mongo-3.4.3.jar:na]
        at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:109) ~[de.flapdoodle.embed.process-3.1.7.jar:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1930) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872) ~[spring-beans-5.3.16.jar:5.3.16]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.16.jar:5.3.16]
        ... 83 common frames omitted

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.413 s <<< FAILURE! - in com.example.embeddedmongodbtestdemo.EmbeddedMongodbTestDemoApplicationTests
[ERROR] contextLoads  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not start process: <EOF>
Caused by: java.lang.RuntimeException: Could not start process: <EOF>
```
I attached the full stacktrace and the sample project.

[fullStacktrace.txt](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/8213095/fullStacktrace.txt)
[embedded-mongodb-test-demo.zip](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/files/8213097/embedded-mongodb-test-demo.zip)

**Comment by michaelmosmann** [comment]
@FrVaBe hmm.. sample projects just works find on my machine .. what makes me wonder is this entry from the stacktrace-log:

2022-03-09 08:52:00.010  INFO 3768 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : {"t":{"$date":"2022-03-09T08:52:00.009+01:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":22,"message":"[1646812320:9844][3828:0x7fb4f3bb0c80], connection: __posix_sync, 99: /tmp/embedmongo-db-a9dccc3a-8c94-4df6-aa3a-bc08c3cc5ea5/: directory-sync: fdatasync: Invalid argument"}}

is /tmp/embedmongo-db-a9dccc3a-8c94-4df6-aa3a-bc08c3cc5ea5/ not writeable?

**Comment by FrVaBe** [comment]
@michaelmosmann What do you mean with "on my machine"? If the build works fine or not depends on the OS. It works fine on my (windows) machine too but the build failed in the WSL Ubuntu environment.

But in the meantime I found out that my Ubuntu version was outdated and I stll used WSL Version 1. So I updated the ubuntu distribution and set the WSL Version to 2. And after that the error (also) disappeared on my windows machine using wsl.

I will now check how the build behaves in oour CI/CD pipeline with a real ubtunu image and come back later.

**Comment by michaelmosmann** [comment]
@FrVaBe "What do you mean with "on my machine"?" ... i am working on ubuntu .. so there was nothing wrong with this project setup.

WSL: interesting .. never tried that ..

(was sick, so missed some notifications)

**Comment by michaelmosmann** [comment]
@FrVaBe do you have still this issue?

**Comment by FrVaBe** [comment]
@michaelmosmann To be honest, the problem hit me and I then worked around it and didn't have the time to pursue it further.

I will be upgrading to Spring Boot 2.7.x soon and that will certainly bring new dependency versions with it. If the problem still exists and I can provide a scenario in which it can be reproduced, I will get back to you.

Until then, it is only fair to close the issue for now (and I will do so).

**Comment by eladeyal-intel** [comment]
I had this, on Ubuntu 22.04 WSL2:

`Download Version{5.0.5}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04}`

`/tmp/extract-c3d4c6d1-7b9b-42d2-85e8-9a03bb783feaextractmongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory`

Following these instructions to install `libssl1.1` seemed to have solved: https://stackoverflow.com/a/72633324

**Comment by EXayer** [comment]
Have a similar error, running in docker, in my project 
https://github.com/dota-showcase/inventory-service/blob/main/app/Dockerfile


`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.process.config.RuntimeConfig]: Factory method 'embeddedMongoRuntimeConfig' threw exception; nested exception is java.lang.NoSuchFieldError: Ubuntu_21_04`

**Comment by michaelmosmann** [comment]
@EXayer as far as i can see: you are running the default spring integration for spring 2.7.x with java17 .. i suggest that you upgrade to this: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/tree/spring-2.7.x .. and if this does not work i would suggest to open an new issue with a full stacktrace:)

**Comment by EXayer** [comment]
@michaelmosmann, Your suggestion didn't help.
 I've update spring boot to version 3, to use de.flapdoodle.embed.mongo.spring30x. There wasn't this problem.
 Thanks.
