### ISSUE TITLE
Hang in AbstractMongoProcess onAfterProcessStart when successful start takes longer than then startup timeout

### ISSUE THREAD

**Issue by wilkinsona** [flapdoodle-oss/de.flapdoodle.embed.mongo#385]
Spring Boot's CI build hangs occasionally when running tests that use Embedded Mongo. When hung, the stack trace is the following:

```
"Test worker" #1 prio=5 os_prio=0 cpu=119615.45ms elapsed=5444.84s tid=0x00007f334c036c90 nid=0xb38 in Object.wait()  [0x00007f335294f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@17.0.2/Object.java:338)
	at java.lang.ProcessImpl.waitFor(java.base@17.0.2/ProcessImpl.java:434)
	- locked <0x00000000ec815500> (a java.lang.ProcessImpl)
	at de.flapdoodle.embed.process.runtime.ProcessControl.waitFor(ProcessControl.java:200)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:78)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:113)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
	at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
	at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:109)
```

The call to `java.lang.ProcessImpl.waitFor` never returns.

This is the code that's involved:

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/ec5bd1ba61a8aec4b7e66ac3efee11fef4c08eda/src/main/java/de/flapdoodle/embed/mongo/AbstractMongoProcess.java#L56-L85

My theory is that `logWatch.waitForResult(getConfig().timeout().getStartupTimeout());` returns because the startup timeout period has elapsed. At this point Mongo is in the middle of starting up successfully, but has not yet output the success message. As a result, we drop into the `else` block and a call to `waitFor` is made in anticipation of the process failing to start. As the start is successful (although rather slow), `waitFor` never returns and a hang occurs.

We're currently relying on the default timeout which appears to be too short for our sometimes congested and slow CI infrastructure. We can increase the timeout to reduce the chances of the hang occurring, but I wonder if `onAfterProcessStart` could be modified so that the possibility of a hang is eliminated entirely? Perhaps this could be done by passing a timeout into `Process.waitFor`?

**Comment by michaelmosmann** [comment]
@wilkinsona .. hmm.. your analysis seems valid ... waitFor should use a timeout so it aborts somehow

**Comment by michaelmosmann** [comment]
@wilkinsona (was sick, still a little, so will take some time)

**Comment by wilkinsona** [comment]
Thanks, @michaelmosmann. We’ll upgrade to 3.4.5 and see how it goes. The hang only happens occasionally so it’ll take a while to get an impression of whether it has helped.

**Comment by michaelmosmann** [comment]
.. if this still an issue, please reopen.
