### ISSUE TITLE
Flapdoodle "Couldn't kill mongod process!" after v3.1.4 on macOS

### ISSUE THREAD

**Issue by snazy** [flapdoodle-oss/de.flapdoodle.embed.mongo#388]
All versions after 3.1.4 run into the following issue when trying to stop the mongod process on macOS Monterey (latest).

```
java.lang.IllegalStateException: 
Couldn't kill mongod process!
	at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:153)
	at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:81)
	at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:77)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:196)
	at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:119)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:174)
	at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:81)
	at org.projectnessie.versioned.persist.mongodb.FlapdoodleMongoTestConnectionProviderSource.stop(FlapdoodleMongoTestConnectionProviderSource.java:141)
	at org.projectnessie.versioned.persist.tests.extension.DatabaseAdapterExtension$ClassDbAdapters.close(DatabaseAdapterExtension.java:102)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
...
```

One of the recent PRs to bump flapdoodle to 3.4.4 (also 3.4.5 today) is this one. It works fine on Linux, but not on macOS.

Our Dependabot PR: https://github.com/projectnessie/nessie/pull/3787 [unified diff](https://patch-diff.githubusercontent.com/raw/projectnessie/nessie/pull/3787.patch)

Steps to reproduce (on macOS):
* `git clone https://github.com/projectnessie/nessie.git`
* `./mvnw -Dquickly`
* `./mvnw clean verify -pl versioned/persist/mongodb`

**Comment by michaelmosmann** [comment]
@snazy will try this.. but don't have macos to test this..

**Comment by michaelmosmann** [comment]
@snazy .. still an issue?

**Comment by snazy** [comment]
Can't say. We've removed flapdoodle from the project due to this issue a while ago.
