### ISSUE TITLE
When stopping receiving 11600 error "interrupted at shutdown"

### ISSUE THREAD

**Issue by dstibbe** [flapdoodle-oss/de.flapdoodle.embed.mongo#391]
Specs:
flapdoodle: 3.4.5
kmongo 4.2.7
language: Kotlin 1.6.20

When connecting in a test to the embedded mongo database (using a KMongo client) , I try to close the database in the tearDown, using the `stop()` method.

```
 @AfterTest
    fun tearDown() = runBlocking {
        withContext(Dispatchers.Default) {
            mongodExecutable?.stop()
        }
    }
```

The stop command however will show the following error in the log:

```
...
2022-04-17 23:37:01.064 [cluster-ClusterId{value='625c8873b179cf0b6348ad54', description='null'}-localhost:27017] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoNodeIsRecoveringException: Command failed with error 11600 (InterruptedAtShutdown): 'interrupted at shutdown' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "interrupted at shutdown", "code": 11600, "codeName": "InterruptedAtShutdown"}
	at com.mongodb.internal.connection.ProtocolHelper.createSpecialException(ProtocolHelper.java:242)
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:171)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.InternalStreamConnection.receive(InternalStreamConnection.java:315)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:215)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144)
	at java.base/java.lang.Thread.run(Thread.java:833)
...
```

Fladpdoodle setup:

```
  ...
   val processOutput = ProcessOutput.builder()
            .output(Processors.logTo(logger, Slf4jLevel.DEBUG))
            .error(Processors.logTo(logger, Slf4jLevel.ERROR))
            .commands(Processors.named("[console>]", Processors.logTo(logger, Slf4jLevel.INFO)))
            .build()

        val runtimeConfig: RuntimeConfig = Defaults.runtimeConfigFor(Command.MongoD, logger)
            .processOutput(processOutput)
            .artifactStore(
                Defaults.extractedArtifactStoreFor(Command.MongoD)
                    .download(
                        Defaults.downloadConfigFor(Command.MongoD)
                            .progressListener(Slf4jProgressListener(logger))
                    )
            )
            .build()

        val starter = MongodStarter.getInstance(runtimeConfig)

        val port: Int = Network.freeServerPort(InetAddress.getByName("localhost"), 27017)
        val mongodConfig: MongodConfig = MongodConfig.builder()
            .version(Version.Main.PRODUCTION)
            .net(Net(port, Network.localhostIsIPv6()))
            .build()

        mongodExecutable = starter.prepare(mongodConfig)
        mongodExecutable?.start()
       ...
```

What can I do to avoid this error?

**Comment by michaelmosmann** [comment]
@dstibbe maybe you must close the driver connection .. stopping the executable will shutdown the connection from the server side, so the driver cries a little bit about that .. :)

**Comment by dstibbe** [comment]
Indeed, it seems to be the case that there was another client still connected to the database. That was most likely the cause of my errors.
