### ISSUE TITLE
Unable to run binary from /tmp (GitLab)

### ISSUE THREAD

**Issue by stefanbethke** [flapdoodle-oss/de.flapdoodle.embed.mongo#413]
We're using GitLab to run our Maven pipeline for our Spring Boot project, and the default setup for a Docker runner does not allow running executables from /tmp:

```
2022-07-20 07:16:27.207  INFO 107 --- [           main] .t.c.g.m.r.Grove404RepositoryServiceTest : Starting Grove404RepositoryServiceTest using Java 11.0.9 on runner-bteckse3-project-1580-concurrent-0 with PID 107 (started by root in /builds/cmshared/cmcc-grove/grove-mongo)
2022-07-20 07:16:27.209  INFO 107 --- [           main] .t.c.g.m.r.Grove404RepositoryServiceTest : The following 1 profile is active: "groveMongoRepositoryTest"
2022-07-20 07:16:27.370  INFO 107 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2022-07-20 07:16:27.412  INFO 107 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 38 ms. Found 2 MongoDB repository interfaces.
2022-07-20 07:16:27.651  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:27.654  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:27.654  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : starting...
2022-07-20 07:16:27.655  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:27.657  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:28.361  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : DownloadSize: 72382504
2022-07-20 07:16:28.364  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 0 %
2022-07-20 07:16:28.596  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 10 %
2022-07-20 07:16:28.751  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 20 %
2022-07-20 07:16:28.822  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 30 %
2022-07-20 07:16:30.534  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 40 %
2022-07-20 07:16:30.589  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 50 %
2022-07-20 07:16:30.958  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 60 %
2022-07-20 07:16:31.003  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 70 %
2022-07-20 07:16:31.834  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 80 %
2022-07-20 07:16:33.518  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 90 %
2022-07-20 07:16:33.570  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : 100 %
2022-07-20 07:16:33.570  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : downloaded with 14137kb/s
2022-07-20 07:16:33.627  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} : finished
2022-07-20 07:16:33.628  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:33.630  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:33.630  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:33.631  WARN 107 --- [           main] d.f.e.m.p.linux.LinuxPackageFinder       : because there is no package for Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to Version{4.4.13}:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
2022-07-20 07:16:33.631  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.13.tgz : starting...
2022-07-20 07:16:34.421  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.13.tgz : extract mongodb-linux-x86_64-ubuntu2004-4.4.13/bin/mongod
2022-07-20 07:16:34.421  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.13.tgz : nothing left
2022-07-20 07:16:34.421  INFO 107 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /root/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.13.tgz : finished
2022-07-20 07:16:34.516 ERROR 107 --- [           main] d.f.e.process.runtime.AbstractProcess    : failed to call start()
 
java.io.IOException: Cannot run program "/tmp/extract-de278330-74f1-4748-ab3b-4917434ebae9extractmongod": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128) ~[na:na]
```

I've tried the suggestion from https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/122 but my config is being ignored, flapdoodle is still using /tmp/... for the executable.

Is there any documentation that clearly shows how to:
* configure how the Mongo installation archive is downloaded, and
* how and where the mongod executable is being configured?

The code is hard to understand, and there doesn't seem to exist a concise documentation on how to configure the whole caboodle, apart from a few examples in the readme?

**Comment by stefanbethke** [comment]
I thought at first that this was an issue with permissions, but setting de.flapdoodle.embed.io.tmpdir to a path that definitely allows execution, it seems that the extraction process is failing to put the binary there. Since everything appears to be working locally as expected, it's not easy to debug this...

**Comment by stefanbethke** [comment]
In the latest test run, I get this in the log:
```
2022-07-20 09:54:59.967 ERROR 139 --- [           main] d.f.e.process.runtime.AbstractProcess    : failed to call start()
 
java.io.IOException: Cannot run program "/builds/cmshared/cmcc-grove/grove-mongo/target/extract-49149441-e32f-4baf-a46c-42098a90345eextractmongod": error=2, No such file or directory
```

However, right after the mvn clean install that triggered the test run, I find this:
```
[32;1m$ find grove-mongo/target[0;m
...
grove-mongo/target/extract-49149441-e32f-4baf-a46c-42098a90345eextractmongod
```

I'm at a loss why the executable cannot be found.

**Comment by stefanbethke** [comment]
I've downloaded the files, and it seems to be OK:
```
$ find ${PWD}/grove-mongo/target -name "*extract*" | sort | xargs ls -ld
-rwxr--r--    1 root     root     109013152 Jul 20 10:26 /builds/cmshared/cmcc-grove/grove-mongo/target/embedmongo/Linux-B64--unknown---5.0.6/extractmongod
-rwxr--r--    1 root     root     109013152 Jul 20 10:26 /builds/cmshared/cmcc-grove/grove-mongo/target/extract-027d8180-0d1e-46b4-a594-a3e816a00717extractmongod
-rwxr--r--    1 root     root     109013152 Jul 20 10:26 /builds/cmshared/cmcc-grove/grove-mongo/target/extract-25b8e3d5-fd16-40a9-a5dc-f41a161185b9extractmongod
...
$ file extract-027d8180-0d1e-46b4-a594-a3e816a00717extractmongod
extract-027d8180-0d1e-46b4-a594-a3e816a00717extractmongod: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=b60370782f11d564671bb41fda010a41e42f30e7, not stripped
```

The only thing I can think of is that /lib64/ld-linux-x86-64.so.2 is not a valid interpreter in our Docker image. I will check that next.

**Comment by stefanbethke** [comment]
I can run the downloaded binary from the pipeline archive in the docker image the pipeline is using. So I'm at a complete loss why the file cannot be found. Is this a race condition with regards to the tests? But the log output has the extraction of the archive before the error, so that doesn't appear to make sense.

I'll try running the commands with the Docker image manually, instead of through the Gitlab runner, to see if that makes any difference.

**Comment by stefanbethke** [comment]
Hah. It appears that /lib64/ld-linux-x86-64.so.2 is in fact missing, leading to the ENOENT error.

**Comment by stefanbethke** [comment]
The problem is in fact that the MongoDB binary cannot run in the image we're using, so essentially, this has nothing to do with Flapdoodle.

**Comment by F-Node-Karlsruhe** [comment]
Any updates on which images work with flapdoodle embedded mongo?

Running with gitlab-runner 16.11.1 (535ced5f) with any jdk image does not work for me

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe the jdk is needed for this project... but there must be a supported linux distribution for the mongod binary.. so something like debian, ubuntu, redhed should work..

**Comment by F-Node-Karlsruhe** [comment]
The strange thing is, that it works locally and locally in a docker container, e.g. with image maven:3.9-eclipse-temurin-17 but as soon as it is run in the gitlab pipeline (even with docker) 

```
#11 138.4 Caused by: java.lang.RuntimeException: Could not start process: 
#11 138.4 ----------------------
#11 138.4 Hmm.. no failure or success message after 60000ms .. 
#11 138.4 ...the cause must be somewhere in the process output:
#11 138.4 - 8<- - - - - - - - - -
#11 138.4 
#11 138.4 
#11 138.4 
#11 138.4 - >8- - - - - - - - - -
#11 138.4 
#11 138.4 	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$null$1(RunningMongoProcess.java:180) ~[de.flapdoodle.embed.mongo-4.1
```

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe is there some logging ahead of "Could not start process"? Maybe you should open a new issue..

**Comment by michaelmosmann** [comment]
@F-Node-Karlsruhe created a new issue.. https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/525
