### ISSUE TITLE
ContentHashExtractedFileSetStore fails with embed.mongo when ~/.embedmongo does not exist

### ISSUE THREAD

**Issue by froth** [flapdoodle-oss/de.flapdoodle.embed.mongo#436]
mondod.start fails when ~/.embedmongo does not exist, works fine if it does.

```
Caused by: java.nio.file.NoSuchFileException: /home/me/.embedmongo/fileSets
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at de.flapdoodle.embed.process.store.ContentHashExtractedFileSetStore.lambda$new$0(ContentHashExtractedFileSetStore.java:50)
	at de.flapdoodle.types.ThrowingRunnable.lambda$mapCheckedException$0(ThrowingRunnable.java:27)
```

I believe the problem is at the line linked below (and maybe on other calls of `java.nio.file.Files.createDirectory`), because createDirectory does not create parent dirs. I think createDirectories should work, but I haven't read all the code so maybe the problem is somewhere else.

https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/main/src/main/java/de/flapdoodle/embed/process/store/ContentHashExtractedFileSetStore.java#L50

**Comment by froth** [comment]
Awesome, thanks a lot!

**Comment by michaelmosmann** [comment]
@froth does it work and can i close this issue?

**Comment by froth** [comment]
It works fine for the default directory.

However when defining a different directory via `Transition[PersistentDir]` this still does not get created. I am not sure if this is also a bug or "works as intended".

**Comment by michaelmosmann** [comment]
@froth yes.. i have to think about that.. maybe it should be created by default.. because everything else expect that PersistentDir exists..

**Comment by michaelmosmann** [comment]
@froth .. will solve this today

**Comment by froth** [comment]
Thanks! I implemented something similar as workaround for the time being  :)

**Comment by michaelmosmann** [comment]
@froth .. i did a new release (4.1.3) which will take some time to reach maven central.. where this should be fixed.. so no workaround needed anymore.. 
thank you for your bug ticket:)

**Comment by froth** [comment]
Now I get a different error:

```
Caused by: java.lang.IllegalArgumentException: does not exist: .embed-mongo
        at de.flapdoodle.checks.Preconditions.checkArgument(Preconditions.java:32)
        at de.flapdoodle.embed.process.io.directories.PersistentDir.check(PersistentDir.java:45)
        at de.flapdoodle.embed.process.io.directories.ImmutablePersistentDir.validate(ImmutablePersistentDir.java:86)
        at de.flapdoodle.embed.process.io.directories.ImmutablePersistentDir.of(ImmutablePersistentDir.java:82)
        at de.flapdoodle.embed.process.io.directories.PersistentDir.of(PersistentDir.java:50)
```

when using the following configuration to use a subfolder of the current dir:

```
Mongod mongod = new Mongod() {
  @Override
  public Transition<PersistentDir> persistentBaseDir() {
    return Start.to(PersistentDir.class).providedBy(() => PersistentDir.of(Paths.get(".embed-mongo")));
  }
};
``` 

However the more I think about it, configuring it via the env variable is most likely better for my usecase anyways :)

Thanks for the fast replies :)

**Comment by michaelmosmann** [comment]
@froth only if you are using PersistentDir.inUserHome(yourPathName) the directory relative to user-home is created.. but in every other case you must create the directory.. and i added a check that it exists. Even if you are using the env variable it should exist.

I do not like the idea, that the creation of an instance has the side effect of creating a directory.

**Comment by michaelmosmann** [comment]
@froth .. in the next release there will be PersistentDir.inWorkingDir(subDir) which creates the subdirectory

**Comment by froth** [comment]
That sounds logical, thanks for the Answers!

**Comment by michaelmosmann** [comment]
@froth we can leave this open until the next release fit's your need:)

**Comment by michaelmosmann** [comment]
@froth release is done .. now you can use 

```java
PersistentDir.inWorkingDir(".embedmongo")
```

which gives you a `ThrowableSupplier<PersistenDir, IOException>`

.. one way to get an Supplier from that: 

```java
PersistentDir.inWorkingDir(".embedmongo").mapCheckedException(RuntimeException::new)::get
```

**Comment by froth** [comment]
Works like a charm, thanks!

**Comment by michaelmosmann** [comment]
.. so I close this issue:)
