### ISSUE TITLE
ConsoleOneLineProgressListener is broken

### ISSUE THREAD

**Issue by ydylla** [flapdoodle-oss/de.flapdoodle.embed.mongo#450]
Hi,
just to let you know. When using the `ConsoleOneLineProgressListener` I get the following Exception:
```
Caused by: java.lang.NegativeArraySizeException: -5
        at de.flapdoodle.embed.process.io.progress.ConsoleOneLineProgressListener.makeString(ConsoleOneLineProgressListener.java:90)
        at de.flapdoodle.embed.process.io.progress.ConsoleOneLineProgressListener.progress(ConsoleOneLineProgressListener.java:63)
        at de.flapdoodle.embed.process.net.UrlStreams.lambda$downloadCopyListenerDelegatingTo$2(UrlStreams.java:116)
        at de.flapdoodle.embed.process.net.UrlStreams.downloadAndCopy(UrlStreams.java:83)
        at de.flapdoodle.embed.process.net.UrlStreams.downloadIntoTempFile(UrlStreams.java:61)
        at de.flapdoodle.embed.process.net.UrlStreams.lambda$downloadTo$0(UrlStreams.java:47)
        at de.flapdoodle.embed.process.net.UrlStreams.downloadTo(UrlStreams.java:52)
        at de.flapdoodle.embed.process.net.UrlStreams.downloadTo(UrlStreams.java:47)
        at de.flapdoodle.embed.process.transitions.DownloadPackage.lambda$result$3(DownloadPackage.java:131)
        at de.flapdoodle.types.ThrowingRunnable.lambda$mapException$0(ThrowingRunnable.java:28)
        at de.flapdoodle.embed.process.transitions.DownloadPackage.result(DownloadPackage.java:133)
        at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:62)
        at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:50)
        at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:165)
        ... 132 more
```
The label `download https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.18.tgz` is 84 characters long which causes `int lineLength = LINE_LEN - label.length() - 1;` to become negative.

**Comment by michaelmosmann** [comment]
@ydylla ups..

**Comment by michaelmosmann** [comment]
@ydylla fixed .. there will be a new release soon..
