### ISSUE TITLE
Flapdoodle 3.4.5 and Mac M2 Issue?

### ISSUE THREAD

**Issue by andregasser** [flapdoodle-oss/de.flapdoodle.embed.mongo#465]
Hello there!

I am facing an issue of running our tests on a new M2 MacBook Pro. We're using flapdoodle 3.4.5 directly in our code (no spring integration). The same tests run on M1 macbooks without issues. Also on Windows machines, these tests run fine.

Is there a known issue with this scenario? Thanks for any help.

This is the output I get from the tests:

```bash
Caused by:
de.flapdoodle.embed.process.exceptions.DistributionException: java.io.EOFException
  at app//de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:71)
  at app//de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
  at app//ch.something.backend.testmongo.EmbeddedTestMongoDBFactory.init(EmbeddedTestMongoDBFactory.java:82)
  at jdk.internal.reflect.GeneratedMethodAccessor175.invoke(Unknown Source)
  at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
  at app//org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
  at app//org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
  at app//org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
  ... 200 more

  Caused by:
  java.io.EOFException
    at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:306)
    at java.base/java.io.InputStream.skip(InputStream.java:547)
    at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:121)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.skip(TarArchiveInputStream.java:276)
    at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:121)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:364)
    at de.flapdoodle.embed.process.extract.AbstractTarExtractor$TarArchiveWrapper.getNextEntry(AbstractTarExtractor.java:45)
    at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:69)
    at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:86)
    at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:103)
    at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:59)
    ... 208 more
```

Scrolling down the test output I could also find this:

```java
Caused by:
de.flapdoodle.embed.process.extract.ExecutableFileAlreadyExistsException: de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: could not create: /Users/taagaanf/.embedmongo/extracted/OS_X-B64--unknown---4.2.13/extractmongod
  at app//de.flapdoodle.embed.process.extract.FilesToExtract$Match.write(FilesToExtract.java:125)
  at app//de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:75)
  at app//de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:86)
  at app//de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:103)
  at app//de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:59)
  ... 209 more

  Caused by:
  de.flapdoodle.embed.process.io.file.FileAlreadyExistsException: could not create: /Users/taagaanf/.embedmongo/extracted/OS_X-B64--unknown---4.2.13/extractmongod
    at app//de.flapdoodle.embed.process.io.file.Files.createTempFile(Files.java:69)
    at app//de.flapdoodle.embed.process.extract.FilesToExtract$Match.write(FilesToExtract.java:123)
    ... 213 more
```

In the code, I have configured flapdoodle to use this version:

```java
Version DEFAULT_VERSION = Version.V4_2_13;
```

My M2 Macbook reports this when running `uname -a`:
```bash
Darwin UM01828 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64
```

The `.embedmongo` folder in my user home directory also seems to not really extract the tgz file:
<img width="1032" alt="Screenshot 2023-06-23 at 09 00 01" src="https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/assets/535130/21736149-332b-4dfa-8943-88f23e427d59">

**Comment by michaelmosmann** [comment]
@andregasser is it possible to use the newest version of flapdoodle?

**Comment by michaelmosmann** [comment]
@andregasser is this still an issue?

**Comment by andregasser** [comment]
Hello @michaelmosmann Sorry for the late reply. Unfortunately, it is not that easy for us to update to the newest version quickly. Feel free to close this issue. Once I find time to look more into this, I might reopen it again. Hope this is ok for you. Have a great day!

**Comment by michaelmosmann** [comment]
@andregasser yes .. no problem with that.. :)
