### ISSUE TITLE
Process starts locally but fails in docker container

### ISSUE THREAD

**Issue by t0ry** [flapdoodle-oss/de.flapdoodle.embed.mongo#474]
Hi there,

I'm experiencing the next problem.

Setup is the following:

- `build.gradle`
```
    componentTestImplementation "de.flapdoodle.embed:de.flapdoodle.embed.mongo:4.6.1"
    componentTestImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo.spring30x:4.6.1'
```
- `application-test.properties` : `de.flapdoodle.mongodb.embedded.version=3.6.1`

- `gradle componentTest` runs in docker container
```
FROM gradle:7.6.1-jdk17  # ubuntu 22 + gradle7.6.1 + jdk17
RUN mkdir /home/gradle/service
WORKDIR /home/gradle/service
ENV GRADLE_RUN_TASKS="clean componentTest"
ENV GRADLE_RUN_OPTS=""
ENV GIT_COMMIT=""
CMD gradle $GRADLE_RUN_TASKS $GRADLE_RUN_OPTS --no-daemon
```

This setup runs in docker container as expected.

On Change in  `application-test.properties` : `de.flapdoodle.mongodb.embedded.version=5.0.5` `gradle componentTest` runs as expected locally (Unbuntu 18) but fails in docker container with the following stack trace:
```
Caused by: java.lang.RuntimeException: error on transition to State(de.flapdoodle.embed.mongo.transitions.RunningMongodProcess), rollback
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:174)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69)
	at de.flapdoodle.embed.mongo.spring.autoconfigure.MongodWrapper.start(MongodWrapper.java:45)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1861)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1818)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)
	... 138 more
Caused by: java.lang.RuntimeException: Could not start process: 
----------------------
Hmm.. no failure message.. 
...the cause must be somewhere in the process output
----------------------


	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$null$1(RunningMongoProcess.java:179)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$factory$3(RunningMongoProcess.java:185)
	at de.flapdoodle.embed.process.types.RunningProcess.start(RunningProcess.java:78)
	at de.flapdoodle.embed.mongo.transitions.MongoServerStarter.result(MongoServerStarter.java:119)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:62)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:50)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:165)
```

Any ideas?

Thanks in advance

**Comment by t0ry** [comment]
Scavenging through other issues I found the problem was in 
`de.flapdoodle.mongodb.embedded.version < 6.0.4` so setting `de.flapdoodle.mongodb.embedded.version=6.0.4` did the trick.

Details are here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/395#issuecomment-1638331115

Closing issue then
