### ISSUE TITLE
could not resolve package for Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian} testing

### ISSUE THREAD

**Issue by Marthym** [flapdoodle-oss/de.flapdoodle.embed.mongo#489]
Hi

I'am not able to resolve package for Debian testing.

May be related to #437 

Thanks for your help

```
Caused by: java.lang.IllegalArgumentException: could not resolve package for V6_0:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian}
--------------
(os=Windows)
  (os=Windows and bitSize=B64 and cpuType=X86) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
    url=/windows/mongodb-windows-x86_64-{version}.zip (ZIP(DEV))
  (os=Windows and bitSize=B64 and cpuType=X86) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23)
    url=/windows/mongodb-windows-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B64 and cpuType=X86) and (4.2.5-4.2.24 or 4.2.0-4.2.3)
    url=/win32/mongodb-win32-x86_64-2012plus-{version}.zip (ZIP)
  (os=Windows and bitSize=B64 and cpuType=X86) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
    url=/win32/mongodb-win32-x86_64-2008plus-ssl-{version}.zip (ZIP)
  (os=Windows and bitSize=B64 and cpuType=X86) and (3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-x86_64-2008plus-{version}.zip (ZIP)
  (os=Windows and bitSize=B64 and cpuType=X86) and (3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-x86_64-{version}.zip (ZIP)
  (os=Windows and bitSize=B32 and cpuType=X86) and (3.5.5 or 3.3.1 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/win32/mongodb-win32-i386-{version}.zip (ZIP)
(os=OS_X)
  (os=OS_X and bitSize=B64 and cpuType=ARM) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1)
    url=/osx/mongodb-macos-arm64-{version}.tgz (TGZ(DEV))
  (os=OS_X and bitSize=B64 and cpuType=ARM) and (7.0.0 or 6.0.0-6.0.9)
    url=/osx/mongodb-macos-arm64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
    url=/osx/mongodb-macos-x86_64-{version}.tgz (TGZ(DEV))
  (os=OS_X and bitSize=B64) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3)
    url=/osx/mongodb-macos-x86_64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.4-3.0.15)
    url=/osx/mongodb-osx-ssl-x86_64-{version}.tgz (TGZ)
  (os=OS_X and bitSize=B64) and (3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/osx/mongodb-osx-x86_64-{version}.tgz (TGZ)
(os=Linux)
  (os=Linux and (version is any of Ubuntu_16_04, Ubuntu_16_10, Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1)
      url=/linux/mongodb-linux-aarch64-ubuntu2204-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0 or 6.0.4-6.0.9)
      url=/linux/mongodb-linux-aarch64-ubuntu2204-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1)
      url=/linux/mongodb-linux-x86_64-ubuntu2204-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0 or 6.0.4-6.0.9)
      url=/linux/mongodb-linux-x86_64-ubuntu2204-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-aarch64-ubuntu2004-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23)
      url=/linux/mongodb-linux-aarch64-ubuntu2004-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-ubuntu2004-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23)
      url=/linux/mongodb-linux-x86_64-ubuntu2004-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0-rc2 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-aarch64-ubuntu1804-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3)
      url=/linux/mongodb-linux-aarch64-ubuntu1804-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (7.0.0-rc2 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-ubuntu1804-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3 or 4.0.1-4.0.28 or 3.6.20-3.6.23)
      url=/linux/mongodb-linux-x86_64-ubuntu1804-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of Ubuntu_16_04, Ubuntu_16_10, Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7)
      url=/linux/mongodb-linux-arm64-ubuntu1604-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_16_04, Ubuntu_16_10, Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-ubuntu1604-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of Ubuntu_16_04, Ubuntu_16_10, Ubuntu_18_04, Ubuntu_18_10, Ubuntu_19_04, Ubuntu_19_10, Ubuntu_20_04, Ubuntu_20_10, Ubuntu_21_04, Ubuntu_21_10, Ubuntu_22_04, Ubuntu_22_10, Ubuntu_23_04, Ubuntu_23_10)) and (4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.7-3.2.22)
      url=/linux/mongodb-linux-x86_64-ubuntu1604-{version}.tgz (TGZ)
  (os=Linux and (version is any of LINUX_MINT_19_0, LINUX_MINT_19_1, LINUX_MINT_19_2, LINUX_MINT_19_3, LINUX_MINT_20_0, LINUX_MINT_20_1, LINUX_MINT_20_2, LINUX_MINT_20_3, LINUX_MINT_21_0, LINUX_MINT_21_1, LINUX_MINT_21_2, LINUX_MINT_21_3))
    use Ubuntu_18_04 for LINUX_MINT_19_0, LINUX_MINT_19_1, LINUX_MINT_19_2, LINUX_MINT_19_3 and Ubuntu_20_04 for LINUX_MINT_20_0, LINUX_MINT_20_1, LINUX_MINT_20_2, LINUX_MINT_20_3 and Ubuntu_22_04 for LINUX_MINT_21_0, LINUX_MINT_21_1, LINUX_MINT_21_2, LINUX_MINT_21_3
  (os=Linux and (version is any of POP_OS_22_4))
    use Ubuntu_22_04 for POP_OS_22_4
  (os=Linux and (version is any of DEBIAN_9, DEBIAN_10, DEBIAN_11, DEBIAN_12))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_11, DEBIAN_12)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1)
      url=/linux/mongodb-linux-x86_64-debian11-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_11, DEBIAN_12)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.8-5.0.20)
      url=/linux/mongodb-linux-x86_64-debian11-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_10, DEBIAN_11, DEBIAN_12)) and (7.0.0-rc2 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-debian10-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_10, DEBIAN_11, DEBIAN_12)) and (6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.1-4.2.3)
      url=/linux/mongodb-linux-x86_64-debian10-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_9, DEBIAN_10, DEBIAN_11, DEBIAN_12)) and (5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-debian92-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_9, DEBIAN_10, DEBIAN_11, DEBIAN_12)) and (5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.5-3.6.23)
      url=/linux/mongodb-linux-x86_64-debian92-{version}.tgz (TGZ)
  (os=Linux and (version is any of CentOS_6, CentOS_7, CentOS_8, CentOS_9, Redhat_6, Redhat_7, Redhat_8, Redhat_9, Oracle_6, Oracle_7, Oracle_8, Oracle_9, Fedora_38))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 6.0.9-rc1)
      url=/linux/mongodb-linux-aarch64-rhel90-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0 or 6.0.7-6.0.9)
      url=/linux/mongodb-linux-aarch64-rhel90-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1)
      url=/linux/mongodb-linux-x86_64-rhel90-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0 or 6.0.4-6.0.9)
      url=/linux/mongodb-linux-x86_64-rhel90-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-aarch64-rhel82-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.4-4.4.23)
      url=/linux/mongodb-linux-aarch64-rhel82-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-rhel80-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.1-4.2.3 or 4.0.14-4.0.28 or 3.6.17-3.6.23 or 3.4.24)
      url=/linux/mongodb-linux-x86_64-rhel80-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_7, Redhat_7, Oracle_7, CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-rhel70-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_7, Redhat_7, Oracle_7, CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-rhel70-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_6, Redhat_6, Oracle_6, CentOS_7, Redhat_7, Oracle_7, CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-rhel62-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of CentOS_6, Redhat_6, Oracle_6, CentOS_7, Redhat_7, Oracle_7, CentOS_8, Redhat_8, Oracle_8, CentOS_9, Redhat_9, Oracle_9, Fedora_38)) and (4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-rhel62-{version}.tgz (TGZ)
  (os=Linux and (version is any of AmazonLinux, AmazonLinux2, AmazonLinux2023))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of AmazonLinux2023)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10)
      url=/linux/mongodb-linux-aarch64-amazon2023-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of AmazonLinux2023)) and (7.0.0)
      url=/linux/mongodb-linux-aarch64-amazon2023-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux2023)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10)
      url=/linux/mongodb-linux-x86_64-amazon2023-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux2023)) and (7.0.0)
      url=/linux/mongodb-linux-x86_64-amazon2023-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of AmazonLinux2)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-aarch64-amazon2-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=ARM and (version is any of AmazonLinux2)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.4-4.4.23 or 4.2.13-4.2.24)
      url=/linux/mongodb-linux-aarch64-amazon2-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux2)) and (7.0.0-rc8 or 7.0.0-rc2 or 7.0.0-rc10 or 7.0.0-rc1 or 6.3.1-6.3.2 or 6.0.9-rc1 or 5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-amazon2-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux2)) and (7.0.0 or 6.0.0-6.0.9 or 5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.22-3.6.23)
      url=/linux/mongodb-linux-x86_64-amazon2-{version}.tgz (TGZ)
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux)) and (5.0.20-rc1 or 4.4.24-rc0)
      url=/linux/mongodb-linux-x86_64-amazon-{version}.tgz (TGZ(DEV))
    (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of AmazonLinux)) and (5.0.0-5.0.20 or 4.4.0-4.4.23 or 4.2.5-4.2.24 or 4.2.0-4.2.3 or 4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.2.0-3.2.22 or 3.0.0-3.0.15)
      url=/linux/mongodb-linux-x86_64-amazon-{version}.tgz (TGZ)
  (os=Linux)
    (os=Linux and bitSize=B64 and cpuType=X86) and (4.0.0-4.0.28 or 3.6.0-3.6.23 or 3.5.5 or 3.4.9-3.4.24 or 3.4.0-3.4.7 or 3.3.1 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
      url=/linux/mongodb-linux-x86_64-{version}.tgz (TGZ)
    (os=Linux and bitSize=B32 and cpuType=X86) and (3.5.5 or 3.3.1 or 3.2.0-3.2.22 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
      url=/linux/mongodb-linux-i686-{version}.tgz (TGZ)
  (os=Linux)
    fallback to Ubuntu_20_04
(os=Solaris)
  (os=Solaris and bitSize=B64 and cpuType=X86) and (3.5.5 or 3.4.0-3.4.5 or 3.3.1 or 3.2.0-3.2.14 or 3.0.0-3.0.15 or 2.6.0-2.6.12)
    url=/sunos5/mongodb-sunos5-x86_64-{version}.tgz (TGZ)

        at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.lambda$packageFor$0(PlatformPackageResolver.java:63)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at de.flapdoodle.embed.mongo.packageresolver.PlatformPackageResolver.packageFor(PlatformPackageResolver.java:57)
        at de.flapdoodle.embed.mongo.transitions.PackageOfCommandDistribution.packageOf(PackageOfCommandDistribution.java:53)
        at de.flapdoodle.embed.mongo.transitions.PackageOfCommandDistribution.result(PackageOfCommandDistribution.java:93)
        at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:58)
        at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:46)
        at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:176)
        ... 46 more
```

```
$ lsb_release -a

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux trixie/sid
Release:        n/a
Codename:       trixie
```

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by michaelmosmann** [comment]
@Marthym .. there is a new release for that:)
