### ISSUE TITLE
How define the download URL when using Spring Boot 3.x ?

### ISSUE THREAD

**Issue by maecval** [flapdoodle-oss/de.flapdoodle.embed.mongo#501]
Hi all,

Up until Spring Boot 2.7 we were able to configure the download URL to be used by Flapdoodle by the following configuration class (note `downloadPath(distribution -> "https://our-own-url-to-be-used.../org/mongodb/")`):
```
@Configuration
public class FlapDoodleConfig {

    Command command = Command.MongoD;

    @Bean
    public RuntimeConfig embeddedMongoRuntimeConfig() {
        Logger logger = LoggerFactory.getLogger(getClass().getPackage().getName() + ".EmbeddedMongo");
        ProcessOutput processOutput = new ProcessOutput(
                Processors.logTo(logger, Slf4jLevel.INFO),
                Processors.logTo(logger, Slf4jLevel.ERROR), Processors.named(
                "[console>]", Processors.logTo(logger, Slf4jLevel.DEBUG)));
        return Defaults.runtimeConfigFor(command, logger)
                .artifactStore(Defaults.extractedArtifactStoreFor(command)
                        .withDownloadConfig(Defaults.downloadConfigFor(command)
                                .downloadPath(distribution -> "https://our-own-url-to-be-used.../org/mongodb/")
                                .progressListener(new Slf4jProgressListener(logger))
                                .userAgent("curl/7.74.0")
                                .build()))
                .processOutput(processOutput)
                .build();
    }
}
```

We are now upgrading to Spring Boot 3.1 and struggle with a configuration when using the following flapdoodle libraries:
```
        ...
        <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo</artifactId>
            <version>4.12.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo.spring3x</artifactId>
            <version>4.12.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>
        ...
```

Can you please support on how to create a configuration class in Spring Boot 3.1 where we can define the download URL?
In our environment we are forced to download through our Artifactory instance.

Kind regards,
Valentin

P.S. part of the stacktrace:
```
Caused by: java.lang.IllegalStateException: could not download https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz (if this issue persist, you can download it manually to /home/taamava0/.embedmongo/archives/https-fastdl-mongodb-org/56cb3d10404e5b9df5358ac4ee83efcb/linuxmongodb-linux-x86-64-ubuntu2004-4-4-0-tgz/12ead5cea005d414a7bf81ab08ed4305e8f04ebdc9ec4d962dd7fb98e3ffce17/archive.tgz)
	at de.flapdoodle.embed.process.transitions.DownloadPackage.lambda$result$4(DownloadPackage.java:154)
	at de.flapdoodle.types.ThrowingRunnable.lambda$mapException$0(ThrowingRunnable.java:33)
	at de.flapdoodle.embed.process.transitions.DownloadPackage.result(DownloadPackage.java:156)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:58)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:46)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:180)
	... 157 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2057)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2052)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2051)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at de.flapdoodle.net.URLConnections.downloadAndCopy(URLConnections.java:112)
	at de.flapdoodle.net.URLConnections.downloadIntoTempFile(URLConnections.java:93)
``

**Comment by michaelmosmann** [comment]
@maecval this is how you can customize the mongod starter with spring:

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/HowTo.md#customize-mongod

and here you can see how to customize the download basepath:

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/docs/Customizations.md#customize-download-url

**Comment by maecval** [comment]
Hi @michaelmosmann 
Thanks a lot for this quick reply !
Right after creating this request I also found some of the docs you mentioned and tried with the following Spring configuration class:
```
import de.flapdoodle.embed.mongo.transitions.Mongod;
import de.flapdoodle.embed.mongo.types.DistributionBaseUrl;
import de.flapdoodle.reverse.Transition;
import de.flapdoodle.reverse.transitions.Start;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@Slf4j
public class FlapDoodleConfig {

    private static final String DOWNLOAD_URL =
            "https://artifactory............./org/mongodb";

    @Bean
    public Mongod mongod() {
        log.info("Creating Mongod with download URL={}", DOWNLOAD_URL);
        final Mongod mongod = new Mongod() {
            @Override
            public Transition<DistributionBaseUrl> distributionBaseUrl() {
                return Start.to(DistributionBaseUrl.class)
                        .initializedWith(DistributionBaseUrl.of(DOWNLOAD_URL));
            }
        };
        return mongod;
    }
}
```
It was able to successfully download the `mongodb-linux-x86_64-debian10-4.4.26.tgz` but failed later on when trying to start it.

I noticed that in case of a successful start it gets downloaded and started by `EmbeddedMongo`.
But with the configuration above (defining the download URL) the logs are different and _do not_ mention `EmbeddedMongo`.
Please find sample logs hereafter:

**Success case:**
```
18:41:14  2023-12-19 18:41:13.928 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.SyncClientServerFactory] [main] sync server factory
18:41:15  2023-12-19 18:41:14.733 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.EmbeddedMongo] [main] download https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.4.26.tgz : starting...
...
18:41:15  2023-12-19 18:41:15.584 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.EmbeddedMongo] [main] download https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.4.26.tgz : finished
18:41:16  2023-12-19 18:41:16.619 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.EmbeddedMongo] [Thread-3] {"t":{"$date":"2023-12-19T18:41:16.619+01:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
18:41:16  2023-12-19 18:41:16.621 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.EmbeddedMongo] [Thread-3] {"t":{"$date":"2023-12-19T18:41:16.621+01:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
18:41:16  2023-12-19 18:41:16.622 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.EmbeddedMongo] [Thread-3] {"t":{"$date":"2023-12-19T18:41:16.622+01:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":
...
...
18:41:26  2023-12-19 18:41:26.140 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.EmbeddedMongo] [Thread-13] {"t":{"$date":"2023-12-19T18:41:26.140+01:00"},"s":"I",  "c":"STORAGE",  "id":20320,   "ctx":"LogicalSessionCacheRefresh","msg":"createCollection","attr":{"namespace":"config.system.sessions","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"8c831e3a-0ca4-45e3-b456-5042804a8b0b"}},"options":{}}}
18:41:26  2023-12-19 18:41:26.190 INFO  traceId= spanId= parentSpanId= reqId= clientId= [o.m.d.client] [main] MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync|spring-boot", "version": "4.9.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "6.2.0-34-generic"}, "platform": "Java/BellSoft/17.0.6+10-LTS"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=null, streamFactoryFactory=null, commandListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener@65468c7d], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@51c0bdf9, com.mongodb.Jep395RecordCodecProvider@16335685]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[localhost:41973], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener@504d4fb5], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=JAVA_LEGACY, serverApi=null, autoEncryptionSettings=null, contextProvider=null}
18:41:26  2023-12-19 18:41:26.191 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.EmbeddedMongo] [Thread-13] {"t":{"$date":"2023-12-19T18:41:26.190+01:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:49096","connectionId":1,"connectionCount":1}}
...
...
```

**Failure case with download URL configuration:**
```
21:09:51  2023-12-19 21:09:50.944 INFO  traceId= spanId= parentSpanId= reqId= clientId= [d.f.e.m.s.a.SyncClientServerFactory] [main] sync server factory
21:09:51  download https://artifactory......................../mongodb/linux/mongodb-linux-x86_64-debian10-4.4.26.tgz START
...
21:10:00  download https://artifactory......................../mongodb/linux/mongodb-linux-x86_64-debian10-4.4.26.tgz DONE
21:10:01  [mongod output]{"t":{"$date":"2023-12-19T21:10:01.691+01:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
21:10:01  [mongod output] {"t":{"$date":"2023-12-19T21:10:01.695+01:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
21:10:01  [mongod output] {"t":{"$date":"2023-12-19T21:10:01.695+01:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1978023,"port":35807,"dbPath":"/tmp/temp--c7dc3430-88bb-495c-9331-423b274b34ef/mongod-database13336787347798374452","architecture":"64-bit","host":"874751d3-79b3-47ef-5ad1-a8d6"}}
...
...
21:10:02  [mongod output] {"t":{"$date":"2023-12-19T21:10:02.388+01:00"},"s":"I",  "c":"INDEX",    "id":20345,   "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"lsidTTLIndex","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
21:10:02  [mongod output] 2023-12-19 21:10:02.802 INFO  traceId= spanId= parentSpanId= reqId= clientId= [o.m.d.cluster] [cluster-ClusterId{value='6581f89a4940d13f4c596403', description='null'}-localhost:41007] Exception in monitor thread while connecting to server localhost:41007
21:10:02  com.mongodb.MongoSocketOpenException: Exception opening socket
21:10:02  	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:73)
21:10:02  	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:204)
21:10:02  	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:199)
21:10:02  	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:159)
21:10:02  	at java.base/java.lang.Thread.run(Thread.java:833)
21:10:02  Caused by: java.net.ConnectException: Connection refused
21:10:02  	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
21:10:02  	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
21:10:02  	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
21:10:02  	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
21:10:02  	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
21:10:02  	at java.base/java.net.Socket.connect(Socket.java:633)
21:10:02  	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:107)
21:10:02  	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:82)
21:10:02  	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:68)
21:10:02  	... 4 common frames omitted
21:10:03  2023-12-19 21:10:02.812 INFO  traceId= spanId= parentSpanId= reqId= clientId= [o.m.d.client] [main] MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync|spring-boot", "version": "4.9.1"}, "os": {"type": "Linux", "name": "Linux", "architecture": "amd64", "version": "6.2.0-34-generic"}, "platform": "Java/BellSoft/17.0.6+10-LTS"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=null, streamFactoryFactory=null, commandListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener@26542c47], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@41e43c90, com.mongodb.Jep395RecordCodecProvider@7d474824]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[localhost:41007], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='30000 ms', localThreshold='30000 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, sendBufferSize=0}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, sendBufferSize=0}, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener@7f75f630], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=JAVA_LEGACY, serverApi=null, autoEncryptionSettings=null, contextProvider=null}
21:10:04  2023-12-19 21:10:04.067 INFO  traceId= spanId= parentSpanId= reqId= clientId= [c.s.b.d.e.MongoDataInitializer] [main] Setting database
21:10:04  2023-12-19 21:10:04.119 INFO  traceId= spanId= parentSpanId= reqId= clientId= [o.m.d.cluster] [main] Cluster description not yet available. Waiting for 30000 ms before timing out
21:10:37  2023-12-19 21:10:34.121 WARN  traceId= spanId= parentSpanId= reqId= clientId= [o.s.w.c.s.GenericWebApplicationContext] [main] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongoDataInitializer': Invocation of init method failed
21:10:37  {"t":{"$date":"2023-12-19T21:10:34.127+01:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"127.0.0.1:34866","connectionId":1,"connectionCount":1}}
21:10:37  [mongod output] {"t":{"$date":"2023-12-19T21:10:34.127+01:00"},"s":"I",  "c":"COMMAND",  "id":20475,   "ctx":"conn1","msg":"Terminating via shutdown command","attr":{"cmdObj":{"shutdown":1,"force":true,"timeoutSecs":0,"$db":"admin"}}}
21:10:37  [mongod output] {"t":{"$date":"2023-12-19T21:10:34.127+01:00"},"s":"I",  "c":"COMMAND",  "id":4784901, "ctx":"conn1","msg":"Shutting down the MirrorMaestro"}
```


Looks as if the configuration is not (yet) correct :-(.

**Can you please help us some more based on these logs?**

Kind regards,
Valentin

**Comment by michaelmosmann** [comment]
@maecval .. ah.. sorry for that confusion.. the easiest way to customize your mongod-server-stuff WITH spring is with the builder-pattern .. first code snippet here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.spring/blob/main/HowTo.md#customize-mongod 

.. because i try to emulate existing spring behavior where the server port etc comes from some spring properties .. so we can not just create a new configuration. As all this stuff is immutable, you have to make a copy if you want to apply your changes.. this is done with the builder pattern.

**Comment by maecval** [comment]
@michaelmosmann 
Thanks once more for replying so fast !
In the meanwhile I figured out a working configuration. I looked at some more docs and combined the described approaches.

Here's my config class:
```
@Configuration
public class FlapDoodleConfig {

    private static final String DOWNLOAD_URL =
            "https://artifactory.................../org/mongodb";

    @Bean
    BeanPostProcessor customizeMongod() {
        return TypedBeanPostProcessor.applyBeforeInitialization(Mongod.class, src -> {
            return Mongod.builder()
                    .from(src)
                    .distributionBaseUrl(Start.to(DistributionBaseUrl.class)
                            .initializedWith(DistributionBaseUrl.of(DOWNLOAD_URL)))
                    .build();
        });
    }

}
```

Once more:
**Vielen Dank für deine Hilfe !**
Frohe Festtage wünscht
Valentin

**Comment by michaelmosmann** [comment]
@maecval gleichfalls:)

**Comment by maecval** [comment]
Thanks for your support!
It works like a dream :-)

**Comment by sparmboy** [comment]
If anyone is trying to download from a path that doesn't end in `/windows` or `/win32` etc this is how to override the _**entire**_ URL (took me a whole afternoon to figure out this convoluted setup - be nice if there was some documentation on this)

```
package com.rbs.ee.forms;

import de.flapdoodle.embed.mongo.spring.autoconfigure.TypedBeanPostProcessor;
import de.flapdoodle.embed.mongo.transitions.ImmutablePackageOfCommandDistribution;
import de.flapdoodle.embed.mongo.transitions.Mongod;
import de.flapdoodle.embed.mongo.types.DistributionBaseUrl;
import de.flapdoodle.embed.process.config.store.FileSet;
import de.flapdoodle.embed.process.config.store.FileType;
import de.flapdoodle.embed.process.config.store.Package;
import de.flapdoodle.embed.process.distribution.ArchiveType;
import de.flapdoodle.reverse.transitions.Start;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@Slf4j
public class FlapDoodleConfig {

    public final String DOWNLOAD_URL = "https://myserver.com/30-01-25/mongodb-windows-x86_64-enterprise-6.0.20.zip";

    @Bean
    BeanPostProcessor customizeMongod() {
        return TypedBeanPostProcessor.applyBeforeInitialization(Mongod.class, src -> Mongod.builder()
                .from(src)
                .packageOfDistribution(
                        ImmutablePackageOfCommandDistribution.withDefaults()
                                .withCommandPackageResolver(command -> distribution -> Package.builder()
                                        .archiveType(ArchiveType.ZIP)
                                        .fileSet(FileSet.builder().addEntry(FileType.Executable, "mongod.exe", ".*mongod.exe").build())
                                        .url(DOWNLOAD_URL)
                                        .build())
                )
                .distributionBaseUrl(Start.to(DistributionBaseUrl.class)
                        .initializedWith(DistributionBaseUrl.of(""))
                )
                .build());
    }
}

```
