### ISSUE TITLE
Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' (GenericFeatureAwareVersion{4.13.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04}

### ISSUE THREAD

**Issue by sleski** [flapdoodle-oss/de.flapdoodle.embed.mongo#518]
I work on update my Spring-Boot (2.7.18) service from jdk 17 to jdk 21.
Problem is on CI (Jenkins), with jdk 17 Jenkins was using image: maven:3.8.5-eclipse-temurin-17-focal (https://hub.docker.com/layers/library/maven/3.8.5-eclipse-temurin-17-focal/images/sha256-f7034e7f1a1415126dc5b5e7c5c530b093c9dffb93247b38cc88273fe1c7963b?context=explore) and with jdk 21 - 3.9.6-eclipse-temurin-21-jammy (https://hub.docker.com/layers/library/maven/3.9.6-eclipse-temurin-21-jammy/images/sha256-6a1d7ebcda52c05b9a8f9d418dcfe8cc95fb07eedee14a54a5dce47329d6d40b?context=explore)

With jdk 17:
```
<dependency>
        <groupId>de.flapdoodle.embed</groupId>
        <artifactId>de.flapdoodle.embed.mongo</artifactId>
        <version>3.4.11</version>
        <scope>test</scope>
 </dependency>
```

Now I added:
```
<dependency>
        <groupId>de.flapdoodle.embed</groupId>
        <artifactId>de.flapdoodle.embed.mongo.spring27x</artifactId>
        <version>4.13.0</version>
         <scope>test</scope>
</dependency>
```
But still see in the log:
```
10:50:26  2024-05-07 08:50:26.459  WARN 782 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'myBean' defined in com.example.MyBean defined in @EnableMongoRepositories declared on MongoConfiguration: Cannot resolve reference to bean 'mongoTemplate' while setting bean property 'mongoOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is java.lang.IllegalArgumentException: could not resolve package for GenericFeatureAwareVersion{4.13.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04}
```
Ubuntu version:
```
12:43:36  + cat /etc/os-release
12:43:36  PRETTY_NAME="Ubuntu 22.04.4 LTS"
12:43:36  NAME="Ubuntu"
12:43:36  VERSION_ID="22.04"
12:43:36  VERSION="22.04.4 LTS (Jammy Jellyfish)"
12:43:36  VERSION_CODENAME=jammy
12:43:36  ID=ubuntu
12:43:36  ID_LIKE=debian
12:43:36  HOME_URL="https://www.ubuntu.com/"
12:43:36  SUPPORT_URL="https://help.ubuntu.com/"
12:43:36  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
12:43:36  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
12:43:36  UBUNTU_CODENAME=jammy
```
I was checking other issues, but did not find the same. Any info how I can solve the problem, or where may I do a mistake?

**Comment by Storje** [comment]
Same kind of issue on my side with 
```xml
      <dependency>
        <groupId>de.flapdoodle.embed</groupId>
        <artifactId>de.flapdoodle.embed.mongo.spring3x</artifactId>
        <version>4.13.0</version>
        <scope>test</scope>
      </dependency>
```

 I tried with following images : maven:3-eclipse-temurin-21-jammy , maven:3.9-amazoncorretto-21-debian, maven:3.9.6-amazoncorretto-21

But the following  exception raised :
```stackstrace
Cannot resolve reference to bean 'mongoTemplate' while setting bean property 'mongoOperations'
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1355)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1192)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1454)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:553)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
	... 17 more
	Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0: Error creating bean with name 'reactiveClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$ReactiveClientServerWrapperConfig.class]: 'long org.apache.commons.io.IOUtils.skip(java.io.InputStream, long, java.util.function.Supplier)'
	Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'reactiveClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$ReactiveClientServerWrapperConfig.class]: 'long org.apache.commons.io.IOUtils.skip(java.io.InputStream, long, java.util.function.Supplier)'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904) ~[spring-beans-6.1.6.jar:6.1.6]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782) ~[spring-beans-6.1.6.jar:6.1.6]
	... 135 common frames omitted
Caused by: java.lang.NoSuchMethodError: 'long org.apache.commons.io.IOUtils.skip(java.io.InputStream, long, java.util.function.Supplier)'
	at org.apache.commons.compress.utils.IOUtils.skip(IOUtils.java:282) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:409) ~[commons-compress-1.26.1.jar:1.26.1]
	at de.flapdoodle.embed.process.archives.AbstractTarAdapter$TarArchiveWrapper.getNextEntry(AbstractTarAdapter.java:44) ~[de.flapdoodle.embed.process-4.11.0.jar:na]
	at de.flapdoodle.embed.process.archives.AbstractExtractFileSet.extract(AbstractExtractFileSet.java:58) ~[de.flapdoodle.embed.process-4.11.0.jar:na]
	at de.flapdoodle.embed.process.transitions.ExtractPackage.lambda$extractedFileSet$1(ExtractPackage.java:114) ~[de.flapdoodle.embed.process-4.11.0.jar:na]
	at de.flapdoodle.types.ThrowingSupplier.lambda$mapException$0(ThrowingSupplier.java:30) ~[de.flapdoodle.java8-1.4.2.jar:na]
	at de.flapdoodle.types.Try.get(Try.java:42) ~[de.flapdoodle.java8-1.4.2.jar:na]
	at de.flapdoodle.embed.process.transitions.ExtractPackage.extractedFileSet(ExtractPackage.java:114) ~[de.flapdoodle.embed.process-4.11.0.jar:na]
	at de.flapdoodle.embed.process.transitions.ExtractPackage.result(ExtractPackage.java:102) ~[de.flapdoodle.embed.process-4.11.0.jar:na]
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:58) ~[de.flapdoodle.reverse-1.7.2.jar:na]
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:46) ~[de.flapdoodle.reverse-1.7.2.jar:na]
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:180) ~[de.flapdoodle.reverse-1.7.2.jar:na]
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69) ~[de.flapdoodle.reverse-1.7.2.jar:na]
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:65) ~[de.flapdoodle.reverse-1.7.2.jar:na]
	at de.flapdoodle.embed.mongo.spring.autoconfigure.MongodWrapper.start(MongodWrapper.java:45) ~[de.flapdoodle.embed.mongo.spring3x-4.13.0.jar:na]
```

**Comment by michaelmosmann** [comment]
@sleski i guess there is no matching mongodb version for ubuntu22 (nested exception is java.lang.IllegalArgumentException: could not resolve package for GenericFeatureAwareVersion{4.13.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04})

you can find any known version in this generated overview: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/test/resources/de/flapdoodle/embed/mongo/packageresolver/explainedSnapshot.txt .. AFAIK is a 4.4.x version the latest 4.x.x version you can get.

**Comment by michaelmosmann** [comment]
@Storje .. from an other issue my best guess is a version miss match for commons.io between your project setup an the one which this project uses by using commons-compress .. (java.lang.NoSuchMethodError: 'long org.apache.commons.io.IOUtils.skip)

**Comment by sleski** [comment]
Thank you for your answer. 

I added version 4.4.0:
```
        <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo.spring27x</artifactId>
            <version>4.4.0</version>
            <scope>test</scope>
        </dependency>
```

And now can see:

```
10:39:34  2024-05-09 08:39:33.798  INFO 679 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Download GenericFeatureAwareVersion{4.4.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04} : finished
10:39:34  2024-05-09 08:39:33.879  INFO 679 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz : starting...
10:39:34  2024-05-09 08:39:34.845  INFO 679 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz : extract mongodb-linux-x86_64-ubuntu2004-4.4.0/bin/mongod
10:39:34  2024-05-09 08:39:34.845  INFO 679 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz : nothing left
10:39:34  2024-05-09 08:39:34.846  INFO 679 --- [           main] o.s.b.a.mongo.embedded.EmbeddedMongo     : Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz : finished
10:39:34  java.lang.NoSuchFieldException: handle
10:39:34  	at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
```
and below:

`10:39:34  2024-05-09 08:39:34.950 ERROR 679 --- [       Thread-2] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-70929bfd-26b2-40c9-bc82-d78a97e0429aextractmongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
`
and more:

```
10:39:57  2024-05-09 08:39:55.283 ERROR 679 --- [       Thread-5] o.s.b.a.mongo.embedded.EmbeddedMongo     : /tmp/extract-abcf3b4c-8808-4585-b0d1-ffe7b4382aecextractmongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
10:39:57  2024-05-09 08:39:55.284  WARN 679 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'archiverRetryRepository' defined in com.example.ArchiverRetryRepository defined in @EnableMongoRepositories declared on MongoConfiguration: Cannot resolve reference to bean 'mongoTemplate' while setting bean property 'mongoOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Could not start process: <EOF>
```

Could it be related to 2 dependencies for  `EmbeddedMongoAutoConfiguration`?
![20240509_111423](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/assets/1952501/ffeec929-fdbe-4c2e-9f91-b2459e5d4bdd)

**Comment by michaelmosmann** [comment]
@sleski the version in the pom is NOT the version of the mongodb.. there must be some spring property where you set the mongodb version.. not the library version of flapdoodle.. (flapdoodle version: use the latest spring adapter version, mongodb version: use what you need .. here you might use 4.4.x? or newer (should match your deployment))

**Comment by Storje** [comment]
@michaelmosmann Thanks for your message, but after handling this apache commons libs mismatch , the following exception raised ( libcrypto.so.1.1: cannot open shared object file ) :

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0: Error creating bean with name 'reactiveClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$ReactiveClientServerWrapperConfig.class]: rollback after error on transition to State(RunningMongodProcess), successful reached:
  State(ExtractedFileSet)=ExtractedFileSet{baseDir=/root/.embedmongo/fileSets/49428e5e90aa8c60f114086713b28db8517cdd5e25c428f172ea2c7af7e224d5, executable=/root/.embedmongo/fileSets/49428e5e90aa8c60f114086713b28db8517cdd5e25c428f172ea2c7af7e224d5/mongod, libraryFiles=[]},
  State(Archive)=Archive(/root/.embedmongo/archives/https-fastdl-mongodb-org/56cb3d10404e5b9df5358ac4ee83efcb/linuxmongodb-linux-x86-64-ubuntu2004-4-4-0-tgz/12ead5cea005d414a7bf81ab08ed4305e8f04ebdc9ec4d962dd7fb98e3ffce17/archive.tgz),
  State(DownloadCache)=de.flapdoodle.embed.process.store.LocalDownloadCache@38b88037,
  State(Package)=Package{archiveType=TGZ, fileSet=FileSet{entries=[Entry{type=Executable, destination=mongod, uncompiledMatchingPattern=UncompiledPattern{regex=.*mongod, flags=2}}]}, url=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz},
  State(ExtractedFileSetStore)=de.flapdoodle.embed.process.store.ContentHashExtractedFileSetStore@122c8b64,
  State(ProcessArguments)=ProcessArguments([--dbpath, /tmp/temp--5ab6fe9d-ae62-40ab-991f-ea9f18a70c12/mongod-database9167787402650913380, --noauth, --nojournal, --port, 34085, --bind_ip, 127.0.0.1, --syncdelay=0]),
  State(ProcessWorkingDir)=ProcessWorkingDir(/tmp/temp--5ab6fe9d-ae62-40ab-991f-ea9f18a70c12/workingDir17082343275497019865),
  State(Distribution)=GenericFeatureAwareVersion{4.4.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04},
  State(SupportConfig)=SupportConfig{name=mongod, supportUrl=https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues, messageOnException=de.flapdoodle.embed.mongo.transitions.ProcessDefaults$$Lambda/0x00007ffa745f8fb8@10743711},
  State(Name)=Name(mongod),
  State(PersistentDir)=ImmutablePersistentDir(/root/.embedmongo),
  State(DatabaseDir)=DatabaseDir(/tmp/temp--5ab6fe9d-ae62-40ab-991f-ea9f18a70c12/mongod-database9167787402650913380),
  State(TempDir)=ImmutableTempDir(/tmp/temp--5ab6fe9d-ae62-40ab-991f-ea9f18a70c12),
  State(DistributionBaseUrl)=DistributionBaseUrl(https://fastdl.mongodb.org),
  State(Platform)=Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_22_04},

Caused by: java.lang.RuntimeException: Could not start process: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$null$1(RunningMongoProcess.java:179)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
```

**Comment by michaelmosmann** [comment]
@Storje yes.. unless you can pull this lib into this linux version you might use a newer version of mongodb..

**Comment by Storje** [comment]
@michaelmosmann Unfortunately I'm stuck with this Mongo version :/ So, I changed the base image to Ubuntu Focal, but still an error (libcurl.so.4: cannot open shared object file) :

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0: Error creating bean with name 'reactiveClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$ReactiveClientServerWrapperConfig.class]: rollback after error on transition to State(RunningMongodProcess), successful reached:
  State(ExtractedFileSet)=ExtractedFileSet{baseDir=/root/.embedmongo/fileSets/49428e5e90aa8c60f114086713b28db8517cdd5e25c428f172ea2c7af7e224d5, executable=/root/.embedmongo/fileSets/49428e5e90aa8c60f114086713b28db8517cdd5e25c428f172ea2c7af7e224d5/mongod, libraryFiles=[]},
  State(Archive)=Archive(/root/.embedmongo/archives/https-fastdl-mongodb-org/56cb3d10404e5b9df5358ac4ee83efcb/linuxmongodb-linux-x86-64-ubuntu2004-4-4-0-tgz/12ead5cea005d414a7bf81ab08ed4305e8f04ebdc9ec4d962dd7fb98e3ffce17/archive.tgz),
  State(DownloadCache)=de.flapdoodle.embed.process.store.LocalDownloadCache@bc70176,
  State(Package)=Package{archiveType=TGZ, fileSet=FileSet{entries=[Entry{type=Executable, destination=mongod, uncompiledMatchingPattern=UncompiledPattern{regex=.*mongod, flags=2}}]}, url=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz},
  State(ExtractedFileSetStore)=de.flapdoodle.embed.process.store.ContentHashExtractedFileSetStore@eba64a9,
  State(ProcessArguments)=ProcessArguments([--dbpath, /tmp/temp--279a0d06-d55f-4981-b11d-6e5c7ce04a61/mongod-database12472033629878115147, --noauth, --nojournal, --port, 41567, --bind_ip, 127.0.0.1, --syncdelay=0]),
  State(ProcessWorkingDir)=ProcessWorkingDir(/tmp/temp--279a0d06-d55f-4981-b11d-6e5c7ce04a61/workingDir14710916568508443105),
  State(Distribution)=GenericFeatureAwareVersion{4.4.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_20_04},
  State(SupportConfig)=SupportConfig{name=mongod, supportUrl=https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues, messageOnException=de.flapdoodle.embed.mongo.transitions.ProcessDefaults$$Lambda/0x00007fab704331f8@53e1cd6b},
  State(Name)=Name(mongod),
  State(PersistentDir)=ImmutablePersistentDir(/root/.embedmongo),
  State(DatabaseDir)=DatabaseDir(/tmp/temp--279a0d06-d55f-4981-b11d-6e5c7ce04a61/mongod-database12472033629878115147),
  State(TempDir)=ImmutableTempDir(/tmp/temp--279a0d06-d55f-4981-b11d-6e5c7ce04a61),
  State(DistributionBaseUrl)=DistributionBaseUrl(https://fastdl.mongodb.org),
  State(Platform)=Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu, version=Ubuntu_20_04},

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1890)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1843)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 92 more
Caused by: java.lang.RuntimeException: Could not start process: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$null$1(RunningMongoProcess.java:179)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
```

**Comment by Storje** [comment]
After installing curl it's ok ...

**Comment by michaelmosmann** [comment]
@Storje ah.. interesting .. 

I did not see any upgrades for mongodb lately .. so i guess you should change to a newer version some day.

**Comment by michaelmosmann** [comment]
@chandni-navani this is a version mismatch for commons-compress between spring and flapdoodle.. you should use a commons-io dependency with works with the commons-compress dependency..

**Comment by chandni-navani** [comment]
> @chandni-navani this is a version mismatch for commons-compress between spring and flapdoodle.. you should use a commons-io dependency with works with the commons-compress dependency..

Thank you @michaelmosmann , that solved it!

**Comment by michaelmosmann** [comment]
.. i close this issue.. reopen if needed:)
