### ISSUE TITLE
Error raised when run springboottest  test in pipleline container when using “de.flapdoodle.embed.mongo”

### ISSUE THREAD

**Issue by willgss** [flapdoodle-oss/de.flapdoodle.embed.mongo#530]
I use “de.flapdoodle.embed.mongo” as embeded mongodb in my integration test with "@SpringBootTest"
The case is OK when i run it on my IDE with the command "mvn clean test", but when i run the case in the pipeline contained in the process of build, it always failed with the following error message:

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'prepareDatabase' defined in file [/__w/1/s/component-test/target/test-classes/com/futurmaster/tpm/util/PrepareDatabase.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0: Error creating bean with name 'syncClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$SyncClientServerWrapperConfig.class]: rollback after error on transition to State(RunningMongodProcess), successful reached:
  State(ExtractedFileSet)=ExtractedFileSet{baseDir=/home/vsts_azpcontainer/.embedmongo/fileSets/49428e5e90aa8c60f114086713b28db8517cdd5e25c428f172ea2c7af7e224d5, executable=/home/vsts_azpcontainer/.embedmongo/fileSets/49428e5e90aa8c60f114086713b28db8517cdd5e25c428f172ea2c7af7e224d5/mongod, libraryFiles=[]},
  State(Archive)=Archive(/home/vsts_azpcontainer/.embedmongo/archives/https-fastdl-mongodb-org/56cb3d10404e5b9df5358ac4ee83efcb/linuxmongodb-linux-x86-64-ubuntu2004-4-4-0-tgz/12ead5cea005d414a7bf81ab08ed4305e8f04ebdc9ec4d962dd7fb98e3ffce17/archive.tgz),
  State(DownloadCache)=de.flapdoodle.embed.process.store.LocalDownloadCache@2cd8310d,
  State(Package)=Package{archiveType=TGZ, fileSet=FileSet{entries=[Entry{type=Executable, destination=mongod, uncompiledMatchingPattern=UncompiledPattern{regex=.*mongod, flags=2}}]}, url=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-4.4.0.tgz},
  State(ExtractedFileSetStore)=de.flapdoodle.embed.process.store.ContentHashExtractedFileSetStore@170a9ea7,
  State(ProcessArguments)=ProcessArguments([--dbpath, /tmp/temp--e80595c0-f613-4769-94d9-e724bb992521/mongod-database9788155574469651818, --noauth, --nojournal, --port, 34059, --bind_ip, 127.0.0.1, --syncdelay=0]),
  State(ProcessWorkingDir)=ProcessWorkingDir(/tmp/temp--e80595c0-f613-4769-94d9-e724bb992521/workingDir1563659773221758669),
  State(Distribution)=GenericFeatureAwareVersion{4.4.0}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian, version=DEBIAN_12},
  State(SupportConfig)=SupportConfig{name=mongod, supportUrl=https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues, messageOnException=de.flapdoodle.embed.mongo.transitions.ProcessDefaults$$Lambda/0x00007f9120f0fcd0@bebbcbd},
  State(Name)=Name(mongod),
  State(PersistentDir)=ImmutablePersistentDir(/home/vsts_azpcontainer/.embedmongo),
  State(DatabaseDir)=DatabaseDir(/tmp/temp--e80595c0-f613-4769-94d9-e724bb992521/mongod-database9788155574469651818),
  State(TempDir)=ImmutableTempDir(/tmp/temp--e80595c0-f613-4769-94d9-e724bb992521),
  State(DistributionBaseUrl)=DistributionBaseUrl(https://fastdl.mongodb.org),
  State(Platform)=Platform{operatingSystem=Linux, architecture=X86_64, distribution=Debian, version=DEBIAN_12},
  State(ProcessConfig)=ProcessConfig{daemonProcess=false, stopTimeoutInMillis=5000},
  State(ProcessEnv)=ProcessEnv({}),
  State(ProcessOutput)=ProcessOutput{output=de.flapdoodle.embed.process.io.Slf4jStreamProcessor@25ba93bf, error=de.flapdoodle.embed.process.io.Slf4jStreamProcessor@69fe3c4c, commands=de.flapdoodle.embed.process.io.NamedOutputStreamProcessor@638d5340},
  State(SystemEnv)=SystemEnv({AGENT_OS=Linux, SYSTEM_STAGEDISPLAYNAME=__default, AGENT_RETAINDEFAULTENCODING=false, INPUT_CLASSFILTER=, BUILD_REQUESTEDFORID=9dedb684-9725-4208-8398-2845dc926630, AGENT_UPLOADTIMELINEATTACHMENTSTOBLOB=true, AGENT_HOMEDIRECTORY=/__a, VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT=true, SYSTEM_COLLECTIONID=cfa5d10a-136f-438e-8cf3-750800ce1405, PIPELINE_WORKSPACE=/__w/1, SYSTEM_TEAMFOUNDATIONSERVERURI=https://dev.azure.com/FuturMasterDev/, INPUT_TESTRUNTITLE=, BUILD_BUILDURI=vstfs:///Build/Build/295523, AGENT_UPLOADBUILDARTIFACTSTOBLOB=true, AZP_AGENT_CHECK_FOR_TASK_DEPRECATION=true, SYSTEM_TEAMFOUNDATIONCOLLECTIONURI=https://dev.azure.com/FuturMasterDev/, SYSTEM_TEAMPROJECT=FuturMaster, BUILD_SOURCEVERSION=d48f16af1f200a5b6b42643270d9af516f40d5b9, TASK_SKIPTRANSLATORFORCHECKOUT=False, MAVEN_CACHE_FOLDER=/__w/1/.m2/repository, AZP_75787_ENABLE_NEW_LOGIC=false, SYSTEM_PULLREQUEST_TARGETBRANCH=refs/heads/develop, MAVEN_CMD_LINE_ARGS=/root/.m2 -f /__w/1/s/pom.xml -U -Drevision=2.19.0-SNAPSHOT clean package org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar, AGENT_BUILDDIRECTORY=/__w/1, BUILD_QUEUEDBY=Microsoft.VisualStudio.Services.TFS, AGENT_ROOTDIRECTORY=/__w, AZP_AGENT_MOUNT_WORKSPACE=true, BUILD_SOURCEBRANCH=refs/pull/29121/merge, JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto, AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN=true, SYSTEM_SERVERTYPE=Hosted, SYSTEM_PULLREQUEST_SOURCECOMMITID=91b4799624d40aa4c9edf7d08c0c631826b80dc0, INPUT_CLASSFILESDIRECTORIES=, BUILD_QUEUEDBYID=00000002-0000-8888-8000-000000000000, SYSTEM_DEFAULTWORKINGDIRECTORY=/__w/1/s, SYSTEM_DEFINITIONID=119, SYSTEM_TEAMPROJECTID=7733e1dc-3216-41a5-bf89-e82d9ed68388, VERSION=2.19.0, SYSTEM_CULTURE=en-US, AGENT_OSARCHITECTURE=X64, SONARQUBE_SCANNER_PARAMS={"sonar.host.url":"https://sonarcloud.io","sonar.token":***,"sonar.organization":"futurmasterdev","sonar.pullrequest.key":"29121","sonar.pullrequest.base":"develop","sonar.pullrequest.branch":"syy20240702tryApiTestForJava21_clientServerFailed","sonar.pullrequest.provider":"vsts","sonar.pullrequest.vsts.instanceUrl":"https://dev.azure.com/FuturMasterDev/","sonar.pullrequest.vsts.project":"FuturMaster","sonar.pullrequest.vsts.repository":"micro-service-tpm","sonar.scanner.metadataFilePath":"/__w/_temp/sonar/295523/7734dd92-7921-015a-f011-1166f64b7484/report-task.txt","sonar.projectKey":"FuturMasterDev_micro-service-tpm","sonar.projectName":"micro-service-tpm"}, FAIL_DEPRECATED_TASK=true, BUILD_DEFINITIONNAME=micro-service-tpm-YAML, FAIL_DEPRECATED_BUILD_TASK=true, SYSTEM_STAGEID=96ac2280-8cb4-5df5-99de-dd2da759617d, AZP_AGENT_IGNORE_VSTSTASKLIB=true, HOSTNAME=d13a07427309, VSTSAGENT_DOCKER_ACTION_RETRIES=true, SYSTEM_PHASEDISPLAYNAME=Build And Test, TF_BUILD=True, BUILD_CONTAINERID=18301143, AGENT_TEMPDIRECTORY=/__w/_temp, SYSTEM_PULLREQUEST_SOURCEBRANCH=refs/heads/syy20240702tryApiTestForJava21_clientServerFailed, AZP_75787_ENABLE_COLLECT=true, AGENT_TASKRESTRICTIONSENFORCEMENTMODE=Enabled, SYSTEM_JOBATTEMPT=1, AZP_75787_ENABLE_NEW_PH_LOGIC=true, SYSTEM_OIDCREQUESTURI=https://dev.azure.com/FuturMasterDev/7733e1dc-3216-41a5-bf89-e82d9ed68388/_apis/distributedtask/hubs/build/plans/0f5de03d-23bc-43d4-b5b3-7ffd139ce343/jobs/ab477ad6-9781-5b54-82ca-a0141b26726e/oidctoken, MAVEN_PROJECTBASEDIR=/__w/1/s, BUILD_REASON=PullRequest, SYSTEM_DEFINITIONNAME=micro-service-tpm-YAML, AGENT_ACCEPTTEEEULA=True, SYSTEM_PULLREQUEST_PULLREQUESTID=29121, HOME=/home/vsts_azpcontainer, SYSTEM_HOSTTYPE=build, BUILD_SOURCEVERSIONMESSAGE=Merge pull request 29121 from syy20240702tryApiTestForJava21_clientServerFailed into develop, SYSTEM_PIPELINESTARTTIME=2024-07-09 07:30:30+00:00, AGENT_WORKFOLDER=/__w, RESOURCES_TRIGGERINGCATEGORY=, AGENT_JOBSTATUS=Succeeded, BUILD_BUILDID=295523, BUILD_BINARIESDIRECTORY=/__w/1/b, USE_GIT_LONG_PATHS=true, INPUT_JDKUSERINPUTPATH=, SYSTEM_JOBDISPLAYNAME=Build And Test, SYSTEM_DEBUG=false, PIPELINE_REPOSITORY_NAME=micro-service-tpm, SYSTEM_TIMELINEID=0f5de03d-23bc-43d4-b5b3-7ffd139ce343, BUILD_DEFINITIONFOLDERPATH=\TPM, MAVEN_HOME=/usr/share/maven, COMMON_TESTRESULTSDIRECTORY=/__w/1/TestResults, AGENT_NAME=Azure Pipelines 2, VSTS_PROCESS_LOOKUP_ID=vsts_11b24f80-542d-4e0f-9eb9-b80fd4705dbe, ENV_MAVEN_ACCESS_TOKEN=VlNUUzpleUowZVhBaU9pSktWMVFpTENKaGJHY2lPaUpTVXpJMU5pSXNJbmcxZENJNkltOVBkbU42TlUxZk4zQXRTR3BKUzJ4R1dIbzVNM1ZmVmpCYWJ5SjkuZXlKdVlXMWxhV1FpT2lKaVpXWXdObVZtTXkxbFkyRXpMVFEyTkRBdFlqYzNaQzFsTnpOak56TTFOMlpqTUdFaUxDSnpZM0FpT2lKaGNIQmZkRzlyWlc0aUxDSmhkV2tpT2lKaFpUZ3hNemxoTVMwMVpXWmtMVFE1TkRFdFlqa3pNQzFrWTJNNE5HWTBOemRoTkRJaUxDSnphV1FpT2lKaVpUUTFPVGN4WWkxall6RXdMVFE1TVRrdE9EQTNaQzFpTmpBMk1qUTNOV016T0dJaUxDSndZMk1pT2lKYmUxd2lVMk52Y0dWY0lqcGNJakV4T1RzM056TXpaVEZrWXkwek1qRTJMVFF4WVRVdFltWTRPUzFsT0RKa09XVmtOamd6T0RnN2NtVm1jeTlvWldGa2N5OXplWGt5TURJME1EY3dNblJ5ZVVGd2FWUmxjM1JHYjNKS1lYWmhNakZmWTJ4cFpXNTBVMlZ5ZG1WeVJtRnBiR1ZrT3pSaU9EaGpPVGhoTFdKaVptRXRORGhrWkMwNVpEQXhMV1EwWVRVMk4yTmhOalF5Tmx3aUxGd2lVR1Z5YldsemMybHZibHdpT2pGOUxIdGNJbE5qYjNCbFhDSTZYQ0l4TVRrN056Y3pNMlV4WkdNdE16SXhOaTAwTVdFMUxXSm1PRGt0WlRneVpEbGxaRFk0TXpnNE8zSmxabk12YUdWaFpITXZaR1YyWld4dmNEczBZamc0WXprNFlTMWlZbVpoTFRRNFpHUXRPV1F3TVMxa05HRTFOamRqWVRZME1qWmNJaXhjSWxCbGNtMXBjM05wYjI1Y0lqb3hmU3g3WENKVFkyOXdaVndpT2x3aU1URTVPemMzTXpObE1XUmpMVE15TVRZdE5ERmhOUzFpWmpnNUxXVTRNbVE1WldRMk9ETTRPRHR5WldaekwyaGxZV1J6TDJSbGRtVnNiM0E3TkdJNE9HTTVPR0V0WW1KbVlTMDBPR1JrTFRsa01ERXRaRFJoTlRZM1kyRTJOREkyWENJc1hDSlFaWEp0YVhOemFXOXVYQ0k2TVgwc2Uxd2lVMk52Y0dWY0lqcGNJakV4T1RzM056TXpaVEZrWXkwek1qRTJMVFF4WVRVdFltWTRPUzFsT0RKa09XVmtOamd6T0RnN2NtVm1jeTl3ZFd4c0x6STVNVEl4TDIxbGNtZGxPelJpT0Roak9UaGhMV0ppWm1FdE5EaGtaQzA1WkRBeExXUTBZVFUyTjJOaE5qUXlObHdpTEZ3aVVHVnliV2x6YzJsdmJsd2lPak45TEh0Y0lsTmpiM0JsWENJNlhDSXhNVGs3Tnpjek0yVXhaR010TXpJeE5pMDBNV0UxTFdKbU9Ea3RaVGd5WkRsbFpEWTRNemc0TzNKbFpuTXZhR1ZoWkhNdmJXRnpkR1Z5T3pSaU9EaGpPVGhoTFdKaVptRXRORGhrWkMwNVpEQXhMV1EwWVRVMk4yTmhOalF5Tmx3aUxGd2lVR1Z5YldsemMybHZibHdpT2pGOUxIdGNJbE5qYjNCbFhDSTZYQ0l4TVRrN056Y3pNMlV4WkdNdE16SXhOaTAwTVdFMUxXSm1PRGt0WlRneVpEbGxaRFk0TXpnNE8zSmxabk12YUdWaFpITXZiV0ZwYmpzMFlqZzRZems0WVMxaVltWmhMVFE0WkdRdE9XUXdNUzFrTkdFMU5qZGpZVFkwTWpaY0lpeGNJbEJsY20xcGMzTnBiMjVjSWpveGZWMGlMQ0pDZFdsc1pFbGtJam9pTnpjek0yVXhaR010TXpJeE5pMDBNV0UxTFdKbU9Ea3RaVGd5WkRsbFpEWTRNemc0T3pJNU5UVXlNeUlzSWtSbFprbGtJam9pTVRFNUlpd2lhbTlpY21WbUlqb2lNR1kxWkdVd00yUXRNak5pWXkwME0yUTBMV0kxWWpNdE4yWm1aREV6T1dObE16UXpPbUZpTkRjM1lXUTJMVGszT0RFdE5XSTFOQzA0TW1OaExXRXdNVFF4WWpJMk56STJaU0lzSW5Cd2FXUWlPaUoyYzNSbWN6b3ZMeTlDZFdsc1pDOUNkV2xzWkM4eU9UVTFNak1pTENKdmNtTm9hV1FpT2lJd1pqVmtaVEF6WkMweU0ySmpMVFF6WkRRdFlqVmlNeTAzWm1aa01UTTVZMlV6TkRNdVluVnBiR1JoYm1SMFpYTjBMbDlmWkdWbVlYVnNkQ0lzSW1semN5STZJbUZ3Y0M1MmMzUnZhMlZ1TG5acGMzVmhiSE4wZFdScGJ5NWpiMjBpTENKaGRXUWlPaUpoY0hBdWRuTjBiMnRsYmk1MmFYTjFZV3h6ZEhWa2FXOHVZMjl0ZkhaemJ6cGpabUUxWkRFd1lTMHhNelptTFRRek9HVXRPR05tTXkwM05UQTRNREJqWlRFME1EVWlMQ0p1WW1ZaU9qRTNNakExTURrMk16RXNJbVY0Y0NJNk1UY3lNRFV4TkRRek1IMC5XcVJYenhxLVpUZHR6TVBiVGZqWkF0T2xra1BXeGlMRGdjTmozWFA2VkgyMEVUVnlBU0k2RjVuczFUb2RQVnVEYUNQRU0tQm9HQy1tVmY5bkpxTEkxUVNFQ21GYk8xdU9TNExzd2tzbzJRY1ZvdGUyWE05UUQteEJ3SXhzQS1iaUVQVDdWa0VvM1RTeC1ad1haU0ZoSnhWOEhTYUNkTktaR05KZVd3R2FSUEpHS2dyRzUtZThxRW12QW40SjA0RkZMYUdrXzdlNXZFU3BLc21CNXdnMWE3SEhoUWJjN3hOVGFHd2lDNm1EUXkxbG1pWUFoMWNYMlNYRjFoTzdZUDZkSFN1aTE3bmFxZ29PUkZOU0s0eGVvTTNzNUcxdGZoYk1ENnRSbW5zVC1odnhTUzNHZkc2R3ktbEN2N0F5bmdLejlWWDNUcUlfM0diTFctVERKYmR0cnc=, DOCKERREGISTRY=futurmastersolutions, TASK_DISPLAYNAME=Maven package, BUILD_REPOSITORY_PROVIDER=TfsGit, SYSTEM_JOBIDENTIFIER=BuildAndTest.__default, BUILD_SOURCEVERSIONAUTHOR=ShiSheng Gao, SYSTEM_PLANID=0f5de03d-23bc-43d4-b5b3-7ffd139ce343, AGENT_CONTAINERID=d13a074273094b7db0488ec8307a0d0056b405e280b9a41273f72318ed15d546, PWD=/__w/1/s/component-test, BUILD_BUILDNUMBER=2.19.0-PullRequest29121.43, AZURE_HTTP_USER_AGENT=VSTS_cfa5d10a-136f-438e-8cf3-750800ce1405_build_119_0, AGENT_JOBNAME=Build And Test, AGENT_CONTAINERNETWORK=vsts_network_797ddcceb1d346cf98d22f70a3301824, REVISION=2.19.0-SNAPSHOT, SYSTEM_JOBPOSITIONINPHASE=1, USE_MSDEPLOY_TOKEN_AUTH=true, AGENT_ISSELFHOSTED=0, BUILD_SOURCESDIRECTORY=/__w/1/s, SYSTEM_TASKINSTANCEID=ad23f291-be59-5a67-5d93-f5334d820c7f, SYSTEM_PHASEID=2b1cf740-7e83-5b38-9f56-89c750cf5d77, SYSTEM_PHASEATTEMPT=1, SYSTEM_TASKDEFINITIONSURI=https://dev.azure.com/FuturMasterDev/, AZP_AGENT_USE_INTEROP_TO_FIND_PARENT_PROCESS=true, DOCKERIMAGENAME=futurmastersolutions/micro-service-tpm, AGENT_READONLYVARIABLES=true, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, ROSETTA2_WARNING=true, SYSTEM_WORKFOLDER=/__w, SYSTEM_PHASENAME=BuildAndTest, BUILD_REQUESTEDFOREMAIL=ssgao@futurmaster.com, FAIL_JOB_WHEN_AGENT_DIES=true, SYSTEM_ISAZUREVM=1, SYSTEM_ISSCHEDULED=False, BUILD_REQUESTEDFOR=ShiSheng Gao, BUILD_REPOSITORY_NAME=micro-service-tpm, INPUT_MAVENPATH=, AGENT_USE_FETCH_FILTER_IN_CHECKOUT_TASK=true, BUILD_REPOSITORY_URI=https://FuturMasterDev@dev.azure.com/FuturMasterDev/FuturMaster/_git/micro-service-tpm, AGENT_LOGTOBLOBSTORAGESERVICE=true, SYSTEM_TOTALJOBSINPHASE=1, SONARQUBE_SCANNER_MODE=Other, BUILD_ARTIFACTSTAGINGDIRECTORY=/__w/1/a, GIT_TERMINAL_PROMPT=0, INPUT_SRCDIRECTORIES=, AZP_75787_ENABLE_NEW_LOGIC_LOG=false, SYSTEM_TASKDISPLAYNAME=Maven package, SYSTEM_POSTLINESSPEED=10000, BUILD_REPOSITORY_CLEAN=True, AZP_AGENT_LOG_TASKNAME_IN_USERAGENT=true, AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE=true, SYSTEM_PREFERREDIRECTGETCONTAINERITEM=true, SYSTEM_TASKINSTANCENAME=Maven1, SONARQUBE_SCANNER_REPORTTASKFILE=/__w/_temp/sonar/295523/7734dd92-7921-015a-f011-1166f64b7484/report-task.txt, MAVEN_OPTS= -Xmx3072m -Dmaven.repo.local=/__w/1/.m2/repository, RETIRE_AZURERM_POWERSHELL_MODULE=true, BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT=False, SYSTEM_ISDOCKERCONTAINER=0, TASK_PUBLISHTELEMETRY=True, SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI=https://FuturMasterDev@dev.azure.com/FuturMasterDev/FuturMaster/_git/micro-service-tpm, AGENT_ID=333, RESOURCES_TRIGGERINGALIAS=, BUILD_DEFINITIONVERSION=5, AGENT_VERSION=3.241.0, AGENT_TOOLSDIRECTORY=/__t, BUILD_SOURCEBRANCHNAME=merge, SYSTEM_JOBID=ab477ad6-9781-5b54-82ca-a0141b26726e, SYSTEM_ENABLEACCESSTOKEN=SecretVariable, AGENT_USEWORKSPACEID=true, SYSTEM_PULLREQUEST_ISFORK=False, AGENT_CLOUDID=67814923-9e81-4aff-bd6f-bb62ee3fc19b, AZP_PS_ENABLE_INVOKE_PROCESS=true, SYSTEM_ARTIFACTSDIRECTORY=/__w/1/a, SONARQUBE_SERVER_VERSION=8.0.0, SYSTEM_JOBNAME=__default, MSDEPLOY_HTTP_USER_AGENT=VSTS_cfa5d10a-136f-438e-8cf3-750800ce1405_build_119_0, AGENT_MACHINENAME=fv-az355-737, SYSTEM_COLLECTIONURI=https://dev.azure.com/FuturMasterDev/, USE_MSAL=true, BUILD_REPOSITORY_ID=4b88c98a-bbfa-48dd-9d01-d4a567ca6426, SYSTEM_JOBPARALLELISMTAG=Private, SYSTEM=build, BUILD_REPOSITORY_LOCALPATH=/__w/1/s, MAVEN_CONFIG=/root/.m2, SYSTEM_STAGENAME=__default, SYSTEM_PULLREQUEST_PULLREQUESTITERATION=7, SYSTEM_JOBTIMEOUT=60, AGENT_DISABLELOGPLUGIN_TESTFILEPUBLISHERPLUGIN=true, BUILD_STAGINGDIRECTORY=/__w/1/a, OLDPWD=/__w/1/s/component-test, AGENT_CONTAINERMAPPING={
  "maven3": {
    "id": "d13a074273094b7db0488ec8307a0d0056b405e280b9a41273f72318ed15d546"
  }
}, USE_LATEST_GIT_VERSION=true, SYSTEM_PULLREQUEST_TARGETBRANCHNAME=develop, SYSTEM_STAGEATTEMPT=1, ENDPOINT_URL_SYSTEMVSSCONNECTION=https://dev.azure.com/FuturMasterDev/}),
  State(ProgressListener)=de.flapdoodle.embed.process.io.progress.Slf4jProgressListener@2cc70f6e,
  State(Command)=MongoD,
  State(Version)=GenericFeatureAwareVersion{4.4.0},
  State(Net)=Net{bindIp=127.0.0.1, port=34059, isIpv6=false},
  State(MongodArguments)=MongodArguments{syncDelay=0, useDefaultSyncDelay=false, isVerbose=false, verbosityLevel=1, isQuiet=false, useNoPrealloc=true, useSmallFiles=true, useNoJournal=true, enableTextSearch=false, auth=false, master=false, isConfigServer=false, isShardServer=false, params={}, args={}}

at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1357)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1194)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1463)
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:553)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
	... 6 more

Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0: Error creating bean with name 'syncClientServerWrapper' defined in class path resource [de/flapdoodle/embed/mongo/spring/autoconfigure/EmbeddedMongoAutoConfiguration$SyncClientServerWrapperConfig.class]: rollback after error on transition to State(RunningMongodProcess), successful reached:

.............
at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:190)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:65)
	at de.flapdoodle.embed.mongo.spring.autoconfigure.MongodWrapper.start(MongodWrapper.java:45)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1892)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
	... 72 more
Caused by: java.lang.RuntimeException: Could not start process: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$null$1(RunningMongoProcess.java:179)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
	at de.flapdoodle.types.ThrowingSupplier.lambda$andFinally$1(ThrowingSupplier.java:47)
	at de.flapdoodle.embed.mongo.transitions.RunningMongoProcess.lambda$factory$3(RunningMongoProcess.java:185)
	at de.flapdoodle.embed.process.types.RunningProcess.start(RunningProcess.java:83)
	at de.flapdoodle.embed.mongo.transitions.MongoServerStarter.result(MongoServerStarter.java:119)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:58)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:46)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:180)
	... 79 more

The following is my dependency:
        <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo</artifactId>
            <version>4.12.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.flapdoodle.embed</groupId>
            <artifactId>de.flapdoodle.embed.mongo.spring3x</artifactId>
            <version>4.12.0</version>
            <scope>test</scope>
        </dependency>

In my application.yml configuration file, i have :
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.4.0

Do you have any idea about this error? or i miss some important configuration?

**Comment by michaelmosmann** [comment]
@willgss You use debian12 in your pipeline.. there is no mongodb version 4.4.0 for debian 12 so there is a fallback to an ubuntu22 version.. which is missing libcurl.so.4. You should use a mongodb version matching your production environment and a linux distribution also matching your production environment. You can finde supported versions for debian12 here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/5b0e9b699171ab52076ca5d769609389bc9f1f06/src/test/resources/de/flapdoodle/embed/mongo/packageresolver/explainedSnapshot.txt#L78

**Comment by willgss** [comment]
@michaelmosmann 
sorry, but i could not find the useful information in the link you mentioned above. As you said, my mongodb version is 4.4.0 and is not included in debian 12, so what i need is firstly a supported mongodb version list and for each version to get the debian os version that support the mongodb version, but i did not find these information in the link above.

**Comment by michaelmosmann** [comment]
@willgss if you read the line from the link above you get: (os=Linux and bitSize=B64 and cpuType=X86 and (version is any of DEBIAN_12)) and (7.0.11-7.0.12 or 7.0.5-7.0.9) .. which means: for a debian12 (64 bit, x86) these production grade versions are available: 7.0.11-7.0.12 or 7.0.5-7.0.9

**Comment by willgss** [comment]
@michaelmosmann 
7.0.11-7.0.12 or 7.0.5-7.0.9 are the versions of mongodb?

**Comment by michaelmosmann** [comment]
@willgss for debian12 yes.. so i would recommend 7.0.12 as the newest .. and most of these newer version are available for other platforms too..

**Comment by willgss** [comment]
@michaelmosmann 
OK, i will try the versions above, thank you!

**Comment by michaelmosmann** [comment]
@willgss reopen if there are any issues left..
