### ISSUE TITLE
Tests fail in Jenkins due to java.net.UnknownHostException: fastdl.mongodb.org

### ISSUE THREAD

**Issue by Claudius10** [flapdoodle-oss/de.flapdoodle.embed.mongo#541]
Hello!

The complete stack is:

`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.mongo.MongodExecutable]: Factory method 'embeddedMongoServer' threw exception; nested exception is de.flapdoodle.embed.process.exceptions.DistributionException: prepare executable
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
	... 46 common frames omitted
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: prepare executable
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:64)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:45)
	at org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.embeddedMongoServer(EmbeddedMongoAutoConfiguration.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 47 common frames omitted
Caused by: java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.5.5.tgz
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)
	... 54 common frames omitted
Caused by: java.net.UnknownHostException: fastdl.mongodb.org
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)`

I noticed 

`java.io.IOException: Could not open inputStream for https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.5.5.tgz`

I downloaded the file from the URL and I'm wondering if there isn't a way to add it where its needed so the tests can pass because Jenkins is running inside the company intranet and I don't know if I'm able to set up a proxy or something similar to allow the connection to the URL and download the resource.

I tested running the tests in my local machine without an internet connection and it works! I think that if I place that file where it's needed they tests may work.

Any help would be greatly appreciated! 

Thank you for your time and effort!

**Comment by michaelmosmann** [comment]
@Claudius10 you have to look into an directory .embeddedmongo inside your home directory..  but i guess from the stack trace that you are using an older version of this library .. can you tell me which one (the directory layout changed with newer versions)?

**Comment by Claudius10** [comment]
@michaelmosmann the version of the library is 2.2.0

**Comment by michaelmosmann** [comment]
@Claudius10 .. hmm.. this is a little bit old.. ok. The easiest way to get what you want: start the test on a machine which matches your jenkins machine but with access to the download site. After the test just dump everything in <userHome>/.embeddedmongo and copy it to your jenkins-job-home-directory .. if a matching binary is found, no download is started.

In the long run: you should migrate to a newer version of this library if you might need a newer version of mongodb. Maybe the testcontainer project could be an alternative .. and for systems without access to the download site you can host the required artifacts yourself (and change the download base path to your server).
