### ISSUE TITLE
Intermittent IllegalStateException on CI Server 

### ISSUE THREAD

**Issue by btiernay** [flapdoodle-oss/de.flapdoodle.embed.mongo#71]
I've been getting intermittent issues like this for a while now, so I decided to make the next move here :)

```
Error Message

Couldn't kill mongod process!

----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/embedmongo.flapdoodle.de/issues

Thank you:)
----------------------------------------------------

Stacktrace

java.lang.IllegalStateException: Couldn't kill mongod process!

----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/embedmongo.flapdoodle.de/issues

Thank you:)
----------------------------------------------------


    at de.flapdoodle.embed.process.runtime.ProcessControl.waitForProcessGotKilled(ProcessControl.java:193)
    at de.flapdoodle.embed.process.runtime.ProcessControl.stop(ProcessControl.java:77)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.stopProcess(AbstractProcess.java:169)
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:100)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:150)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:98)
    at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:52)
    at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:48)
    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:36)
    at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:99)
    at org.icgc.dcc.test.mongodb.EmbeddedMongo.createProcess(EmbeddedMongo.java:127)
    at org.icgc.dcc.test.mongodb.EmbeddedMongo.start(EmbeddedMongo.java:96)
    at org.icgc.dcc.test.mongodb.EmbeddedMongo.access$100(EmbeddedMongo.java:47)
    at org.icgc.dcc.test.mongodb.EmbeddedMongo$1.evaluate(EmbeddedMongo.java:68)
    at org.junit.rules.RunRules.evaluate(RunRules.java:18)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
Standard Output

22:11:53.958 [main] INFO  o.i.dcc.test.mongodb.EmbeddedMongo - Starting embedded Mongo...
Extract /var/lib/jenkins/.embedmongo/linux/mongodb-linux-x86_64-2.4.6.tgz START
Extract /var/lib/jenkins/.embedmongo/linux/mongodb-linux-x86_64-2.4.6.tgz DONE
Standard Error

Nov 27, 2013 10:12:16 PM de.flapdoodle.embed.process.runtime.AbstractProcess <init>
SEVERE: Could not start process: null
Nov 27, 2013 10:12:16 PM MongodProcess ctor
INFO: de.flapdoodle.embed.mongo.config.MongodConfigBuilder$ImmutableMongodConfig@1c3627d1
Nov 27, 2013 10:12:16 PM de.flapdoodle.embed.mongo.AbstractMongoProcess stopInternal
INFO: try to stop mongod
Nov 27, 2013 10:12:16 PM de.flapdoodle.embed.mongo.runtime.Mongod sendShutdown
WARNING: sendShutdown localhost/127.0.0.1:51590
Nov 27, 2013 10:12:16 PM de.flapdoodle.embed.mongo.AbstractMongoProcess stopInternal
WARNING: could not stop mongod with db command, try next
Nov 27, 2013 10:12:16 PM de.flapdoodle.embed.mongo.AbstractMongoProcess stopInternal
WARNING: could not stop mongod, try next
Nov 27, 2013 10:12:16 PM de.flapdoodle.embed.mongo.AbstractMongoProcess stopInternal
WARNING: could not stop mongod the second time, try one last thing
Nov 27, 2013 10:12:16 PM de.flapdoodle.embed.process.runtime.ProcessControl stopOrDestroyProcess
INFO: stopOrDestroyProcess: process hasn't exited 
```

**Comment by vladimir-belous** [comment]
@michaelmosmann I've faced same issue on Teamcity
@mudlee thanks for the workaround.

**Comment by michaelmosmann** [comment]
.. i should write a check.

**Comment by jmlrt** [comment]
Hi!

I've had the same problems in Debian Jessie after the last kernel upgrade.
I encountered the problem inside a docker container running on 2 different Debian Jessie servers but I think that it can be reproduced without docker has it seems related to the kernel which is shared between debian host and the guest container.

 * Initial State: Everything is OK
   * Debian Kernel: `Linux docker-1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`
   * Docker: `Docker version 1.9.1, build a34a1d5`

 * After Kernel Upgrade: We have `Couldn't kill mongod process!` and the process are in uninterruptible process (D) state.
  * Debian Kernel: `Linux docker-1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux`
  * Docker: `Docker version 1.9.1, build a34a1d5`

 * After Kernel Downgrade: Everything is OK
  * Downgrade command: `apt install linux-image-3.16.0-4-amd64=3.16.7-ckt11-1+deb8u3 linux-headers-3.16.0-4-amd64=3.16.7-ckt11-1+deb8u3 linux-headers-3.16.0-4-common=3.16.7-ckt11-1+deb8u3 linux-headers-3.16.0-4-amd64=3.16.7-ckt11-1+deb8u3 linux-compiler-gcc-4.8-x86=3.16.7-ckt11-1+deb8u3 linux-libc-dev:amd64=3.16.7-ckt11-1+deb8u3` 
  * Debian Kernel: `Linux docker-1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`
  * Docker: `Docker version 1.9.1, build a34a1d5`

**Comment by ndrone** [comment]
I saw the same issue tonight. I did find a workaround if you are using Maven with the `maven-surefire-plugin` by setting the `<forkCount>1</forkCount>` and `<reuseForks>false</reuseForks>` I was able to get all of my integration tests to run smoothly.
