### ISSUE TITLE
Operation on server localhost:64955 failed

### ISSUE THREAD

**Issue by samiTab** [flapdoodle-oss/de.flapdoodle.embed.mongo#88]
Hi all,

I am using embedmongo 1.43 and have a strange bug when launching a series of tests of my application.

All my tests extends the following class:

public abstract class InitTest{
    private static MongodExecutable mongodExecutable = null;
    private static MongodProcess _mongod = null;

```
@BeforeClass
public static void dohh() throws Exception{
    final MongodStarter runtime = MongodStarter.getDefaultInstance();
    int port = myOwnRandPortNumber()
    IMongodConfig mongodConfig = new MongodConfigBuilder()
    .version(Version.Main.PRODUCTION)
    .net(new Net(port, Network.localhostIsIPv6()))
    .configServer(false)
    .build(); 

    try{
        mongodExecutable = runtime.prepare(mongodConfig);
         _mongod = mongodExecutable.start();
    }catch(Exception e){
        e.printStackTrace();
    }
}
@AfterClass
public  static void donn() throws InterruptedException{
    if(_mongod != null){
        _mongod.stop();
    }

if (mongodExecutable != null){
        mongodExecutable.stop();
    }
}
```

}

maven build with success my project, but when executing the same under eclipse I have an : "com.mongodb.MongoException$Network: Operation on server localhost:64955 failed" error on 2 among my 12 tests, knowing that when I execute the same failed tests one by one they succeed, and when I remove the @AfterClass above function and executing all test in the same  time, the all is well and my tests success without errors under eclipse, but I think it is not a clean way to remove cleanup operations  (  mongodExecutable.stop() and  _mongod.stop()).
Here is the @AfterClass function

```
   @AfterClass
public  static void donn() throws InterruptedException{
    if(_mongod != null){
        _mongod.stop();
    }
        if (mongodExecutable != null){
                    mongodExecutable.stop();
    }
}
```

I have also increase the MAX_CONNECTIONS within my MongoClient by doing an
builder.connectionsPerHost(30) but no way,

Please if any one can give me some Hints to fix this, it will be great
Thanks in advance, and here is the stack trace of my execution : 

com.mongodb.MongoException$Network: Operation on server localhost:64955 failed
    at com.mongodb.DBTCPConnector.doOperation(DBTCPConnector.java:218)
    at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:185)
    at com.mongodb.DBCollectionImpl.insertWithWriteProtocol(DBCollectionImpl.java:519)
    at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:187)
    at com.mongodb.DBCollectionImpl.insert(DBCollectionImpl.java:159)
    at com.mongodb.DBCollection.insert(DBCollection.java:161)
    at com.mongodb.DBCollection.insert(DBCollection.java:107)
    at com.mongodb.DBCollection.save(DBCollection.java:966)
    at org.mongodb.morphia.DatastoreImpl.tryVersionedUpdate(DatastoreImpl.java:1024)
    at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:980)
    at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1055)
    at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1042)
    at net.atos.xa.rm.mongodb.repo.AbstractMongoDBBackend.store(AbstractMongoDBBackend.java:89)
    at net.atos.xa.rm.mongodb.repo.AbstractMongoDBPipeRepo.store(AbstractMongoDBPipeRepo.java:18)
    at net.atos.xa.rm.api.pipe.AbstractPipeCreator.create(AbstractPipeCreator.java:101)
    at net.atos.xa.rm.api.pipe.AbstractPipeCreator.apply(AbstractPipeCreator.java:124)
    at net.atos.xa.rm.api.pipe.WalkThroughPipe.done(WalkThroughPipe.java:52)
    at net.atos.xa.rm.mongodb.repo.UseOfRMMaintainerTest.testFullConfigRMMaintainerUsesTest(UseOfRMMaintainerTest.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.net.SocketException: Software caused connection abort: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(Unknown Source)
    at java.net.SocketOutputStream.write(Unknown Source)
    at org.bson.io.PoolOutputBuffer.pipe(PoolOutputBuffer.java:153)
    at com.mongodb.OutMessage.pipe(OutMessage.java:236)
    at com.mongodb.DBPort$1.execute(DBPort.java:140)
    at com.mongodb.DBPort$1.execute(DBPort.java:135)
    at com.mongodb.DBPort.doOperation(DBPort.java:164)
    at com.mongodb.DBPort.call(DBPort.java:135)
    at com.mongodb.DBPort.findOne(DBPort.java:189)
    at com.mongodb.DBPort.runCommand(DBPort.java:197)
    at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:137)
    at com.mongodb.DBTCPConnector.access$000(DBTCPConnector.java:42)
    at com.mongodb.DBTCPConnector$1.execute(DBTCPConnector.java:190)
    at com.mongodb.DBTCPConnector$1.execute(DBTCPConnector.java:185)
    at com.mongodb.DBTCPConnector.doOperation(DBTCPConnector.java:214)
    ... 42 more

Regards,

**Comment by Loki-Afro** [comment]
@samiTab if the problem does actuall exist with the current version, please file a new Issue with an example Project. I will close this issue for now.
