### ISSUE TITLE
question: problem with download distribution. How to manually setup the distribution archive location ?

### ISSUE THREAD

**Issue by rschlick** [flapdoodle-oss/de.flapdoodle.embed.mongo#89]
Hello,

When embed mongo try to download the distribution, I obtain a connection refused exception. I was try to put manually the mongodb archive file in $user_home/.embedmongo/linux/mongodb-linux-x86_64-2.4.10.tgz
But, embed mongo still try to download the distribution. My system is a linux 64bits.
Any idea ?

Thanks you !

java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1003)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:951)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
    at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:76)
    at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
    at de.flapdoodle.embed.process.store.CachingArtifactStore.checkDistribution(CachingArtifactStore.java:56)
    at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:52)

**Comment by mbhuie** [comment]
> just copy mongodb-linux-x86_64-2.6.1.tgz to ${user.home}/.embedmongo/linux/ where user is the user your jenkins job is running...

This fixed the problem on linux where the build server is running. But I still face the same issue on windows. What are the directories for Windows

**Comment by ChrisZ2** [comment]
Could you tell me what is the directory of mongodb-linux-x86_64-2.6.1.zip on windows?

**Comment by ChrisZ2** [comment]
I made a fold  ${user.home}/.embedmongo/win32/ and it worked!

**Comment by givenm** [comment]
@ChrisZ2 Thanks a lot. You saved me after hours of battling behind proxy. Your solution works :)

**Comment by Anomalyzero** [comment]
I am having a similar problem. I am trying to download the distribution through our own internal repositories by configuring my own IDownloadConfig/IRuntimeConfig like so:

```java
protected void setUp() throws Exception {
        IDownloadConfig downloadConfig = new DownloadConfigBuilder().defaults()
                .downloadPath("https://my.download.repo.com").build();

        IRuntimeConfig runtimeConfig = new RuntimeConfigBuilder().defaults(
                Command.MongoD).artifactStore(new ExtractedArtifactStoreBuilder()
                .download(downloadConfig)).build();

        IMongodConfig mongoConfig = new MongodConfigBuilder()
                .version(Version.Main.PRODUCTION)
                .net(new Net(port, Network.localhostIsIPv6())).build();

        port = Network.getFreeServerPort();
        _mongodExe = MongodStarter.getInstance(runtimeConfig).prepare(mongoConfig);
        _mongod = _mongodExe.start();

        super.setUp();

        _mongo = new MongoClient("localhost", port);
    }
```

However, when I actually attempt to build/test I receive the following Stacktrace:
```
java.lang.RuntimeException: PackageResolver(interface de.flapdoodle.embed.process.config.store.IPackageResolver) not set
	at de.flapdoodle.embed.process.builder.AbstractEmbeddedBuilder.get(AbstractEmbeddedBuilder.java:68)
	at de.flapdoodle.embed.process.config.store.DownloadConfigBuilder.build(DownloadConfigBuilder.java:137)
	at my.package.path.AbstractMongoDBTest.setUp(AbstractMongoDBTest.java:60)
	at junit.framework.TestCase.runBare(TestCase.java:139)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```
I've been trying awhile now to get around this, but nothing I've tried seems to change the error at all. 

Anyone care to relieve me of my ignorance? Thanks

**Comment by cawena** [comment]
On my side that was a proxy issue. I just add the config on my jenkins file.

.....
stages {
        stage('Build') {
            tools {
                jdk "JDK-11"
            }
            steps {
                sh 'echo $JAVA_HOME'
                sh '$JAVA_HOME/bin/java -version'
                sh 'java -version'

                withMaven(maven: 'maven_3_6_3') {
                    sh 'mvn test -Dhttps.proxyHost=yourServerHostHere -Dhttps.proxyPort=8080 -Dhttp.proxyHost=yourServerHostHere -Dhttp.proxyPort=8080'
                    sh 'mvn clean install'
                }
            }
        }
        
        .....

**Comment by michaelmosmann** [comment]
There is a new release, so i close this..
