### ISSUE TITLE
DistributionException "Not in GZIP format" with 1.46.0

### ISSUE THREAD

**Issue by julienroubieu** [flapdoodle-oss/de.flapdoodle.embed.mongo#96]
Hello,

I have an issue when trying to use 1.46.0 via Maven: the download and extraction fails with the following exception.
Everything works fine if I use 1.45 instead.
I'm trying to use: Version.Main.V2_6

Any idea about what is causing this?

```
de.flapdoodle.embed.process.exceptions.DistributionException: java.util.zip.ZipException: Not in GZIP format
[error]     at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:65)
[error]     at integration.EmbeddedMongo.start(EmbeddedMongo.java:39)
[error]     ...
[error] Caused by: java.util.zip.ZipException: Not in GZIP format
[error]     at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
[error]     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:78)
[error]     at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
[error]     at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:43)
[error]     at de.flapdoodle.embed.process.extract.TgzExtractor.archiveStream(TgzExtractor.java:40)
[error]     at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:51)
[error]     at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:77)
[error]     at de.flapdoodle.embed.process.store.CachingArtifactStore$FilesWithCounter.use(CachingArtifactStore.java:129)
[error]     at de.flapdoodle.embed.process.store.CachingArtifactStore.extractFileSet(CachingArtifactStore.java:75)
[error]     at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:53)
[error]     ... 52 more
```

**Comment by Salina73** [comment]
> Running https://github.com/julienroubieu/embed-mongo-issue on my machine works well.. Hmm.. bad. My best guess: downloaded archive is corrupt. Removing from cache (.embedmongo) will trigger a new download... and maybe this time everything works well.

how to download it again?
